Repository OCA/partner-contact, pull requests merged in 2019-10, with the labels that each got.

#787 [13.0][MIG]partner_fax
  partner_fax/README.rst
  partner_fax/__init__.py
  partner_fax/__manifest__.py
  partner_fax/i18n/de.po
  partner_fax/i18n/es.po
  partner_fax/i18n/fr.po
  partner_fax/i18n/hr_HR.po
  partner_fax/i18n/it.po
  partner_fax/i18n/nl.po
  partner_fax/i18n/partner_fax.pot
  partner_fax/i18n/sl.po
  partner_fax/models/__init__.py
  partner_fax/models/res_partner.py
  partner_fax/readme/CONTRIBUTORS.rst
  partner_fax/readme/DESCRIPTION.rst
  partner_fax/readme/USAGE.rst
  partner_fax/static/description/icon.png
  partner_fax/static/description/index.html
  partner_fax/views/res_partner.xml
Labels: approved

#657 11.0 mig partner noncommercial
  partner_noncommercial/README.rst
  partner_noncommercial/__init__.py
  partner_noncommercial/__manifest__.py
  partner_noncommercial/i18n/nl.po
  partner_noncommercial/i18n/partner_noncommercial.pot
  partner_noncommercial/i18n/sl.po
  partner_noncommercial/i18n_extra/en.po
  partner_noncommercial/i18n_extra/nl.po
  partner_noncommercial/readme/CONFIGURE.rst
  partner_noncommercial/readme/CONTRIBUTORS.rst
  partner_noncommercial/readme/DESCRIPTION.rst
  partner_noncommercial/readme/USAGE.rst
  partner_noncommercial/static/description/index.html
  partner_noncommercial/views/menu.xml
  partner_noncommercial/views/res_partner.xml
Labels: approved, ready to merge

#782 [FIX] [partner_firstname] don't update user's name in onchange
  partner_firstname/models/res_partner.py
Labels: approved, needs review

#776 Add normalization and optional uniqueness constraint to partner_email_check
  partner_email_check/README.rst
  partner_email_check/__manifest__.py
  partner_email_check/models/__init__.py
  partner_email_check/models/base_config_settings.py
  partner_email_check/models/res_partner.py
  partner_email_check/tests/test_partner_email_check.py
  partner_email_check/views/base_config_view.xml
  requirements.txt
Labels: approved, needs review
