Repository OCA/partner-contact, pull requests merged in 2019-04, with the labels that each got.

#720 [ADD] partner_email_unique: new module
  partner_email_unique/README.rst
  partner_email_unique/__init__.py
  partner_email_unique/__openerp__.py
  partner_email_unique/models/__init__.py
  partner_email_unique/models/res_partner.py
  partner_email_unique/readme/CONTRIBUTORS.rst
  partner_email_unique/readme/DESCRIPTION.rst
  partner_email_unique/readme/USAGE.rst
  partner_email_unique/static/description/index.html
  partner_email_unique/tests/__init__.py
  partner_email_unique/tests/test_res_partner_email.py
Labels: approved

#721 [MIG] crm_deduplicate_acl > partner_deduplicate_acl: Migration to 12.0
  partner_deduplicate_acl/README.rst
  partner_deduplicate_acl/__init__.py
  partner_deduplicate_acl/__manifest__.py
  partner_deduplicate_acl/i18n/de.po
  partner_deduplicate_acl/i18n/es.po
  partner_deduplicate_acl/i18n/hr.po
  partner_deduplicate_acl/i18n/it.po
  partner_deduplicate_acl/i18n/nl_NL.po
  partner_deduplicate_acl/i18n/partner_deduplicate_acl.pot
  partner_deduplicate_acl/i18n/pt_BR.po
  partner_deduplicate_acl/i18n/sk.po
  partner_deduplicate_acl/i18n/sl.po
  partner_deduplicate_acl/i18n/tr.po
  partner_deduplicate_acl/i18n/zh_CN.po
  partner_deduplicate_acl/images/perms.png
  partner_deduplicate_acl/readme/CONFIGURE.rst
  partner_deduplicate_acl/readme/CONTRIBUTORS.rst
  partner_deduplicate_acl/readme/DESCRIPTION.rst
  partner_deduplicate_acl/readme/USAGE.rst
  partner_deduplicate_acl/security/partner_deduplicate_acl_security.xml
  partner_deduplicate_acl/static/description/icon.png
  partner_deduplicate_acl/static/description/icon.svg
  partner_deduplicate_acl/static/description/index.html
  partner_deduplicate_acl/tests/__init__.py
  partner_deduplicate_acl/tests/test_partner_deduplicate_acl.py
  partner_deduplicate_acl/views/base_partner_merge_view.xml
  partner_deduplicate_acl/wizards/__init__.py
  partner_deduplicate_acl/wizards/partner_merge.py
  partner_deduplicate_acl/wizards/partner_merge_view.xml
Labels: approved, ready to merge

#726 [MIG] crm_deduplicate_filter > partner_deduplicate_filter: Migration to 12.0
  partner_deduplicate_filter/README.rst
  partner_deduplicate_filter/__init__.py
  partner_deduplicate_filter/__manifest__.py
  partner_deduplicate_filter/i18n/crm_deduplicate_filter.pot
  partner_deduplicate_filter/i18n/de.po
  partner_deduplicate_filter/i18n/es.po
  partner_deduplicate_filter/i18n/hr.po
  partner_deduplicate_filter/i18n/nl_NL.po
  partner_deduplicate_filter/i18n/sk.po
  partner_deduplicate_filter/i18n/sl.po
  partner_deduplicate_filter/i18n/tr.po
  partner_deduplicate_filter/readme/CONTRIBUTORS.rst
  partner_deduplicate_filter/readme/DESCRIPTION.rst
  partner_deduplicate_filter/readme/USAGE.rst
  partner_deduplicate_filter/static/description/icon.png
  partner_deduplicate_filter/static/description/icon.svg
  partner_deduplicate_filter/static/description/index.html
  partner_deduplicate_filter/tests/__init__.py
  partner_deduplicate_filter/tests/test_partner_deduplicate_filter.py
  partner_deduplicate_filter/wizards/__init__.py
  partner_deduplicate_filter/wizards/partner_merge.py
  partner_deduplicate_filter/wizards/partner_merge_view.xml
Labels: approved

#730 [FIX] partner_email_unique: allow empty emails
  partner_email_unique/models/res_partner.py
  partner_email_unique/tests/test_res_partner_email.py
Labels: approved

#543 11.0 mig partner email check
  partner_email_check/README.rst
  partner_email_check/__init__.py
  partner_email_check/__manifest__.py
  partner_email_check/models/__init__.py
  partner_email_check/models/res_partner.py
  partner_email_check/tests/__init__.py
  partner_email_check/tests/test_partner_email_check.py
  requirements.txt
Labels: approved, needs review, ready to merge

#731 [FIX] make res.partner.relation.all#write work for multiple records
  partner_multi_relation/models/res_partner_relation_all.py
Labels: approved, needs review, ready to merge
