Repository OCA/partner-contact, pull requests merged in 2019-06, with the labels that each got.

#744 [MIG] portal_partner_select_all: Migration to 12.0
  portal_partner_select_all/README.rst
  portal_partner_select_all/__init__.py
  portal_partner_select_all/__manifest__.py
  portal_partner_select_all/i18n/portal_partner_select_all.pot
  portal_partner_select_all/readme/CONTRIBUTORS.rst
  portal_partner_select_all/readme/DESCRIPTION.rst
  portal_partner_select_all/readme/USAGE.rst
  portal_partner_select_all/static/description/icon.png
  portal_partner_select_all/static/description/index.html
  portal_partner_select_all/wizard/__init__.py
  portal_partner_select_all/wizard/portal_wizard.py
  portal_partner_select_all/wizard/portal_wizard.xml
Labels: approved

#441 [IMP] backport 9.0 mechanism
  base_partner_merge/README.rst
  base_partner_merge/__init__.py
  base_partner_merge/__openerp__.py
  base_partner_merge/base_partner_merge.py
  base_partner_merge/hooks.py
  base_partner_merge/models/__init__.py
  base_partner_merge/models/base_partner_merge.py
  base_partner_merge/models/base_partner_merge_automatic_wizard.py
  base_partner_merge/models/res_partner.py
  base_partner_merge/tests/__init__.py
  base_partner_merge/tests/test_merge.py
  base_partner_merge/validate_email.py
  base_partner_merge/views/base_partner_merge.xml
  oca_dependencies.txt
Labels: needs review

#706 [10.0][ADD] partner_bank_sort_code: Add Sort Code on Banks
  partner_bank_sort_code/README.rst
  partner_bank_sort_code/__init__.py
  partner_bank_sort_code/__manifest__.py
  partner_bank_sort_code/models/__init__.py
  partner_bank_sort_code/models/res_bank.py
  partner_bank_sort_code/readme/CONTRIBUTORS.rst
  partner_bank_sort_code/readme/DESCRIPTION.rst
  partner_bank_sort_code/readme/HISTORY.rst
  partner_bank_sort_code/readme/USAGE.rst
  partner_bank_sort_code/static/description/icon.png
  partner_bank_sort_code/static/description/index.html
  partner_bank_sort_code/tests/__init__.py
  partner_bank_sort_code/tests/test_sort_code.py
  partner_bank_sort_code/views/res_bank.xml
  setup/partner_bank_sort_code/odoo/__init__.py
  setup/partner_bank_sort_code/odoo/addons/__init__.py
  setup/partner_bank_sort_code/odoo/addons/partner_bank_sort_code
  setup/partner_bank_sort_code/setup.py
Labels: approved, ready to merge

#479 [FIX] Unintended trigger of 'street' inverse write function
  partner_street_number/__openerp__.py
  partner_street_number/views/res_partner.xml
Labels: bug, needs review
