Repository OCA/partner-contact, pull requests merged in 2019-05, with the labels that each got.

#732 [ADD] partner_priority module
  partner_priority/README.rst
  partner_priority/__init__.py
  partner_priority/__manifest__.py
  partner_priority/data/partner_priority_data.xml
  partner_priority/data/partner_priority_sequence_data.xml
  partner_priority/models/__init__.py
  partner_priority/models/partner_priority.py
  partner_priority/models/res_partner.py
  partner_priority/readme/CONTRIBUTORS.rst
  partner_priority/readme/DESCRIPTION.rst
  partner_priority/readme/USAGE.rst
  partner_priority/security/ir.model.access.csv
  partner_priority/static/description/icon.png
  partner_priority/views/partner_priority.xml
  partner_priority/views/res_partner.xml
Labels: needs review

#736 [FIX] partner_email_unique: duplicating partner sets empty email
  partner_email_unique/models/res_partner.py
  partner_email_unique/tests/test_res_partner_email.py
Labels: approved

#686 [12.0][base_partner_sequence] fix unique ref on write
  base_partner_sequence/models/partner.py
  base_partner_sequence/tests/test_base_partner_sequence.py
Labels: approved, ready to merge

#740 [10.0] [FIX] Issue #712 Need to set is_symmetric False where it is NULL.
  partner_multi_relation/__manifest__.py
  partner_multi_relation/migrations/10.0.1.0.2/post-migration.py
Labels: approved
