Repository OCA/partner-contact, pull requests merged in 2020-03, with the labels that each got.

#862 [13.0] base_vat_sanitized: Add warning in README
  base_vat_sanitized/readme/DESCRIPTION.rst
Labels: approved

#867 [12.0][IMP] - filter city zip by country in partner form
  base_location/models/res_city_zip.py
  base_location/models/res_partner.py
Labels: approved, enhancement, needs review

#863 [12.0][MIG] partner_multi_relation_tabs
  partner_multi_relation_tabs/README.rst
  partner_multi_relation_tabs/__init__.py
  partner_multi_relation_tabs/__manifest__.py
  partner_multi_relation_tabs/demo/res_partner_category_demo.xml
  partner_multi_relation_tabs/demo/res_partner_demo.xml
  partner_multi_relation_tabs/demo/res_partner_relation_demo.xml
  partner_multi_relation_tabs/demo/res_partner_relation_type_demo.xml
  partner_multi_relation_tabs/demo/res_partner_tab_demo.xml
  partner_multi_relation_tabs/i18n/da.po
  partner_multi_relation_tabs/i18n/nl.po
  partner_multi_relation_tabs/i18n/partner_multi_relation_tabs.pot
  partner_multi_relation_tabs/models/__init__.py
  partner_multi_relation_tabs/models/res_partner.py
  partner_multi_relation_tabs/models/res_partner_relation_all.py
  partner_multi_relation_tabs/models/res_partner_relation_type.py
  partner_multi_relation_tabs/models/res_partner_relation_type_selection.py
  partner_multi_relation_tabs/models/res_partner_tab.py
  partner_multi_relation_tabs/readme/CONTRIBUTORS.rst
  partner_multi_relation_tabs/readme/DESCRIPTION.rst
  partner_multi_relation_tabs/readme/USAGE.rst
  partner_multi_relation_tabs/security/ir.model.access.csv
  partner_multi_relation_tabs/static/description/icon.png
  partner_multi_relation_tabs/static/description/index.html
  partner_multi_relation_tabs/static/description/partner_multi_relation_tabs-partner-display.png
  partner_multi_relation_tabs/static/description/partner_multi_relation_tabs-partner-edit.png
  partner_multi_relation_tabs/static/description/partner_multi_relation_tabs-relation-search.png
  partner_multi_relation_tabs/static/description/partner_multi_relation_tabs-relation-type-configuration.png
  partner_multi_relation_tabs/static/description/partner_multi_relation_tabs-tab-configuration.png
  partner_multi_relation_tabs/tablib/__init__.py
  partner_multi_relation_tabs/tablib/tab.py
  partner_multi_relation_tabs/tests/__init__.py
  partner_multi_relation_tabs/tests/common.py
  partner_multi_relation_tabs/tests/test_partner_tabs.py
  partner_multi_relation_tabs/tests/test_tab.py
  partner_multi_relation_tabs/views/menu.xml
  partner_multi_relation_tabs/views/res_partner_relation_all.xml
  partner_multi_relation_tabs/views/res_partner_relation_type.xml
  partner_multi_relation_tabs/views/res_partner_tab.xml
  setup/_metapackage/setup.py
Labels: approved, migration, ready to merge

#857 [13.0][MIG] partner_vat_unique: Migration to 13.0
  partner_vat_unique/README.rst
  partner_vat_unique/__init__.py
  partner_vat_unique/__manifest__.py
  partner_vat_unique/i18n/es.po
  partner_vat_unique/i18n/it.po
  partner_vat_unique/i18n/partner_vat_unique.pot
  partner_vat_unique/i18n/pt.po
  partner_vat_unique/models/__init__.py
  partner_vat_unique/models/res_partner.py
  partner_vat_unique/readme/CONTRIBUTORS.rst
  partner_vat_unique/readme/DESCRIPTION.rst
  partner_vat_unique/readme/INSTALL.rst
  partner_vat_unique/readme/ROADMAP.rst
  partner_vat_unique/static/description/icon.png
  partner_vat_unique/static/description/index.html
  partner_vat_unique/tests/__init__.py
  partner_vat_unique/tests/test_vat_unique.py
Labels: migration
