Repository OCA/partner-contact, pull requests merged in 2020-12, with the labels that each got.

#1027 [12.0][FIX] base_location: Update name when changing city's state or country
  base_location/models/res_city_zip.py
Labels: approved, bot is merging ⏳

#1029 [13.0][FIX] base_location: Update name when changing city's state or country
  base_location/models/res_city_zip.py
Labels: approved, bot is merging ⏳

#1030 [14.0][FIX] base_location: Update name when changing city's state or country
  base_location/models/res_city_zip.py
Labels: approved, bot is merging ⏳

#1026 [14.0][FIX] partner_firstname: byte encoded string from ldap
  partner_firstname/models/res_partner.py
Labels: bot is merging ⏳

#812 [9.0][MIG] migrate module portal_partner_select_all
  portal_partner_select_all/README.rst
  portal_partner_select_all/__init__.py
  portal_partner_select_all/__openerp__.py
  portal_partner_select_all/i18n/portal_partner_select_all.pot
  portal_partner_select_all/readme/CONTRIBUTORS.rst
  portal_partner_select_all/readme/DESCRIPTION.rst
  portal_partner_select_all/readme/USAGE.rst
  portal_partner_select_all/static/description/index.html
  portal_partner_select_all/wizard/__init__.py
  portal_partner_select_all/wizard/portal_wizard.py
  portal_partner_select_all/wizard/portal_wizard.xml
Labels: approved, bot is merging ⏳, migration, needs review

#1009 [14.0][MIG] partner_priority: Migration to 14.0
  partner_priority/README.rst
  partner_priority/__init__.py
  partner_priority/__manifest__.py
  partner_priority/data/partner_priority_data.xml
  partner_priority/i18n/partner_priority.pot
  partner_priority/models/__init__.py
  partner_priority/models/partner_priority.py
  partner_priority/models/res_partner.py
  partner_priority/readme/CONTRIBUTORS.rst
  partner_priority/readme/DESCRIPTION.rst
  partner_priority/readme/USAGE.rst
  partner_priority/security/ir.model.access.csv
  partner_priority/static/description/icon.png
  partner_priority/static/description/index.html
  partner_priority/views/partner_priority.xml
  partner_priority/views/res_partner.xml
  setup/partner_priority/odoo/addons/partner_priority
  setup/partner_priority/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#909 [13.0][MIG] portal_partner_select_all: Migration to 13.0
  portal_partner_select_all/README.rst
  portal_partner_select_all/__init__.py
  portal_partner_select_all/__manifest__.py
  portal_partner_select_all/i18n/portal_partner_select_all.pot
  portal_partner_select_all/readme/CONTRIBUTORS.rst
  portal_partner_select_all/readme/DESCRIPTION.rst
  portal_partner_select_all/readme/USAGE.rst
  portal_partner_select_all/static/description/icon.png
  portal_partner_select_all/static/description/index.html
  portal_partner_select_all/tests/__init__.py
  portal_partner_select_all/tests/test_portal_partner_select_all.py
  portal_partner_select_all/wizard/__init__.py
  portal_partner_select_all/wizard/portal_wizard.py
  portal_partner_select_all/wizard/portal_wizard.xml
  setup/portal_partner_select_all/odoo/addons/portal_partner_select_all
  setup/portal_partner_select_all/setup.py
Labels: bot is merging ⏳, migration, needs review
