Repository OCA/partner-contact, pull requests merged in 2020-06, with the labels that each got.

#899 [FIX] partner_multi_relation (Smart Button Error)
  partner_multi_relation/models/res_partner.py
Labels: approved, bot is merging ⏳, bug, needs fixing

#563 [10.0] partner_changeset - Fix condition on test_enable
  partner_changeset/models/res_partner.py
  partner_changeset/tests/test_changeset_field_type.py
  partner_changeset/tests/test_changeset_flow.py
Labels: approved, bot is merging ⏳, ready to merge

#927 [13.0][IMP] partner_company_group: Change group search field after name
  partner_company_group/views/contact_view.xml
Labels: approved, bot is merging ⏳

#931 [10.0][FIX] .travis: Update to latest template
  .travis.yml
Labels: bot is merging ⏳

#930 [11.0][IMP] partner_vat_unique: More rigorous check
  partner_vat_unique/models/res_partner.py
  partner_vat_unique/tests/test_vat_unique.py
Labels: approved, bot is merging ⏳

#604 [10.0][ADD] Module which allow to track changes on partner bank account
  partner_bank_mail_thread/__init__.py
  partner_bank_mail_thread/__manifest__.py
  partner_bank_mail_thread/models/__init__.py
  partner_bank_mail_thread/models/res_partner_bank.py
  partner_bank_mail_thread/readme/CONTRIBUTORS.rst
  partner_bank_mail_thread/readme/DESCRIPTION.rst
  partner_bank_mail_thread/readme/HISTORY.rst
  partner_bank_mail_thread/readme/INSTALL.rst
  partner_bank_mail_thread/readme/ROADMAP.rst
  partner_bank_mail_thread/readme/USAGE.rst
  partner_bank_mail_thread/static/description/icon.png
  partner_bank_mail_thread/views/res_partner_bank.xml
  setup/partner_bank_mail_thread/odoo/__init__.py
  setup/partner_bank_mail_thread/odoo/addons/__init__.py
  setup/partner_bank_mail_thread/odoo/addons/partner_bank_mail_thread
  setup/partner_bank_mail_thread/setup.py
Labels: approved, bot is merging ⏳

#934 [ADD] partner_contact_access_link: reach contact full form
  partner_contact_access_link/README.rst
  partner_contact_access_link/__init__.py
  partner_contact_access_link/__manifest__.py
  partner_contact_access_link/models/__init__.py
  partner_contact_access_link/models/res_partner.py
  partner_contact_access_link/readme/CONTRIBUTORS.rst
  partner_contact_access_link/readme/DESCRIPTION.rst
  partner_contact_access_link/readme/USAGE.rst
  partner_contact_access_link/static/description/full-form.gif
  partner_contact_access_link/static/description/icon.png
  partner_contact_access_link/static/description/index.html
  partner_contact_access_link/views/res_partner_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#937 [FIX] partner_vat_unique: constrain on company change
  partner_vat_unique/models/res_partner.py
Labels: approved, bot is merging ⏳
