Repository OCA/partner-contact, pull requests merged in 2020-10, with the labels that each got.

#966 [13.0][FIX] partner_multi_relation: Fixing problems with migration of computed fields with search f…
  partner_multi_relation/models/res_partner.py
  partner_multi_relation/models/res_partner_relation_all.py
Labels: approved, bot is merging ⏳

#969 [FIX] partner_second_lastname: False value should be set on lastname2
  partner_second_lastname/models/res_partner.py
  partner_second_lastname/tests/test_name.py
Labels: approved, bot is merging ⏳

#970 [FIX] partner_second_lastname: False value should be set on lastname2
  partner_second_lastname/models/res_partner.py
  partner_second_lastname/tests/test_name.py
Labels: bot is merging ⏳

#977 Change connection to ec.europa.eu from http to https
  base_location_nuts/tests/test_base_location_nuts.py
  base_location_nuts/wizard/nuts_import.py
Labels: approved, bot is merging ⏳, enhancement

#978 [12.0] Change connection to ec.europa.eu from http to https
  base_location_nuts/tests/test_base_location_nuts.py
  base_location_nuts/wizard/nuts_import.py
Labels: bot is merging ⏳

#980 [FIX] partner_second_lastname: False value should be set on lastname2
  partner_second_lastname/models/res_partner.py
  partner_second_lastname/tests/test_name.py
Labels: bot is merging ⏳

#975 [FIX][13.0] partner_identification id number check
  partner_identification/models/res_partner_id_number.py
Labels: approved, bot is merging ⏳, ready to merge

#973 [ADD] animal
  animal/README.rst
  animal/__init__.py
  animal/__manifest__.py
  animal/data/animal.breed.csv
  animal/data/animal.color.csv
  animal/data/animal.species.csv
  animal/data/ir.module.category.csv
  animal/models/__init__.py
  animal/models/animal.py
  animal/models/animal_breed.py
  animal/models/animal_color.py
  animal/models/animal_species.py
  animal/readme/CONTRIBUTORS.rst
  animal/readme/DESCRIPTION.rst
  animal/readme/USAGE.rst
  animal/security/ir.model.access.csv
  animal/security/res_groups.xml
  animal/static/description/icon.png
  animal/static/img/avatar.png
  animal/views/animal.xml
  animal/views/animal_breed.xml
  animal/views/animal_color.xml
  animal/views/animal_species.xml
  animal/views/menu.xml
Labels: bot is merging ⏳, enhancement, needs review

#986 [14.0][MIG] partner_contact_personal_information_page: Migration to 14.0
  partner_contact_personal_information_page/README.rst
  partner_contact_personal_information_page/__init__.py
  partner_contact_personal_information_page/__manifest__.py
  partner_contact_personal_information_page/i18n/da.po
  partner_contact_personal_information_page/i18n/de.po
  partner_contact_personal_information_page/i18n/en.po
  partner_contact_personal_information_page/i18n/es.po
  partner_contact_personal_information_page/i18n/fi.po
  partner_contact_personal_information_page/i18n/fr.po
  partner_contact_personal_information_page/i18n/hr_HR.po
  partner_contact_personal_information_page/i18n/it.po
  partner_contact_personal_information_page/i18n/nl.po
  partner_contact_personal_information_page/i18n/partner_contact_personal_information_page.pot
  partner_contact_personal_information_page/i18n/pt_BR.po
  partner_contact_personal_information_page/i18n/pt_PT.po
  partner_contact_personal_information_page/i18n/sl.po
  partner_contact_personal_information_page/readme/CONTRIBUTORS.rst
  partner_contact_personal_information_page/readme/DESCRIPTION.rst
  partner_contact_personal_information_page/readme/USAGE.rst
  partner_contact_personal_information_page/static/description/icon.png
  partner_contact_personal_information_page/static/description/index.html
  partner_contact_personal_information_page/views/res_partner.xml
  setup/partner_contact_personal_information_page/odoo/addons/partner_contact_personal_information_page
  setup/partner_contact_personal_information_page/setup.py
Labels: approved, bot is merging ⏳

#666 [10.0][MIG][partner_identification_gln] mig partner identification gln mgs
  partner_identification_gln/README.rst
  partner_identification_gln/__init__.py
  partner_identification_gln/__manifest__.py
  partner_identification_gln/data/partner_identification_gln.xml
  partner_identification_gln/i18n/sl.po
  partner_identification_gln/models/__init__.py
  partner_identification_gln/models/partner.py
  partner_identification_gln/static/description/icon.svg
  partner_identification_gln/tests/__init__.py
  partner_identification_gln/tests/test_gln.py
  setup/partner_identification_gln/odoo/__init__.py
  setup/partner_identification_gln/odoo/addons/__init__.py
  setup/partner_identification_gln/odoo/addons/partner_identification_gln
  setup/partner_identification_gln/setup.py
Labels: bot is merging ⏳

#985 [14.0][MIG] partner_fax: Migration to 14.0
  partner_fax/README.rst
  partner_fax/__init__.py
  partner_fax/__manifest__.py
  partner_fax/i18n/de.po
  partner_fax/i18n/es.po
  partner_fax/i18n/fr.po
  partner_fax/i18n/he.po
  partner_fax/i18n/hr_HR.po
  partner_fax/i18n/it.po
  partner_fax/i18n/nl.po
  partner_fax/i18n/partner_fax.pot
  partner_fax/i18n/pt_BR.po
  partner_fax/i18n/sl.po
  partner_fax/i18n/zh_CN.po
  partner_fax/models/__init__.py
  partner_fax/models/res_partner.py
  partner_fax/readme/CONTRIBUTORS.rst
  partner_fax/readme/DESCRIPTION.rst
  partner_fax/readme/USAGE.rst
  partner_fax/static/description/icon.png
  partner_fax/static/description/index.html
  partner_fax/views/res_partner.xml
Labels: approved, bot is merging ⏳

#990 [14.0][MIG] partner_vat_unique: Migration to 14.0
  partner_vat_unique/README.rst
  partner_vat_unique/__init__.py
  partner_vat_unique/__manifest__.py
  partner_vat_unique/i18n/es.po
  partner_vat_unique/i18n/it.po
  partner_vat_unique/i18n/partner_vat_unique.pot
  partner_vat_unique/i18n/pt.po
  partner_vat_unique/models/__init__.py
  partner_vat_unique/models/res_partner.py
  partner_vat_unique/readme/CONTRIBUTORS.rst
  partner_vat_unique/readme/DESCRIPTION.rst
  partner_vat_unique/readme/INSTALL.rst
  partner_vat_unique/readme/ROADMAP.rst
  partner_vat_unique/static/description/icon.png
  partner_vat_unique/static/description/index.html
  partner_vat_unique/tests/__init__.py
  partner_vat_unique/tests/test_vat_unique.py
  setup/partner_vat_unique/odoo/addons/partner_vat_unique
  setup/partner_vat_unique/setup.py
Labels: approved, bot is merging ⏳

#974 [ADD] animal_owner
  animal_owner/README.rst
  animal_owner/__init__.py
  animal_owner/__manifest__.py
  animal_owner/models/__init__.py
  animal_owner/models/animal.py
  animal_owner/models/res_partner.py
  animal_owner/readme/CONTRIBUTORS.rst
  animal_owner/readme/DESCRIPTION.rst
  animal_owner/readme/USAGE.rst
  animal_owner/static/description/icon.png
  animal_owner/views/animal.xml
  animal_owner/views/res_partner.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#1005 [13.0][IMP] Add missing field to ID Numbers tree view
  partner_identification/views/res_partner_id_number_view.xml
  partner_identification/views/res_partner_view.xml
Labels: approved, bot is merging ⏳
