Repository OCA/partner-contact, pull requests merged in 2020-08, with the labels that each got.

#943 [13.0][FIX] partner_fax: Add fax field to partner child_ids form
  partner_fax/views/res_partner.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#915 [ADD][12.0] partner_contact_address_default: New module to set default address for contacts
  partner_contact_address_default/README.rst
  partner_contact_address_default/__init__.py
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/i18n/es.po
  partner_contact_address_default/i18n/partner_contact_address_default.pot
  partner_contact_address_default/models/__init__.py
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/readme/CONTRIBUTORS.rst
  partner_contact_address_default/readme/DESCRIPTION.rst
  partner_contact_address_default/readme/USAGE.rst
  partner_contact_address_default/static/description/icon.png
  partner_contact_address_default/static/description/index.html
  partner_contact_address_default/tests/__init__.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
  partner_contact_address_default/views/res_partner_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#947 [12.0][IMP] .travis.yml: Update to latest template
  .travis.yml
Labels: bot is merging ⏳, enhancement

#921 [12.0][FIX] do not raise error if partner is without city_id
  base_location/models/res_partner.py
Labels: approved, bot is merging ⏳, enhancement, needs review
