Repository OCA/partner-contact, pull requests merged in 2020-02, with the labels that each got.

#803 [IMP][12.0][partner_company_group] move to the last search item the company group
  partner_company_group/views/contact_view.xml
Labels: approved

#855 [8.0] [FIX] Fix travis.
  .travis.yml
Labels: approved, needs review

#854 [13.0] [FIX] partner_firstname. Fix tests.
  partner_firstname/tests/test_partner_form.py
  partner_firstname/tests/test_user_form.py
Labels: approved, needs review, ready to merge
