Repository OCA/partner-contact, pull requests merged in 2020-09, with the labels that each got.

#954 [FIX] partner_firstname: Avoid error with demo data.
  partner_firstname/models/res_partner.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#958 [12.0][FIX] base_location_nuts missing country_id
  base_location_nuts/wizard/nuts_import.py
Labels: approved, bot is merging ⏳

#957 Added some precision about the module purpose
  partner_affiliate/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#953 [FIX] partner_second_lastname: False value should be set on lastname2
  partner_second_lastname/models/res_partner.py
  partner_second_lastname/tests/test_name.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#950 [10.0] partner-contact - Add style property into 'General Limits' group's fields, partner's financial risk sheet
  partner_financial_risk/views/res_partner_view.xml
  partner_sale_risk/__manifest__.py
  partner_sale_risk/views/res_partner_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#949 [13.0][ADD] partner_iterative_archive
  partner_iterative_archive/README.rst
  partner_iterative_archive/__init__.py
  partner_iterative_archive/__manifest__.py
  partner_iterative_archive/models/__init__.py
  partner_iterative_archive/models/res_partner.py
  partner_iterative_archive/readme/CONTRIBUTORS.rst
  partner_iterative_archive/readme/DESCRIPTION.rst
  partner_iterative_archive/tests/__init__.py
  partner_iterative_archive/tests/test_partner_iterative_archive.py
Labels: approved, bot is merging ⏳, ready to merge

#605 [8.0][MIG] Backport of partner_coc
  partner_coc/README.rst
  partner_coc/__init__.py
  partner_coc/__openerp__.py
  partner_coc/data/res_partner_id_category_data.xml
  partner_coc/i18n/am.po
  partner_coc/i18n/ar.po
  partner_coc/i18n/bg.po
  partner_coc/i18n/bs.po
  partner_coc/i18n/ca.po
  partner_coc/i18n/cs.po
  partner_coc/i18n/da.po
  partner_coc/i18n/de.po
  partner_coc/i18n/el_GR.po
  partner_coc/i18n/en_GB.po
  partner_coc/i18n/es.po
  partner_coc/i18n/es_CR.po
  partner_coc/i18n/es_EC.po
  partner_coc/i18n/es_MX.po
  partner_coc/i18n/es_VE.po
  partner_coc/i18n/et.po
  partner_coc/i18n/eu.po
  partner_coc/i18n/fi.po
  partner_coc/i18n/fr.po
  partner_coc/i18n/fr_CA.po
  partner_coc/i18n/fr_CH.po
  partner_coc/i18n/gl.po
  partner_coc/i18n/hr.po
  partner_coc/i18n/hr_HR.po
  partner_coc/i18n/hu.po
  partner_coc/i18n/it.po
  partner_coc/i18n/ja.po
  partner_coc/i18n/lt.po
  partner_coc/i18n/lv.po
  partner_coc/i18n/mk.po
  partner_coc/i18n/mn.po
  partner_coc/i18n/nb.po
  partner_coc/i18n/nb_NO.po
  partner_coc/i18n/nl.po
  partner_coc/i18n/nl_BE.po
  partner_coc/i18n/nl_NL.po
  partner_coc/i18n/pl.po
  partner_coc/i18n/pt.po
  partner_coc/i18n/pt_BR.po
  partner_coc/i18n/pt_PT.po
  partner_coc/i18n/ro.po
  partner_coc/i18n/ru.po
  partner_coc/i18n/sk.po
  partner_coc/i18n/sl.po
  partner_coc/i18n/sr@latin.po
  partner_coc/i18n/sv.po
  partner_coc/i18n/th.po
  partner_coc/i18n/tr.po
  partner_coc/i18n/tr_TR.po
  partner_coc/i18n/vi.po
  partner_coc/i18n/zh_CN.po
  partner_coc/i18n/zh_TW.po
  partner_coc/models/__init__.py
  partner_coc/models/res_partner.py
  partner_coc/views/res_partner_view.xml
Labels: bot is merging ⏳

#942 [12.0][FIX] partner_fax: Add fax field to partner child_ids form
  partner_fax/views/res_partner.xml
Labels: approved, bot is merging ⏳, ready to merge

#642 [FIX] use provided name for firstname and lastname
  partner_firstname/models/res_users.py
  partner_firstname/tests/__init__.py
  partner_firstname/tests/test_copy.py
Labels: bot is merging ⏳

#876 [13.0] Add module partner_tz
  partner_tz/__init__.py
  partner_tz/__manifest__.py
  partner_tz/readme/CONTRIBUTORS.rst
  partner_tz/readme/DESCRIPTION.rst
  partner_tz/readme/ROADMAP.rst
  partner_tz/tools/__init__.py
  partner_tz/tools/tz_utils.py
  partner_tz/views/res_partner.xml
  setup/partner_tz/odoo/addons/partner_tz
  setup/partner_tz/setup.py
Labels: bot is merging ⏳
