Repository OCA/partner-contact, pull requests merged in 2020-01, with the labels that each got.

#836 [12.0] [ADD] Domain on country_id for partner company type
  partner_company_type/models/res_partner_company_type.py
  partner_company_type/readme/CONTRIBUTORS.rst
  partner_company_type/views/res_partner.xml
  partner_company_type/views/res_partner_company_type.xml
Labels: approved, needs review

#795 [10.0] [FIX] Fix partner_email_check conflict with portal, bump version
  partner_email_check/__manifest__.py
  partner_email_check/models/res_partner.py
  partner_email_check/tests/test_partner_email_check.py
Labels: approved, ready to merge

#839 [12.0][FIX] partner_firstname. LDAP user: TypeError on name partner if byte found
  partner_firstname/models/res_partner.py
Labels: enhancement
