Repository OCA/partner-contact, pull requests merged in 2020-04, with the labels that each got.

#885 [FIX] partner_industry_Secondary: Make api constrains multi to avoid error when create a company with 2 contacts
  partner_industry_secondary/models/res_partner.py
Labels: approved, bot is merging ⏳

#884 [IMP] base_location_geonames_import: Import several countries through the same wizard.
  base_location_geonames_import/readme/CONTRIBUTORS.rst
  base_location_geonames_import/tests/test_base_location_geonames_import.py
  base_location_geonames_import/wizard/geonames_import.py
  base_location_geonames_import/wizard/geonames_import_view.xml
Labels: approved, bot is merging ⏳

#861 [13.0][MIG] partner_deduplicate_by_ref : Migration to 13.0
  partner_deduplicate_by_ref/README.rst
  partner_deduplicate_by_ref/__init__.py
  partner_deduplicate_by_ref/__manifest__.py
  partner_deduplicate_by_ref/i18n/ar.po
  partner_deduplicate_by_ref/i18n/bs.po
  partner_deduplicate_by_ref/i18n/cs.po
  partner_deduplicate_by_ref/i18n/de.po
  partner_deduplicate_by_ref/i18n/en_GB.po
  partner_deduplicate_by_ref/i18n/es.po
  partner_deduplicate_by_ref/i18n/es_CR.po
  partner_deduplicate_by_ref/i18n/es_EC.po
  partner_deduplicate_by_ref/i18n/es_MX.po
  partner_deduplicate_by_ref/i18n/et.po
  partner_deduplicate_by_ref/i18n/fr.po
  partner_deduplicate_by_ref/i18n/gl.po
  partner_deduplicate_by_ref/i18n/hr.po
  partner_deduplicate_by_ref/i18n/hu.po
  partner_deduplicate_by_ref/i18n/it.po
  partner_deduplicate_by_ref/i18n/ja.po
  partner_deduplicate_by_ref/i18n/lt.po
  partner_deduplicate_by_ref/i18n/lv.po
  partner_deduplicate_by_ref/i18n/mk.po
  partner_deduplicate_by_ref/i18n/mn.po
  partner_deduplicate_by_ref/i18n/nb.po
  partner_deduplicate_by_ref/i18n/nl.po
  partner_deduplicate_by_ref/i18n/nl_BE.po
  partner_deduplicate_by_ref/i18n/nl_NL.po
  partner_deduplicate_by_ref/i18n/partner_deduplicate_by_ref.pot
  partner_deduplicate_by_ref/i18n/pt.po
  partner_deduplicate_by_ref/i18n/pt_BR.po
  partner_deduplicate_by_ref/i18n/pt_PT.po
  partner_deduplicate_by_ref/i18n/ro.po
  partner_deduplicate_by_ref/i18n/ru.po
  partner_deduplicate_by_ref/i18n/sk.po
  partner_deduplicate_by_ref/i18n/sl.po
  partner_deduplicate_by_ref/i18n/sv.po
  partner_deduplicate_by_ref/i18n/th.po
  partner_deduplicate_by_ref/i18n/tr.po
  partner_deduplicate_by_ref/i18n/zh_CN.po
  partner_deduplicate_by_ref/i18n/zh_TW.po
  partner_deduplicate_by_ref/readme/CONTRIBUTORS.rst
  partner_deduplicate_by_ref/readme/DESCRIPTION.rst
  partner_deduplicate_by_ref/readme/USAGE.rst
  partner_deduplicate_by_ref/static/description/icon.png
  partner_deduplicate_by_ref/static/description/icon.svg
  partner_deduplicate_by_ref/static/description/index.html
  partner_deduplicate_by_ref/tests/__init__.py
  partner_deduplicate_by_ref/tests/test_partner_deduplicate_by_ref.py
  partner_deduplicate_by_ref/wizards/__init__.py
  partner_deduplicate_by_ref/wizards/partner_merge.py
  partner_deduplicate_by_ref/wizards/partner_merge_view.xml
  setup/partner_deduplicate_by_ref/odoo/addons/partner_deduplicate_by_ref
  setup/partner_deduplicate_by_ref/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#723 [FIX] partner_phone_search: Return None when name is False/empty
  partner_phone_search/README.rst
  partner_phone_search/__manifest__.py
  partner_phone_search/models/res_partner.py
Labels: bot is merging ⏳, needs review

#870 [13.0][MIG] partner_priority
  partner_priority/README.rst
  partner_priority/__init__.py
  partner_priority/__manifest__.py
  partner_priority/data/partner_priority_data.xml
  partner_priority/data/partner_priority_sequence_data.xml
  partner_priority/i18n/partner_priority.pot
  partner_priority/models/__init__.py
  partner_priority/models/partner_priority.py
  partner_priority/models/res_partner.py
  partner_priority/readme/CONTRIBUTORS.rst
  partner_priority/readme/DESCRIPTION.rst
  partner_priority/readme/USAGE.rst
  partner_priority/security/ir.model.access.csv
  partner_priority/static/description/icon.png
  partner_priority/static/description/index.html
  partner_priority/views/partner_priority.xml
  partner_priority/views/res_partner.xml
Labels: approved, bot is merging ⏳, ready to merge

#892 [12.0][FIX] base_location_geonames_import: fix test redefining builtin zip
  base_location_geonames_import/tests/test_base_location_geonames_import.py
Labels: bot is merging ⏳

#893 [12.0][FIX] partner_group: fix file permissions for res_partner.py
  partner_group/models/res_partner.py
Labels: approved, bot is merging ⏳

#887 [FIX] partner_multi_relation_tabs: use default widget many2one
  partner_multi_relation_tabs/tablib/tab.py
Labels: approved, bot is merging ⏳, ready to merge

#886 Fix symmetric tab - copy left tab id to right
  partner_multi_relation_tabs/models/res_partner_relation_type.py
Labels: bot is merging ⏳

#548 set birthdate to user lang date_format if exist
  partner_contact_birthdate/models/res_partner.py
Labels: bot is merging ⏳, needs review

#894 [12.0][FIX] Remove unnecessary test import statements
  base_partner_sequence/__init__.py
  partner_multi_relation/__init__.py
Labels: approved, bot is merging ⏳

#895 [13.0][FIX] Remove unnecessary test import statements
  base_partner_sequence/__init__.py
Labels: approved, bot is merging ⏳
