Repository OCA/partner-contact, pull requests merged in 2020-11, with the labels that each got.

#1004 [14.0][MIG] partner_contact_access_link: Migration to 14.0
  partner_contact_access_link/README.rst
  partner_contact_access_link/__init__.py
  partner_contact_access_link/__manifest__.py
  partner_contact_access_link/i18n/partner_contact_access_link.pot
  partner_contact_access_link/models/__init__.py
  partner_contact_access_link/models/res_partner.py
  partner_contact_access_link/readme/CONTRIBUTORS.rst
  partner_contact_access_link/readme/DESCRIPTION.rst
  partner_contact_access_link/readme/USAGE.rst
  partner_contact_access_link/static/description/full-form.gif
  partner_contact_access_link/static/description/icon.png
  partner_contact_access_link/static/description/index.html
  partner_contact_access_link/tests/__init__.py
  partner_contact_access_link/tests/test_partner_contact_access_link.py
  partner_contact_access_link/views/res_partner_views.xml
  setup/partner_contact_access_link/odoo/addons/partner_contact_access_link
  setup/partner_contact_access_link/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1014 [13.0][MIG] partner_deduplicate_filter
  partner_deduplicate_filter/README.rst
  partner_deduplicate_filter/__init__.py
  partner_deduplicate_filter/__manifest__.py
  partner_deduplicate_filter/i18n/crm_deduplicate_filter.pot
  partner_deduplicate_filter/i18n/de.po
  partner_deduplicate_filter/i18n/es.po
  partner_deduplicate_filter/i18n/hr.po
  partner_deduplicate_filter/i18n/nl_NL.po
  partner_deduplicate_filter/i18n/partner_deduplicate_filter.pot
  partner_deduplicate_filter/i18n/sk.po
  partner_deduplicate_filter/i18n/sl.po
  partner_deduplicate_filter/i18n/tr.po
  partner_deduplicate_filter/readme/CONTRIBUTORS.rst
  partner_deduplicate_filter/readme/DESCRIPTION.rst
  partner_deduplicate_filter/readme/USAGE.rst
  partner_deduplicate_filter/static/description/icon.png
  partner_deduplicate_filter/static/description/icon.svg
  partner_deduplicate_filter/static/description/index.html
  partner_deduplicate_filter/tests/__init__.py
  partner_deduplicate_filter/tests/test_partner_deduplicate_filter.py
  partner_deduplicate_filter/wizards/__init__.py
  partner_deduplicate_filter/wizards/partner_merge.py
  partner_deduplicate_filter/wizards/partner_merge_view.xml
  setup/partner_deduplicate_filter/odoo/addons/partner_deduplicate_filter
  setup/partner_deduplicate_filter/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1017 [13.0][FIX] partner_firstname: byte encoded string from ldap
  partner_firstname/models/res_partner.py
Labels: approved, bot is merging ⏳

#1013 [14.0][ADD] partner_phone_secondary
  partner_phone_secondary/__init__.py
  partner_phone_secondary/__manifest__.py
  partner_phone_secondary/models/__init__.py
  partner_phone_secondary/models/res_partner.py
  partner_phone_secondary/readme/CONTRIBUTORS.rst
  partner_phone_secondary/readme/DESCRIPTION.rst
  partner_phone_secondary/tests/__init__.py
  partner_phone_secondary/tests/test_partner_phone_secondary.py
  partner_phone_secondary/views/res_partner.xml
  setup/partner_phone_secondary/odoo/addons/partner_phone_secondary
  setup/partner_phone_secondary/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge
