Repository OCA/partner-contact, pull requests merged in 2020-07, with the labels that each got.

#939 [FIX] partver_vat_unique: Avoid formatting error due to missing parenthesis
  partner_vat_unique/models/res_partner.py
Labels: approved, bot is merging ⏳

#817 [12.0][MIG] partner_email_check
  partner_email_check/README.rst
  partner_email_check/__init__.py
  partner_email_check/__manifest__.py
  partner_email_check/i18n/partner_email_check.pot
  partner_email_check/models/__init__.py
  partner_email_check/models/res_config_settings.py
  partner_email_check/models/res_partner.py
  partner_email_check/readme/CONFIGURE.rst
  partner_email_check/readme/CONTRIBUTORS.rst
  partner_email_check/readme/DESCRIPTION.rst
  partner_email_check/readme/USAGE.rst
  partner_email_check/static/description/icon.png
  partner_email_check/static/description/index.html
  partner_email_check/tests/__init__.py
  partner_email_check/tests/test_partner_email_check.py
  partner_email_check/views/base_config_view.xml
  requirements.txt
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#889 [MIG] portal_partner_select_all
  portal_partner_select_all/README.rst
  portal_partner_select_all/__init__.py
  portal_partner_select_all/__manifest__.py
  portal_partner_select_all/i18n/portal_partner_select_all.pot
  portal_partner_select_all/readme/CONTRIBUTORS.rst
  portal_partner_select_all/readme/DESCRIPTION.rst
  portal_partner_select_all/readme/USAGE.rst
  portal_partner_select_all/static/description/icon.png
  portal_partner_select_all/static/description/index.html
  portal_partner_select_all/wizard/__init__.py
  portal_partner_select_all/wizard/portal_wizard.py
  portal_partner_select_all/wizard/portal_wizard.xml
Labels: approved, bot is merging ⏳

#941 [13.0][MIG]partner_contact_access_link: Migration to 13.0
  partner_contact_access_link/README.rst
  partner_contact_access_link/__init__.py
  partner_contact_access_link/__manifest__.py
  partner_contact_access_link/i18n/partner_contact_access_link.pot
  partner_contact_access_link/models/__init__.py
  partner_contact_access_link/models/res_partner.py
  partner_contact_access_link/readme/CONTRIBUTORS.rst
  partner_contact_access_link/readme/DESCRIPTION.rst
  partner_contact_access_link/readme/USAGE.rst
  partner_contact_access_link/static/description/full-form.gif
  partner_contact_access_link/static/description/icon.png
  partner_contact_access_link/static/description/index.html
  partner_contact_access_link/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#586 added cheking by states
  base_location_geonames_import/__manifest__.py
  base_location_geonames_import/wizard/geonames_import.py
Labels: bot is merging ⏳, enhancement, needs review
