Repository OCA/partner-contact, pull requests merged in 2020-05, with the labels that each got.

#866 [FIX] partner_multi_relation: Context Errors With Active ID
  partner_multi_relation/models/res_partner.py
  partner_multi_relation/views/res_partner.xml
Labels: approved, bot is merging ⏳, bug

#898 [12.0][FIX] portal_partner_select_all: fix call to unavailable self.portal_id
  portal_partner_select_all/README.rst
  portal_partner_select_all/__manifest__.py
  portal_partner_select_all/readme/DESCRIPTION.rst
  portal_partner_select_all/static/description/index.html
  portal_partner_select_all/tests/__init__.py
  portal_partner_select_all/tests/test_portal_partner_select_all.py
  portal_partner_select_all/wizard/__init__.py
  portal_partner_select_all/wizard/portal_wizard.py
Labels: approved, bot is merging ⏳, ready to merge

#901 [IMP] partner_contact_birthday: Add computed age field
  partner_contact_birthdate/README.rst
  partner_contact_birthdate/__manifest__.py
  partner_contact_birthdate/models/res_partner.py
  partner_contact_birthdate/readme/CONTRIBUTORS.rst
  partner_contact_birthdate/readme/DESCRIPTION.rst
  partner_contact_birthdate/static/description/age.png
  partner_contact_birthdate/tests/__init__.py
  partner_contact_birthdate/tests/test_res_partner.py
  partner_contact_birthdate/views/res_partner.xml
Labels: approved, bot is merging ⏳, ready to merge

#904 [10.0][IMP] partner_identification: Add active toggle
  partner_identification/views/res_partner_id_category_view.xml
  partner_identification/views/res_partner_id_number_view.xml
  partner_identification/views/res_partner_view.xml
Labels: approved, bot is merging ⏳, enhancement, ready to merge

#896 [12.0][IMP] partner_multi_relation: unlinking partner relations
  partner_multi_relation/models/res_partner_relation_all.py
  partner_multi_relation/tests/test_partner_relation_all.py
Labels: bot is merging ⏳, enhancement

#873 [12.0][MIG] partner_label
  partner_label/README.rst
  partner_label/__init__.py
  partner_label/__manifest__.py
  partner_label/i18n/cs_CZ.po
  partner_label/i18n/da.po
  partner_label/i18n/de.po
  partner_label/i18n/es.po
  partner_label/i18n/fr.po
  partner_label/i18n/hr.po
  partner_label/i18n/hr_HR.po
  partner_label/i18n/it.po
  partner_label/i18n/nl_NL.po
  partner_label/i18n/partner_label.pot
  partner_label/i18n/pt_BR.po
  partner_label/i18n/pt_PT.po
  partner_label/i18n/sl.po
  partner_label/models/__init__.py
  partner_label/models/res_company.py
  partner_label/models/res_config_settings.py
  partner_label/reports/res_partner.xml
  partner_label/static/description/icon.png
  partner_label/tests/__init__.py
  partner_label/tests/test_partner_label.py
  partner_label/views/base_config_settings.xml
Labels: approved, bot is merging ⏳

#874 [12.0][MIG] partner_noncommercial
  partner_noncommercial/README.rst
  partner_noncommercial/__init__.py
  partner_noncommercial/__manifest__.py
  partner_noncommercial/i18n/nl.po
  partner_noncommercial/i18n/partner_noncommercial.pot
  partner_noncommercial/i18n/sl.po
  partner_noncommercial/i18n_extra/en.po
  partner_noncommercial/i18n_extra/nl.po
  partner_noncommercial/readme/CONFIGURE.rst
  partner_noncommercial/readme/CONTRIBUTORS.rst
  partner_noncommercial/readme/DESCRIPTION.rst
  partner_noncommercial/readme/USAGE.rst
  partner_noncommercial/static/description/icon.png
  partner_noncommercial/static/description/index.html
  partner_noncommercial/views/menu.xml
  partner_noncommercial/views/res_partner.xml
Labels: approved, bot is merging ⏳

#910 [11.0][FIX] partner_multi_relation: unlinking partner relations
  partner_multi_relation/models/res_partner_relation_all.py
  partner_multi_relation/tests/test_partner_relation_all.py
Labels: approved, bot is merging ⏳

#891 [12.0][IMP] partner_multi_relation_tabs: improve res.partner browse performance
  partner_multi_relation_tabs/models/res_partner.py
  partner_multi_relation_tabs/tests/test_partner_tabs.py
  partner_multi_relation_tabs/views/menu.xml
Labels: bot is merging ⏳

#902 [ADD] new module : partner_contact_age_range
  partner_contact_age_range/README.rst
  partner_contact_age_range/__init__.py
  partner_contact_age_range/__manifest__.py
  partner_contact_age_range/data/age_range_cron.xml
  partner_contact_age_range/models/__init__.py
  partner_contact_age_range/models/res_partner.py
  partner_contact_age_range/models/res_partner_age_range.py
  partner_contact_age_range/readme/CONTRIBUTORS.rst
  partner_contact_age_range/readme/DESCRIPTION.rst
  partner_contact_age_range/readme/USAGE.rst
  partner_contact_age_range/security/ir.model.access.csv
  partner_contact_age_range/static/description/age_range.png
  partner_contact_age_range/static/description/configure_age_range.png
  partner_contact_age_range/static/description/icon.png
  partner_contact_age_range/static/description/index.html
  partner_contact_age_range/tests/__init__.py
  partner_contact_age_range/tests/test_res_partner_age_range.py
  partner_contact_age_range/views/res_partner_age_range_view.xml
  partner_contact_age_range/views/res_partner_view.xml
Labels: approved

#900 [MIG][13.0] partner_label
  partner_label/README.rst
  partner_label/__init__.py
  partner_label/__manifest__.py
  partner_label/i18n/cs_CZ.po
  partner_label/i18n/da.po
  partner_label/i18n/de.po
  partner_label/i18n/es.po
  partner_label/i18n/fr.po
  partner_label/i18n/hr.po
  partner_label/i18n/hr_HR.po
  partner_label/i18n/it.po
  partner_label/i18n/nl_NL.po
  partner_label/i18n/partner_label.pot
  partner_label/i18n/pt_BR.po
  partner_label/i18n/pt_PT.po
  partner_label/i18n/sl.po
  partner_label/models/__init__.py
  partner_label/models/res_company.py
  partner_label/models/res_config_settings.py
  partner_label/readme/CONFIGURE.rst
  partner_label/readme/CONTRIBUTERS.rst
  partner_label/readme/USAGE.rst
  partner_label/reports/res_partner.xml
  partner_label/static/description/icon.png
  partner_label/tests/__init__.py
  partner_label/tests/test_partner_label.py
  partner_label/views/base_config_settings.xml
Labels: approved, bot is merging ⏳, ready to merge

#684 [12.0][NEW] partner industry parent
  partner_industry_parent/README.rst
  partner_industry_parent/__init__.py
  partner_industry_parent/__manifest__.py
  partner_industry_parent/models/__init__.py
  partner_industry_parent/models/res_partner_industry.py
  partner_industry_parent/readme/CONTRIBUTORS.rst
  partner_industry_parent/readme/DESCRIPTION.rst
  partner_industry_parent/static/description/icon.png
  partner_industry_parent/static/description/index.html
  partner_industry_parent/tests/__init__.py
  partner_industry_parent/tests/test_res_partner_industry.py
  partner_industry_parent/views/res_partner_industry.xml
  setup/partner_industry_parent/odoo/addons/partner_industry_parent
  setup/partner_industry_parent/setup.py
Labels: approved, bot is merging ⏳, question, ready to merge
