Repository OCA/partner-contact, pull requests merged in 2021-05, with the labels that each got.

#1084 [13.0][ADD] sale_customer_rank & purchase_supplier_rank
  purchase_supplier_rank/__init__.py
  purchase_supplier_rank/__manifest__.py
  purchase_supplier_rank/models/__init__.py
  purchase_supplier_rank/models/purchase_order.py
  purchase_supplier_rank/readme/CONTRIBUTORS.rst
  purchase_supplier_rank/readme/DESCRIPTION.rst
  purchase_supplier_rank/static/description/icon.png
  sale_customer_rank/__init__.py
  sale_customer_rank/__manifest__.py
  sale_customer_rank/models/__init__.py
  sale_customer_rank/models/sale_order.py
  sale_customer_rank/readme/CONTRIBUTORS.rst
  sale_customer_rank/readme/DESCRIPTION.rst
  sale_customer_rank/static/description/icon.png
Labels: approved, bot is merging ⏳

#1086 [13.0][ADD] partner_manual_rank
  partner_manual_rank/__init__.py
  partner_manual_rank/__manifest__.py
  partner_manual_rank/models/__init__.py
  partner_manual_rank/models/res_partner.py
  partner_manual_rank/readme/CONTRIBUTORS.rst
  partner_manual_rank/readme/DESCRIPTION.rst
  partner_manual_rank/static/description/icon.png
  partner_manual_rank/views/res_partner.xml
Labels: approved, bot is merging ⏳, needs review

#1008 [FIX] partner_contact_address_default: can't adapt type 'res.partner'
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#1106 [13.0][FIX] partner_manual_rank: call compute when rank is incremented
  partner_manual_rank/models/res_partner.py
Labels: approved, bot is merging ⏳

#1107 [IMP] partner_tier_validation (Auto Active and New def for "is_company")
  partner_tier_validation/data/tier_definition.xml
  partner_tier_validation/models/res_partner.py
  partner_tier_validation/readme/DESCRIPTION.rst
  partner_tier_validation/tests/__init__.py
  partner_tier_validation/tests/test_tier_validation.py
Labels: bot is merging ⏳, enhancement, needs review
