Repository OCA/partner-contact, pull requests merged in 2021-04, with the labels that each got.

#1045 [14.0][MIG] portal_partner_select_all: Migration to 14.0
  portal_partner_select_all/README.rst
  portal_partner_select_all/__init__.py
  portal_partner_select_all/__manifest__.py
  portal_partner_select_all/i18n/portal_partner_select_all.pot
  portal_partner_select_all/readme/CONTRIBUTORS.rst
  portal_partner_select_all/readme/DESCRIPTION.rst
  portal_partner_select_all/readme/USAGE.rst
  portal_partner_select_all/static/description/icon.png
  portal_partner_select_all/static/description/index.html
  portal_partner_select_all/tests/__init__.py
  portal_partner_select_all/tests/test_portal_partner_select_all.py
  portal_partner_select_all/wizard/__init__.py
  portal_partner_select_all/wizard/portal_wizard.py
  portal_partner_select_all/wizard/portal_wizard.xml
  setup/portal_partner_select_all/odoo/addons/portal_partner_select_all
  setup/portal_partner_select_all/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1094 [FIX] partner_tier_validation: workflow was not working
  partner_tier_validation/__manifest__.py
  partner_tier_validation/data/tier_definition.xml
  partner_tier_validation/models/__init__.py
  partner_tier_validation/models/res_partner.py
  partner_tier_validation/models/tier_definition.py
  partner_tier_validation/models/tier_validation.py
  partner_tier_validation/readme/CONFIGURATION.rst
  partner_tier_validation/readme/CONTRIBUTORS.rst
  partner_tier_validation/readme/DESCRIPTION.rst
  partner_tier_validation/readme/INSTALL.rst
  partner_tier_validation/readme/USAGE.rst
  partner_tier_validation/views/res_partner_view.xml
Labels: bot is merging ⏳

#1083 [14.0][UPD] Eficent -> ForgeFlow
  base_location_geonames_import/__manifest__.py
  base_location_geonames_import/readme/CONTRIBUTORS.rst
  base_location_geonames_import/static/description/index.html
  base_location_geonames_import/wizard/geonames_import.py
  partner_phone_extension/__manifest__.py
  partner_phone_extension/models/res_partner.py
  partner_phone_extension/readme/CONTRIBUTORS.rst
  partner_phone_extension/static/description/index.html
Labels: approved, bot is merging ⏳, ready to merge

#1082 [13.0][UPD] Eficent -> ForgeFlow
  base_location_geonames_import/__manifest__.py
  base_location_geonames_import/readme/CONTRIBUTORS.rst
  base_location_geonames_import/static/description/index.html
  base_location_geonames_import/wizard/geonames_import.py
  partner_industry_secondary/models/res_config_settings.py
  partner_industry_secondary/models/res_partner.py
  partner_industry_secondary/models/res_partner_industry.py
  partner_industry_secondary/readme/CONTRIBUTORS.rst
  partner_industry_secondary/static/description/index.html
  partner_industry_secondary/views/res_config_settings.xml
  partner_industry_secondary/views/res_partner_industry_view.xml
  partner_industry_secondary/views/res_partner_view.xml
  partner_phone_extension/__manifest__.py
  partner_phone_extension/models/res_partner.py
  partner_phone_extension/readme/CONTRIBUTORS.rst
  partner_phone_extension/static/description/index.html
Labels: approved, bot is merging ⏳

#1080 [12.0][IMP] add addons table and fix translation status
  README.md
Labels: approved, bot is merging ⏳, ready to merge

#1100 [13.0][FIX] partner_company_group: assure no error in migration
  partner_company_group/migrations/13.0.1.0.0/pre-migration.py
Labels: approved, bot is merging ⏳, ready to merge

#1069 [13.0][MIG] partner_pricelist_search: Migration to v13.0
  partner_pricelist_search/README.rst
  partner_pricelist_search/__init__.py
  partner_pricelist_search/__manifest__.py
  partner_pricelist_search/i18n/es.po
  partner_pricelist_search/i18n/partner_pricelist_search.pot
  partner_pricelist_search/models/__init__.py
  partner_pricelist_search/models/product_pricelist.py
  partner_pricelist_search/models/res_partner.py
  partner_pricelist_search/readme/CONTRIBUTORS.rst
  partner_pricelist_search/readme/DESCRIPTION.rst
  partner_pricelist_search/readme/ROADMAP.rst
  partner_pricelist_search/static/description/icon.png
  partner_pricelist_search/static/description/index.html
  partner_pricelist_search/tests/__init__.py
  partner_pricelist_search/tests/test_partner_pricelist_search.py
  partner_pricelist_search/views/product_pricelist_views.xml
  setup/partner_pricelist_search/odoo/addons/partner_pricelist_search
  setup/partner_pricelist_search/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge
