Repository OCA/partner-contact, pull requests merged in 2021-09, with the labels that each got.

#1128 [MIG] partner_email_check: Migration to 14.0
  partner_email_check/README.rst
  partner_email_check/__init__.py
  partner_email_check/__manifest__.py
  partner_email_check/demo/res_company_demo.xml
  partner_email_check/i18n/partner_email_check.pot
  partner_email_check/models/__init__.py
  partner_email_check/models/res_company.py
  partner_email_check/models/res_config_settings.py
  partner_email_check/models/res_partner.py
  partner_email_check/readme/CONFIGURE.rst
  partner_email_check/readme/CONTRIBUTORS.rst
  partner_email_check/readme/DESCRIPTION.rst
  partner_email_check/readme/USAGE.rst
  partner_email_check/static/description/icon.png
  partner_email_check/static/description/index.html
  partner_email_check/tests/__init__.py
  partner_email_check/tests/test_partner_email_check.py
  partner_email_check/views/base_config_view.xml
  requirements.txt
  setup/partner_email_check/odoo/addons/partner_email_check
  setup/partner_email_check/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1138 [14.0][MIG] partner_pricelist_search: Migration to 14.0
  partner_pricelist_search/README.rst
  partner_pricelist_search/__init__.py
  partner_pricelist_search/__manifest__.py
  partner_pricelist_search/i18n/es.po
  partner_pricelist_search/i18n/partner_pricelist_search.pot
  partner_pricelist_search/models/__init__.py
  partner_pricelist_search/models/product_pricelist.py
  partner_pricelist_search/models/res_partner.py
  partner_pricelist_search/readme/CONTRIBUTORS.rst
  partner_pricelist_search/readme/DESCRIPTION.rst
  partner_pricelist_search/readme/ROADMAP.rst
  partner_pricelist_search/static/description/icon.png
  partner_pricelist_search/static/description/index.html
  partner_pricelist_search/tests/__init__.py
  partner_pricelist_search/tests/test_partner_pricelist_search.py
  partner_pricelist_search/views/product_pricelist_views.xml
  setup/partner_pricelist_search/odoo/addons/partner_pricelist_search
  setup/partner_pricelist_search/setup.py
Labels: approved, bot is merging ⏳

#1066 [14.0][MIG] partner_contact_address_default: Migration to 14.0
  partner_contact_address_default/README.rst
  partner_contact_address_default/__init__.py
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/i18n/es.po
  partner_contact_address_default/i18n/partner_contact_address_default.pot
  partner_contact_address_default/i18n/pt.po
  partner_contact_address_default/models/__init__.py
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/readme/CONTRIBUTORS.rst
  partner_contact_address_default/readme/DESCRIPTION.rst
  partner_contact_address_default/readme/USAGE.rst
  partner_contact_address_default/static/description/icon.png
  partner_contact_address_default/static/description/index.html
  partner_contact_address_default/tests/__init__.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
  partner_contact_address_default/views/res_partner_views.xml
  setup/partner_contact_address_default/odoo/addons/partner_contact_address_default
  setup/partner_contact_address_default/setup.py
Labels: bot is merging ⏳

#1103 [13.0][MIG] partner_create_by_vat
  partner_data_vies_populator/README.rst
  partner_data_vies_populator/__init__.py
  partner_data_vies_populator/__manifest__.py
  partner_data_vies_populator/models/__init__.py
  partner_data_vies_populator/models/res_partner.py
  partner_data_vies_populator/readme/CONTRIBUTORS.rst
  partner_data_vies_populator/readme/DESCRIPTION.rst
  partner_data_vies_populator/readme/INSTALL.rst
  partner_data_vies_populator/readme/USAGE.rst
  partner_data_vies_populator/static/description/icon.png
  partner_data_vies_populator/static/description/index.html
  partner_data_vies_populator/tests/__init__.py
  partner_data_vies_populator/tests/test_partner_data_vies_populator.py
  setup/partner_data_vies_populator/odoo/addons/partner_data_vies_populator
  setup/partner_data_vies_populator/setup.py
Labels: migration, bot is merging ⏳

#1068 [12.0] partner_multi_relation: Check reverse overlapping symmetric relations
  partner_multi_relation/models/res_partner_relation.py
Labels: bot is merging ⏳

#1137 [14.0][ADD] partner_bank_code
  partner_bank_code/__init__.py
  partner_bank_code/__manifest__.py
  partner_bank_code/models/__init__.py
  partner_bank_code/models/res_bank.py
  partner_bank_code/readme/CONTRIBUTORS.rst
  partner_bank_code/readme/DESCRIPTION.rst
  partner_bank_code/readme/USAGE.rst
  partner_bank_code/static/description/icon.png
  partner_bank_code/static/description/index.html
  partner_bank_code/views/res_bank.xml
Labels: approved, ready to merge, bot is merging ⏳
