Repository OCA/partner-contact, pull requests merged in 2021-03, with the labels that each got.

#1063 [14.0][MIG]partner_tier_validation
  partner_tier_validation/README.rst
  partner_tier_validation/__init__.py
  partner_tier_validation/__manifest__.py
  partner_tier_validation/models/__init__.py
  partner_tier_validation/models/res_partner.py
  partner_tier_validation/models/tier_validation.py
  partner_tier_validation/static/description/icon.png
  partner_tier_validation/views/res_partner_view.xml
  setup/partner_tier_validation/odoo/addons/partner_tier_validation
  setup/partner_tier_validation/setup.py
Labels: bot is merging ⏳

#1047 14.0 mig base_country_state_translatable
  base_country_state_translatable/README.rst
  base_country_state_translatable/__init__.py
  base_country_state_translatable/__manifest__.py
  base_country_state_translatable/i18n/base_country_state_translatable.pot
  base_country_state_translatable/i18n/da.po
  base_country_state_translatable/i18n/de.po
  base_country_state_translatable/i18n/es.po
  base_country_state_translatable/i18n/fr.po
  base_country_state_translatable/i18n/hr.po
  base_country_state_translatable/i18n/hr_HR.po
  base_country_state_translatable/i18n/it.po
  base_country_state_translatable/i18n/pt_BR.po
  base_country_state_translatable/i18n/sl.po
  base_country_state_translatable/models/__init__.py
  base_country_state_translatable/models/res_country.py
  base_country_state_translatable/readme/CONTRIBUTORS.rst
  base_country_state_translatable/readme/DESCRIPTION.rst
  base_country_state_translatable/readme/USAGE.rst
  base_country_state_translatable/static/description/icon.png
  base_country_state_translatable/static/description/index.html
  setup/base_country_state_translatable/odoo/addons/base_country_state_translatable
  setup/base_country_state_translatable/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#843 [ADD][12.0] add partner_address_two_lines module
  partner_address_two_lines/README.rst
  partner_address_two_lines/__init__.py
  partner_address_two_lines/__manifest__.py
  partner_address_two_lines/models/__init__.py
  partner_address_two_lines/models/ir_actions_report.py
  partner_address_two_lines/models/res_partner.py
  partner_address_two_lines/readme/CONTRIBUTORS.rst
  partner_address_two_lines/readme/DESCRIPTION.rst
  partner_address_two_lines/static/description/index.html
Labels: approved, bot is merging ⏳, needs review

#929 [13.0][MIG] - migration partner_identification_gln
  partner_identification_gln/README.rst
  partner_identification_gln/__init__.py
  partner_identification_gln/__manifest__.py
  partner_identification_gln/data/partner_identification_gln.xml
  partner_identification_gln/i18n/partner_identification_gln.pot
  partner_identification_gln/i18n/sl.po
  partner_identification_gln/models/__init__.py
  partner_identification_gln/models/res_partner_id_category.py
  partner_identification_gln/readme/CONTRIBUTORS.rst
  partner_identification_gln/readme/DESCRIPTION.rst
  partner_identification_gln/readme/INSTALL.rst
  partner_identification_gln/static/description/icon.svg
  partner_identification_gln/tests/__init__.py
  partner_identification_gln/tests/test_gln.py
  setup/partner_identification_gln/odoo/addons/partner_identification_gln
  setup/partner_identification_gln/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#967 [12.0] partner noncommercial streamline
  partner_noncommercial/README.rst
  partner_noncommercial/i18n/nl.po
  partner_noncommercial/i18n/partner_noncommercial.pot
  partner_noncommercial/i18n/sl.po
  partner_noncommercial/readme/USAGE.rst
  partner_noncommercial/static/description/index.html
  partner_noncommercial/views/menu.xml
  partner_noncommercial/views/res_partner.xml
Labels: approved, bot is merging ⏳

#1021 [14.0] partner_address_version: Migration to 14.0
  partner_address_version/README.rst
  partner_address_version/__init__.py
  partner_address_version/__manifest__.py
  partner_address_version/i18n/partner_address_version.pot
  partner_address_version/models/__init__.py
  partner_address_version/models/res_partner.py
  partner_address_version/readme/CONTRIBUTORS.rst
  partner_address_version/readme/DESCRIPTION.rst
  partner_address_version/static/description/icon.png
  partner_address_version/static/description/index.html
  partner_address_version/tests/__init__.py
  partner_address_version/tests/test_address_version.py
  partner_address_version/wizards/__init__.py
  partner_address_version/wizards/base_partner_merge.py
  setup/partner_address_version/odoo/addons/partner_address_version
  setup/partner_address_version/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#1002 [ADD] partner_route: New module
  partner_route/README.rst
  partner_route/__init__.py
  partner_route/__manifest__.py
  partner_route/models/__init__.py
  partner_route/models/partner_route.py
  partner_route/models/res_partner.py
  partner_route/readme/CONTRIBUTORS.rst
  partner_route/readme/DESCRIPTION.rst
  partner_route/readme/USAGE.rst
  partner_route/security/ir.model.access.csv
  partner_route/security/res_groups.xml
  partner_route/static/description/index.html
  partner_route/views/partner_route_view.xml
Labels: approved, bot is merging ⏳, needs review

#1070 [UPD]partner_fax:set field position after mobile
  partner_fax/views/res_partner.xml
Labels: approved, bot is merging ⏳, ready to merge

#860 Fix migration when state_id is NULL
  base_location/migrations/12.0.1.0.0/post-migration.py
Labels: bot is merging ⏳

#845 [ADD][10.0] add partner_address_two_lines module
  partner_address_two_lines/README.rst
  partner_address_two_lines/__init__.py
  partner_address_two_lines/__manifest__.py
  partner_address_two_lines/models/__init__.py
  partner_address_two_lines/models/report.py
  partner_address_two_lines/models/res_partner.py
  partner_address_two_lines/readme/CONTRIBUTORS.rst
  partner_address_two_lines/readme/DESCRIPTION.rst
  partner_address_two_lines/readme/INSTALL.rst
  partner_address_two_lines/static/description/index.html
Labels: approved, bot is merging ⏳, ready to merge

#1072 [12.0[IMP] partner_contact_birthday: Add computed age field (cherry-pick from 13.0)
  partner_contact_birthdate/README.rst
  partner_contact_birthdate/__manifest__.py
  partner_contact_birthdate/models/res_partner.py
  partner_contact_birthdate/readme/CONTRIBUTORS.rst
  partner_contact_birthdate/readme/DESCRIPTION.rst
  partner_contact_birthdate/static/description/age.png
  partner_contact_birthdate/tests/__init__.py
  partner_contact_birthdate/tests/test_res_partner.py
  partner_contact_birthdate/views/res_partner.xml
Labels: approved, bot is merging ⏳, enhancement, ready to merge

#1093 [13.0][ADD] partner_identification_unique_by_category
  partner_identification_unique_by_category/__init__.py
  partner_identification_unique_by_category/__manifest__.py
  partner_identification_unique_by_category/models/__init__.py
  partner_identification_unique_by_category/models/res_partner_id_category.py
  partner_identification_unique_by_category/models/res_partner_id_number.py
  partner_identification_unique_by_category/readme/CONTRIBUTORS.rst
  partner_identification_unique_by_category/readme/DESCRIPTION.rst
  partner_identification_unique_by_category/tests/__init__.py
  partner_identification_unique_by_category/tests/test_partner_identification_unique_by_category.py
  partner_identification_unique_by_category/views/res_partner_id_category_view.xml
  setup/partner_identification_unique_by_category/odoo/addons/partner_identification_unique_by_category
  setup/partner_identification_unique_by_category/setup.py
Labels: approved, bot is merging ⏳
