Repository OCA/partner-contact, pull requests merged in 2021-02, with the labels that each got.

#1053 [13.0][MIG] partner_contact_address_default: Migration to 13.0
  partner_contact_address_default/README.rst
  partner_contact_address_default/__init__.py
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/i18n/es.po
  partner_contact_address_default/i18n/partner_contact_address_default.pot
  partner_contact_address_default/i18n/pt.po
  partner_contact_address_default/models/__init__.py
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/readme/CONTRIBUTORS.rst
  partner_contact_address_default/readme/DESCRIPTION.rst
  partner_contact_address_default/readme/USAGE.rst
  partner_contact_address_default/static/description/icon.png
  partner_contact_address_default/static/description/index.html
  partner_contact_address_default/tests/__init__.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
  partner_contact_address_default/views/res_partner_views.xml
  setup/partner_contact_address_default/odoo/addons/partner_contact_address_default
  setup/partner_contact_address_default/setup.py
Labels: approved, bot is merging ⏳, needs review

#1052 [ADD] portal_partner_data_no_edit: New module
  portal_partner_data_no_edit/README.rst
  portal_partner_data_no_edit/__init__.py
  portal_partner_data_no_edit/__manifest__.py
  portal_partner_data_no_edit/controllers/__init__.py
  portal_partner_data_no_edit/controllers/portal.py
  portal_partner_data_no_edit/i18n/es.po
  portal_partner_data_no_edit/i18n/portal_partner_data_no_edit.pot
  portal_partner_data_no_edit/models/__init__.py
  portal_partner_data_no_edit/models/ir_ui_view.py
  portal_partner_data_no_edit/models/res_partner.py
  portal_partner_data_no_edit/readme/CONFIGURE.rst
  portal_partner_data_no_edit/readme/CREDITS.rst
  portal_partner_data_no_edit/readme/DESCRIPTION.rst
  portal_partner_data_no_edit/readme/ROADMAP.rst
  portal_partner_data_no_edit/readme/USAGE.rst
  portal_partner_data_no_edit/static/description/index.html
  portal_partner_data_no_edit/static/src/js/portal_partner_data_no_edit_tour.js
  portal_partner_data_no_edit/tests/__init__.py
  portal_partner_data_no_edit/tests/test_portal_partner_data_no_edit.py
  portal_partner_data_no_edit/views/assets.xml
  portal_partner_data_no_edit/views/portal_template.xml
  portal_partner_data_no_edit/views/res_partner_views.xml
Labels: approved, bot is merging ⏳, needs review

#1050 13.0 mig base country state translatable
  base_country_state_translatable/README.rst
  base_country_state_translatable/__init__.py
  base_country_state_translatable/__manifest__.py
  base_country_state_translatable/i18n/base_country_state_translatable.pot
  base_country_state_translatable/i18n/da.po
  base_country_state_translatable/i18n/de.po
  base_country_state_translatable/i18n/es.po
  base_country_state_translatable/i18n/fr.po
  base_country_state_translatable/i18n/hr.po
  base_country_state_translatable/i18n/hr_HR.po
  base_country_state_translatable/i18n/it.po
  base_country_state_translatable/i18n/pt_BR.po
  base_country_state_translatable/i18n/sl.po
  base_country_state_translatable/models/__init__.py
  base_country_state_translatable/models/res_country.py
  base_country_state_translatable/readme/CONTRIBUTORS.rst
  base_country_state_translatable/readme/DESCRIPTION.rst
  base_country_state_translatable/readme/USAGE.rst
  base_country_state_translatable/static/description/icon.png
  base_country_state_translatable/static/description/index.html
Labels: approved, bot is merging ⏳

#825 [ADD] New module for smart tags
  partner_tag_smart_assignation/README.rst
  partner_tag_smart_assignation/__init__.py
  partner_tag_smart_assignation/__manifest__.py
  partner_tag_smart_assignation/cron/update_cron.xml
  partner_tag_smart_assignation/migrations/11.0.1.0.0/pre-migration.py
  partner_tag_smart_assignation/models/__init__.py
  partner_tag_smart_assignation/models/res_partner_category.py
  partner_tag_smart_assignation/readme/CONTRIBUTORS.rst
  partner_tag_smart_assignation/readme/DESCRIPTION.rst
  partner_tag_smart_assignation/tests/__init__.py
  partner_tag_smart_assignation/tests/test_smart_tagger.py
  partner_tag_smart_assignation/views/smart_tagger_view.xml
Labels: bot is merging ⏳, needs review

#841 [ADD][13.0] add partner_address_two_lines module
  partner_address_two_lines/README.rst
  partner_address_two_lines/__init__.py
  partner_address_two_lines/__manifest__.py
  partner_address_two_lines/models/__init__.py
  partner_address_two_lines/models/ir_actions_report.py
  partner_address_two_lines/models/res_partner.py
  partner_address_two_lines/readme/CONTRIBUTORS.rst
  partner_address_two_lines/readme/DESCRIPTION.rst
  partner_address_two_lines/static/description/index.html
Labels: approved, bot is merging ⏳, question, ready to merge

#1062 [12.0][FIX] partner_default_sale_discount , compatibility with sale_commission
  partner_default_sale_discount/models/sale_order.py
  partner_default_sale_discount/tests/test_partner_default_sale_discount.py
Labels: approved, bot is merging ⏳

#1059 [13.0] [MIG] portal_partner_data_no_edit: MIgration to v13.0
  portal_partner_data_no_edit/README.rst
  portal_partner_data_no_edit/__init__.py
  portal_partner_data_no_edit/__manifest__.py
  portal_partner_data_no_edit/controllers/__init__.py
  portal_partner_data_no_edit/controllers/portal.py
  portal_partner_data_no_edit/i18n/es.po
  portal_partner_data_no_edit/i18n/portal_partner_data_no_edit.pot
  portal_partner_data_no_edit/models/__init__.py
  portal_partner_data_no_edit/models/ir_ui_view.py
  portal_partner_data_no_edit/models/res_partner.py
  portal_partner_data_no_edit/readme/CONFIGURE.rst
  portal_partner_data_no_edit/readme/CONTRIBUTORS.rst
  portal_partner_data_no_edit/readme/DESCRIPTION.rst
  portal_partner_data_no_edit/readme/ROADMAP.rst
  portal_partner_data_no_edit/readme/USAGE.rst
  portal_partner_data_no_edit/static/description/icon.png
  portal_partner_data_no_edit/static/description/index.html
  portal_partner_data_no_edit/static/src/js/portal_partner_data_no_edit_tour.js
  portal_partner_data_no_edit/templates/assets.xml
  portal_partner_data_no_edit/tests/__init__.py
  portal_partner_data_no_edit/tests/test_portal_partner_data_no_edit.py
  portal_partner_data_no_edit/views/portal_template.xml
  portal_partner_data_no_edit/views/res_partner_views.xml
  setup/portal_partner_data_no_edit/odoo/addons/portal_partner_data_no_edit
  setup/portal_partner_data_no_edit/setup.py
Labels: approved, bot is merging ⏳
