Repository OCA/partner-contact, pull requests merged in 2021-01, with the labels that each got.

#1042 [14.0][MIG] partner_iterative_archive: Migration to 14.0
  partner_iterative_archive/README.rst
  partner_iterative_archive/__init__.py
  partner_iterative_archive/__manifest__.py
  partner_iterative_archive/i18n/partner_iterative_archive.pot
  partner_iterative_archive/models/__init__.py
  partner_iterative_archive/models/res_partner.py
  partner_iterative_archive/readme/CONTRIBUTORS.rst
  partner_iterative_archive/readme/DESCRIPTION.rst
  partner_iterative_archive/static/description/icon.png
  partner_iterative_archive/static/description/index.html
  partner_iterative_archive/tests/__init__.py
  partner_iterative_archive/tests/test_partner_iterative_archive.py
  setup/partner_iterative_archive/odoo/addons/partner_iterative_archive
  setup/partner_iterative_archive/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#999 [14.0][MIG] partner_contact_age_range: Migration to 14.0
  partner_contact_age_range/README.rst
  partner_contact_age_range/__init__.py
  partner_contact_age_range/__manifest__.py
  partner_contact_age_range/data/age_range_cron.xml
  partner_contact_age_range/i18n/partner_contact_age_range.pot
  partner_contact_age_range/models/__init__.py
  partner_contact_age_range/models/res_partner.py
  partner_contact_age_range/models/res_partner_age_range.py
  partner_contact_age_range/readme/CONTRIBUTORS.rst
  partner_contact_age_range/readme/DESCRIPTION.rst
  partner_contact_age_range/readme/USAGE.rst
  partner_contact_age_range/security/ir.model.access.csv
  partner_contact_age_range/static/description/age_range.png
  partner_contact_age_range/static/description/configure_age_range.png
  partner_contact_age_range/static/description/icon.png
  partner_contact_age_range/static/description/index.html
  partner_contact_age_range/tests/__init__.py
  partner_contact_age_range/tests/test_res_partner_age_range.py
  partner_contact_age_range/views/res_partner_age_range_view.xml
  partner_contact_age_range/views/res_partner_view.xml
  setup/partner_contact_age_range/odoo/addons/partner_contact_age_range
  setup/partner_contact_age_range/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge

#1001 [14.0][MIG] partner_company_group: Migration to 14.0
  partner_company_group/README.rst
  partner_company_group/__init__.py
  partner_company_group/__manifest__.py
  partner_company_group/i18n/es.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/i18n/zh_CN.po
  partner_company_group/models/__init__.py
  partner_company_group/models/account_move.py
  partner_company_group/models/crm_lead.py
  partner_company_group/models/res_partner.py
  partner_company_group/models/sale_order.py
  partner_company_group/readme/CONTRIBUTORS.rst
  partner_company_group/readme/DESCRIPTION.rst
  partner_company_group/static/description/icon.png
  partner_company_group/static/description/index.html
  partner_company_group/tests/__init__.py
  partner_company_group/tests/test_partner_company_group.py
  partner_company_group/views/account_move_views.xml
  partner_company_group/views/contact_view.xml
  partner_company_group/views/opportunity_view.xml
  partner_company_group/views/sale_order_view.xml
  setup/partner_company_group/odoo/addons/partner_company_group
  setup/partner_company_group/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#1048 [12.0][ADD] partner_pricelist_search: New module
  partner_pricelist_search/README.rst
  partner_pricelist_search/__init__.py
  partner_pricelist_search/__manifest__.py
  partner_pricelist_search/i18n/es.po
  partner_pricelist_search/i18n/partner_pricelist_search.pot
  partner_pricelist_search/models/__init__.py
  partner_pricelist_search/models/product_pricelist.py
  partner_pricelist_search/models/res_partner.py
  partner_pricelist_search/readme/CONTRIBUTORS.rst
  partner_pricelist_search/readme/DESCRIPTION.rst
  partner_pricelist_search/readme/ROADMAP.rst
  partner_pricelist_search/static/description/icon.png
  partner_pricelist_search/static/description/index.html
  partner_pricelist_search/tests/__init__.py
  partner_pricelist_search/tests/test_partner_pricelist_search.py
  partner_pricelist_search/views/product_pricelist_views.xml
Labels: approved, bot is merging ⏳
