Repository OCA/partner-contact, pull requests merged in 2021-10, with the labels that each got.

#1143 [FIX] partner_multi_relation: Avoid access error on Relations button
  partner_multi_relation/models/res_partner.py
  partner_multi_relation/tests/__init__.py
  partner_multi_relation/tests/test_partner_relation_action.py
Labels: bug, bot is merging ⏳

#1129 [13.0][MIG] partner_bank_sort_code from 10.0
  partner_bank_sort_code/README.rst
  partner_bank_sort_code/__init__.py
  partner_bank_sort_code/__manifest__.py
  partner_bank_sort_code/i18n/partner_bank_sort_code.pot
  partner_bank_sort_code/models/__init__.py
  partner_bank_sort_code/models/res_bank.py
  partner_bank_sort_code/readme/CONTRIBUTORS.rst
  partner_bank_sort_code/readme/DESCRIPTION.rst
  partner_bank_sort_code/readme/HISTORY.rst
  partner_bank_sort_code/readme/USAGE.rst
  partner_bank_sort_code/static/description/icon.png
  partner_bank_sort_code/static/description/index.html
  partner_bank_sort_code/tests/__init__.py
  partner_bank_sort_code/tests/test_sort_code.py
  partner_bank_sort_code/views/res_bank.xml
  setup/partner_bank_sort_code/odoo/addons/partner_bank_sort_code
  setup/partner_bank_sort_code/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1136 [13.0][partner_affiliate][imp] modify partner views to allow you to edit the address and vat of an affiliate.
  partner_affiliate/models/res_partner.py
  partner_affiliate/views/res_partner_view.xml
Labels: bot is merging ⏳
