Repository OCA/partner-contact, pull requests merged in 2021-11, with the labels that each got.

#864 [11.0][ADD] partner_multi_name module
  partner_multi_name/.vscode/settings.json
  partner_multi_name/README.rst
  partner_multi_name/__init__.py
  partner_multi_name/__manifest__.py
  partner_multi_name/i18n/es CO.po
  partner_multi_name/i18n/es.po
  partner_multi_name/i18n/partner_other_names.pot
  partner_multi_name/models/__init__.py
  partner_multi_name/models/res_config_settings.py
  partner_multi_name/models/res_partner.py
  partner_multi_name/models/res_users.py
  partner_multi_name/static/description/icon.png
  partner_multi_name/views/res_partner_views.xml
  partner_multi_name/views/res_users_views.xml
Labels: bot is merging ⏳

#1127 [14.0][IMP] Added the field 'color' to partner_id_category.
  partner_identification/models/res_partner_id_category.py
Labels: approved, ready to merge, bot is merging ⏳

#1154 [14.0][ADD] partner_title_order
  partner_title_order/README.rst
  partner_title_order/__init__.py
  partner_title_order/__manifest__.py
  partner_title_order/models/__init__.py
  partner_title_order/models/res_partner_title.py
  partner_title_order/readme/CONTRIBUTORS.rst
  partner_title_order/readme/CREDITS.rst
  partner_title_order/readme/DESCRIPTION.rst
  partner_title_order/static/description/index.html
  partner_title_order/tests/__init__.py
  partner_title_order/tests/test_partner_title.py
  partner_title_order/views/res_partner_title_views.xml
  setup/partner_title_order/odoo/addons/partner_title_order
  setup/partner_title_order/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1159 [11.0][FIX] partner_tag_smart_assignation: invalid constrains.
  partner_tag_smart_assignation/models/res_partner_category.py
Labels: bot is merging ⏳

#1164 [15.0][MIG] animal: Migration to 15.0
  animal/README.rst
  animal/__init__.py
  animal/__manifest__.py
  animal/data/animal.breed.csv
  animal/data/animal.color.csv
  animal/data/animal.species.csv
  animal/data/ir.module.category.csv
  animal/i18n/animal.pot
  animal/i18n/es.po
  animal/models/__init__.py
  animal/models/animal.py
  animal/models/animal_breed.py
  animal/models/animal_color.py
  animal/models/animal_species.py
  animal/readme/CONTRIBUTORS.rst
  animal/readme/DESCRIPTION.rst
  animal/readme/USAGE.rst
  animal/security/ir.model.access.csv
  animal/security/res_groups.xml
  animal/static/description/icon.png
  animal/static/description/index.html
  animal/static/img/avatar.png
  animal/tests/__init__.py
  animal/tests/test_animal.py
  animal/views/animal.xml
  animal/views/animal_breed.xml
  animal/views/animal_color.xml
  animal/views/animal_species.xml
  animal/views/menu.xml
  setup/animal/odoo/addons/animal
  setup/animal/setup.py
Labels: needs review, migration

#1179 [12.0][FIX] base_location: address field sync zip_id
  base_location/models/res_partner.py
  base_location/tests/test_base_location.py
Labels: approved, bot is merging ⏳

#1180 [13.0][FIX] base_location: address field sync zip_id
  base_location/models/res_partner.py
  base_location/tests/test_base_location.py
Labels: approved, bot is merging ⏳

#1157 [12.0][FIX] partner recursion check
  partner_company_group/models/res_partner.py
  partner_company_group/tests/__init__.py
  partner_company_group/tests/test_partner_company_group.py
Labels: bot is merging ⏳

#1181 [14.0][FIX] base_location: address field sync city_id
  base_location/models/res_partner.py
Labels: approved, bot is merging ⏳

#1182 [15.0][FIX] base_location: address field sync city_id
  base_location/models/res_partner.py
Labels: bot is merging ⏳

#1168 [15.0][MIG] base_country_state_translatable: Migration to 15.0
  base_country_state_translatable/README.rst
  base_country_state_translatable/__init__.py
  base_country_state_translatable/__manifest__.py
  base_country_state_translatable/i18n/base_country_state_translatable.pot
  base_country_state_translatable/i18n/da.po
  base_country_state_translatable/i18n/de.po
  base_country_state_translatable/i18n/es.po
  base_country_state_translatable/i18n/fr.po
  base_country_state_translatable/i18n/hr.po
  base_country_state_translatable/i18n/hr_HR.po
  base_country_state_translatable/i18n/it.po
  base_country_state_translatable/i18n/pt_BR.po
  base_country_state_translatable/i18n/sl.po
  base_country_state_translatable/models/__init__.py
  base_country_state_translatable/models/res_country.py
  base_country_state_translatable/readme/CONTRIBUTORS.rst
  base_country_state_translatable/readme/DESCRIPTION.rst
  base_country_state_translatable/readme/USAGE.rst
  base_country_state_translatable/static/description/icon.png
  base_country_state_translatable/static/description/index.html
  setup/base_country_state_translatable/odoo/addons/base_country_state_translatable
  setup/base_country_state_translatable/setup.py
Labels: approved, bot is merging ⏳

#1170 [15.0] Migration partner_fax
  partner_fax/README.rst
  partner_fax/__init__.py
  partner_fax/__manifest__.py
  partner_fax/i18n/de.po
  partner_fax/i18n/es.po
  partner_fax/i18n/fr.po
  partner_fax/i18n/he.po
  partner_fax/i18n/hr_HR.po
  partner_fax/i18n/it.po
  partner_fax/i18n/nl.po
  partner_fax/i18n/partner_fax.pot
  partner_fax/i18n/pt_BR.po
  partner_fax/i18n/sl.po
  partner_fax/i18n/zh_CN.po
  partner_fax/models/__init__.py
  partner_fax/models/res_partner.py
  partner_fax/readme/CONTRIBUTORS.rst
  partner_fax/readme/DESCRIPTION.rst
  partner_fax/readme/USAGE.rst
  partner_fax/static/description/icon.png
  partner_fax/static/description/index.html
  partner_fax/views/res_partner.xml
  setup/partner_fax/odoo/addons/partner_fax
  setup/partner_fax/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1124 [14.0][ADD] partner_identification_notification.
  partner_identification_notification/README.rst
  partner_identification_notification/__init__.py
  partner_identification_notification/__manifest__.py
  partner_identification_notification/data/ir_cron_data.xml
  partner_identification_notification/models/__init__.py
  partner_identification_notification/models/res_partner_id_category.py
  partner_identification_notification/models/res_partner_id_number.py
  partner_identification_notification/readme/CONTRIBUTORS.rst
  partner_identification_notification/readme/DESCRIPTION.rst
  partner_identification_notification/static/description/icon.png
  partner_identification_notification/static/description/index.html
  partner_identification_notification/views/res_partner_id_category_view.xml
  partner_identification_notification/views/res_partner_id_number_view.xml
  setup/partner_identification_notification/odoo/addons/partner_identification_notification
  setup/partner_identification_notification/setup.py
Labels: needs review, bot is merging ⏳
