Repository OCA/partner-contact, pull requests merged in 2021-06, with the labels that each got.

#1074 [14.0][MIG] animal
  README.md
  animal/README.rst
  animal/__init__.py
  animal/__manifest__.py
  animal/data/animal.breed.csv
  animal/data/animal.color.csv
  animal/data/animal.species.csv
  animal/data/ir.module.category.csv
  animal/i18n/animal.pot
  animal/i18n/es.po
  animal/models/__init__.py
  animal/models/animal.py
  animal/models/animal_breed.py
  animal/models/animal_color.py
  animal/models/animal_species.py
  animal/readme/CONTRIBUTORS.rst
  animal/readme/DESCRIPTION.rst
  animal/readme/USAGE.rst
  animal/security/ir.model.access.csv
  animal/security/res_groups.xml
  animal/static/description/icon.png
  animal/static/description/index.html
  animal/static/img/avatar.png
  animal/views/animal.xml
  animal/views/animal_breed.xml
  animal/views/animal_color.xml
  animal/views/animal_species.xml
  animal/views/menu.xml
  setup/animal/odoo/addons/animal
  setup/animal/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1115 [14.0][FIX] base_location_geonames_import : old_zip id may be removed more than once
  base_location_geonames_import/wizard/geonames_import.py
Labels: bot is merging ⏳

#1043 [MIG] partner_tz: Migration to 14.0
  partner_tz/README.rst
  partner_tz/__init__.py
  partner_tz/__manifest__.py
  partner_tz/i18n/partner_tz.pot
  partner_tz/readme/CONTRIBUTORS.rst
  partner_tz/readme/CREDITS.rst
  partner_tz/readme/DESCRIPTION.rst
  partner_tz/readme/ROADMAP.rst
  partner_tz/static/description/icon.png
  partner_tz/static/description/index.html
  partner_tz/tools/__init__.py
  partner_tz/tools/tz_utils.py
  partner_tz/views/res_partner.xml
  setup/partner_tz/odoo/addons/partner_tz
  setup/partner_tz/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#1116 [IMP] partner_contact_address_default ux
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
  partner_contact_address_default/views/res_partner_views.xml
Labels: approved, bot is merging ⏳
