Repository OCA/partner-contact, pull requests merged in 2022-08, with the labels that each got.

#1315 [14.0][IMP] partner_tz: dev status Alpha -> Beta
  partner_tz/__manifest__.py
Labels: needs review, bot is merging ⏳

#1241 [14.0][FIX] partner_vat_unique set application to false
  partner_vat_unique/__manifest__.py
Labels: bot is merging ⏳, stale

#1321 [13.0][DCK] Updated from template
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .travis.yml
  README.md
  base_location_nuts/__manifest__.py
  partner_address_two_lines/__manifest__.py
  partner_coc/__manifest__.py
  partner_contact_gender/__manifest__.py
  partner_contact_lang/__manifest__.py
  partner_deduplicate_by_ref/__manifest__.py
  partner_label/__manifest__.py
  partner_phone_extension/__manifest__.py
  partner_pricelist_tracking/__manifest__.py
  partner_ref_unique/__manifest__.py
  portal_partner_data_no_edit/__manifest__.py
  portal_partner_select_all/__manifest__.py
Labels: bot is merging ⏳

#1324 [15.0][MIG] partner_company_group: Migration to 15.0
  partner_company_group/README.rst
  partner_company_group/__init__.py
  partner_company_group/__manifest__.py
  partner_company_group/hooks.py
  partner_company_group/i18n/ca.po
  partner_company_group/i18n/es.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/i18n/zh_CN.po
  partner_company_group/models/__init__.py
  partner_company_group/models/account_move.py
  partner_company_group/models/crm_lead.py
  partner_company_group/models/res_partner.py
  partner_company_group/models/sale_order.py
  partner_company_group/readme/CONTRIBUTORS.rst
  partner_company_group/readme/DESCRIPTION.rst
  partner_company_group/static/description/icon.png
  partner_company_group/static/description/index.html
  partner_company_group/tests/__init__.py
  partner_company_group/tests/test_partner_company_group.py
  partner_company_group/views/account_move_views.xml
  partner_company_group/views/contact_view.xml
  partner_company_group/views/opportunity_view.xml
  partner_company_group/views/sale_order_view.xml
  setup/partner_company_group/odoo/addons/partner_company_group
  setup/partner_company_group/setup.py
Labels: approved, bot is merging ⏳

#1328 [14.0][ADD] partner_category_security: New addon.
  partner_category_security/README.rst
  partner_category_security/__init__.py
  partner_category_security/__manifest__.py
  partner_category_security/i18n/es.po
  partner_category_security/i18n/partner_category_security.pot
  partner_category_security/readme/CONTRIBUTORS.rst
  partner_category_security/readme/DESCRIPTION.rst
  partner_category_security/readme/USAGE.rst
  partner_category_security/security/ir.model.access.csv
  partner_category_security/security/security.xml
  partner_category_security/static/description/icon.png
  partner_category_security/static/description/index.html
  partner_category_security/tests/__init__.py
  partner_category_security/tests/test_partner_category_security.py
  partner_category_security/views/menu.xml
  partner_category_security/views/res_partner_view.xml
  setup/partner_category_security/odoo/addons/partner_category_security
  setup/partner_category_security/setup.py
Labels: approved, bot is merging ⏳

#1330 [14.0][ADD] partner_category_security_crm: New addon.
  partner_category_security_crm/README.rst
  partner_category_security_crm/__init__.py
  partner_category_security_crm/__manifest__.py
  partner_category_security_crm/i18n/es.po
  partner_category_security_crm/i18n/partner_category_security_crm.pot
  partner_category_security_crm/readme/CONTRIBUTORS.rst
  partner_category_security_crm/readme/DESCRIPTION.rst
  partner_category_security_crm/readme/USAGE.rst
  partner_category_security_crm/security/ir.model.access.csv
  partner_category_security_crm/static/description/icon.png
  partner_category_security_crm/static/description/index.html
  partner_category_security_crm/tests/__init__.py
  partner_category_security_crm/tests/test_partner_category_security_crm.py
  setup/partner_category_security_crm/odoo/addons/partner_category_security_crm
  setup/partner_category_security_crm/setup.py
Labels: approved, bot is merging ⏳

#1331 [14.0][FIX] partner_category_security: Allow to correctly edit tags when the user has permissions.
  partner_category_security/__init__.py
  partner_category_security/__manifest__.py
  partner_category_security/models/__init__.py
  partner_category_security/models/res_partner.py
  partner_category_security/security/ir.model.access.csv
  partner_category_security/tests/test_partner_category_security.py
  partner_category_security/views/res_partner_view.xml
Labels: approved, bot is merging ⏳
