Repository OCA/partner-contact, pull requests merged in 2022-04, with the labels that each got.

#1244 [15.0][ADD] base_partner_company_group
  base_partner_company_group/README.rst
  base_partner_company_group/__init__.py
  base_partner_company_group/__manifest__.py
  base_partner_company_group/i18n/es.po
  base_partner_company_group/i18n/partner_company_group.pot
  base_partner_company_group/i18n/zh_CN.po
  base_partner_company_group/models/__init__.py
  base_partner_company_group/models/res_partner.py
  base_partner_company_group/readme/CONTRIBUTORS.rst
  base_partner_company_group/readme/DESCRIPTION.rst
  base_partner_company_group/static/description/icon.png
  base_partner_company_group/static/description/index.html
  base_partner_company_group/tests/__init__.py
  base_partner_company_group/tests/test_base_partner_company_group.py
  base_partner_company_group/views/contact_view.xml
  setup/base_partner_company_group/odoo/addons/base_partner_company_group
  setup/base_partner_company_group/setup.py
Labels: approved, bot is merging ⏳

#865 [12.0][ADD] partner_multi_name module
  partner_multi_name/README.rst
  partner_multi_name/__init__.py
  partner_multi_name/__manifest__.py
  partner_multi_name/i18n/es CO.po
  partner_multi_name/i18n/es.po
  partner_multi_name/i18n/partner_other_names.pot
  partner_multi_name/models/__init__.py
  partner_multi_name/models/res_config_settings.py
  partner_multi_name/models/res_partner.py
  partner_multi_name/models/res_users.py
  partner_multi_name/static/description/icon.png
  partner_multi_name/tests/__init__.py
  partner_multi_name/tests/test_config.py
  partner_multi_name/tests/test_name.py
  partner_multi_name/tests/test_onchange.py
  partner_multi_name/views/res_partner_views.xml
  partner_multi_name/views/res_users_views.xml
Labels: approved, bot is merging ⏳

#1252 [13.0][IMP] partner_company_group: Add advises when company_group pricelist is different than member pricelists
  partner_company_group/i18n/es.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/models/res_partner.py
  partner_company_group/readme/CONTRIBUTORS.rst
  partner_company_group/tests/__init__.py
  partner_company_group/tests/test_partner_company_group.py
  partner_company_group/views/contact_view.xml
Labels: enhancement, approved, bot is merging ⏳

#1255 [13] FIX - partner_external_map fix view to better look Update res_partner_view.xml
  partner_external_map/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1261 [13.0][ADD] partner_pricelist_tracking: New module
  partner_pricelist_tracking/README.rst
  partner_pricelist_tracking/__init__.py
  partner_pricelist_tracking/__manifest__.py
  partner_pricelist_tracking/models/__init__.py
  partner_pricelist_tracking/models/res_partner.py
  partner_pricelist_tracking/readme/CONTRIBUTORS.rst
  partner_pricelist_tracking/readme/DESCRIPTION.rst
  partner_pricelist_tracking/readme/ROADMAP.rst
  partner_pricelist_tracking/static/description/index.html
  setup/partner_pricelist_tracking/odoo/addons/partner_pricelist_tracking
  setup/partner_pricelist_tracking/setup.py
Labels: approved, bot is merging ⏳

#1260 [12.0][IMP]partner_contact_address_default: removed field widget to allow filtering
  partner_contact_address_default/readme/CONTRIBUTORS.rst
  partner_contact_address_default/views/res_partner_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1257 [14.0][IMP] partner_company_group: Add warnings when company_group pricelist is different than member pricelists
  partner_company_group/i18n/es.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/models/res_partner.py
  partner_company_group/readme/CONTRIBUTORS.rst
  partner_company_group/tests/test_partner_company_group.py
  partner_company_group/views/contact_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1264 [13.0][FIX] partner_company_group: Terms not translated
  partner_company_group/models/res_partner.py
Labels: approved, bot is merging ⏳

#1266 [IMP] partner_tier_validation (Prevent bypass)
  partner_tier_validation/models/res_partner.py
Labels: bot is merging ⏳
