Repository OCA/partner-contact, pull requests merged in 2022-02, with the labels that each got.

#1196 [14.0] [MIG] partner contact birthplace
  partner_contact_birthplace/README.rst
  partner_contact_birthplace/__init__.py
  partner_contact_birthplace/__manifest__.py
  partner_contact_birthplace/i18n/it.po
  partner_contact_birthplace/i18n/partner_contact_birthplace.pot
  partner_contact_birthplace/models/__init__.py
  partner_contact_birthplace/models/res_partner.py
  partner_contact_birthplace/static/description/icon.png
  partner_contact_birthplace/views/res_partner.xml
  setup/partner_contact_birthplace/odoo/addons/partner_contact_birthplace
  setup/partner_contact_birthplace/setup.py
Labels: approved, bot is merging ⏳

#1215 [14.0][FIX] Fix access right issues when using actions
  animal_owner/models/res_partner.py
  partner_contact_in_several_companies/tests/test_partner_contact_in_several_companies.py
  partner_pricelist_search/models/product_pricelist.py
Labels: approved, bot is merging ⏳

#1221 [IMP] animal
  animal/models/animal_breed.py
  animal/models/animal_species.py
  animal/security/ir.model.access.csv
  animal/views/animal_breed.xml
  animal/views/animal_species.xml
  animal_owner/views/animal.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1185 [15.0][MIG] partner_contact_personal_information_page: Migration to 15.0
  partner_contact_personal_information_page/README.rst
  partner_contact_personal_information_page/__init__.py
  partner_contact_personal_information_page/__manifest__.py
  partner_contact_personal_information_page/i18n/da.po
  partner_contact_personal_information_page/i18n/de.po
  partner_contact_personal_information_page/i18n/en.po
  partner_contact_personal_information_page/i18n/es.po
  partner_contact_personal_information_page/i18n/fi.po
  partner_contact_personal_information_page/i18n/fr.po
  partner_contact_personal_information_page/i18n/hr_HR.po
  partner_contact_personal_information_page/i18n/hu.po
  partner_contact_personal_information_page/i18n/it.po
  partner_contact_personal_information_page/i18n/nl.po
  partner_contact_personal_information_page/i18n/partner_contact_personal_information_page.pot
  partner_contact_personal_information_page/i18n/pt.po
  partner_contact_personal_information_page/i18n/pt_BR.po
  partner_contact_personal_information_page/i18n/pt_PT.po
  partner_contact_personal_information_page/i18n/sl.po
  partner_contact_personal_information_page/readme/CONTRIBUTORS.rst
  partner_contact_personal_information_page/readme/DESCRIPTION.rst
  partner_contact_personal_information_page/readme/USAGE.rst
  partner_contact_personal_information_page/static/description/icon.png
  partner_contact_personal_information_page/static/description/index.html
  partner_contact_personal_information_page/views/res_partner.xml
  setup/partner_contact_personal_information_page/odoo/addons/partner_contact_personal_information_page
  setup/partner_contact_personal_information_page/setup.py
Labels: approved, bot is merging ⏳

#907 12.0 mig partner address version
  partner_address_version/README.rst
  partner_address_version/__init__.py
  partner_address_version/__manifest__.py
  partner_address_version/i18n/partner_address_version.pot
  partner_address_version/models/__init__.py
  partner_address_version/models/res_partner.py
  partner_address_version/readme/CONTRIBUTORS.rst
  partner_address_version/readme/DESCRIPTION.rst
  partner_address_version/static/description/icon.png
  partner_address_version/static/description/index.html
  partner_address_version/tests/__init__.py
  partner_address_version/tests/test_address_version.py
  partner_address_version/wizards/__init__.py
  partner_address_version/wizards/base_partner_merge.py
  setup/partner_address_version/odoo/addons/partner_address_version
  setup/partner_address_version/setup.py
Labels: bot is merging ⏳

#948 [12.0][IMP] partner_contact_address_default: allow selecting all partner
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/models/__init__.py
  partner_contact_address_default/models/res_config_settings.py
  partner_contact_address_default/security/res_groups_security.xml
  partner_contact_address_default/views/res_config_settings_views.xml
  partner_contact_address_default/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#1234 [FIX] [14.0] Removed external dependencies already defined in Odoo base
  partner_identification_gln/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#1238 partner_contact_address_default, error while updating module.
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#1229 [15.0][mig] partner_contact_age_range
  partner_contact_age_range/README.rst
  partner_contact_age_range/__init__.py
  partner_contact_age_range/__manifest__.py
  partner_contact_age_range/data/age_range_cron.xml
  partner_contact_age_range/i18n/partner_contact_age_range.pot
  partner_contact_age_range/models/__init__.py
  partner_contact_age_range/models/res_partner.py
  partner_contact_age_range/models/res_partner_age_range.py
  partner_contact_age_range/readme/CONTRIBUTORS.rst
  partner_contact_age_range/readme/DESCRIPTION.rst
  partner_contact_age_range/readme/USAGE.rst
  partner_contact_age_range/security/ir.model.access.csv
  partner_contact_age_range/static/description/age_range.png
  partner_contact_age_range/static/description/configure_age_range.png
  partner_contact_age_range/static/description/icon.png
  partner_contact_age_range/static/description/index.html
  partner_contact_age_range/tests/__init__.py
  partner_contact_age_range/tests/test_res_partner_age_range.py
  partner_contact_age_range/views/res_partner_age_range_view.xml
  partner_contact_age_range/views/res_partner_view.xml
  setup/partner_contact_age_range/odoo/addons/partner_contact_age_range
  setup/partner_contact_age_range/setup.py
Labels: needs review, approved, bot is merging ⏳
