Repository OCA/partner-contact, pull requests merged in 2022-07, with the labels that each got.

#1291 [15.0][MIG] partner_priority
  partner_priority/README.rst
  partner_priority/__init__.py
  partner_priority/__manifest__.py
  partner_priority/data/partner_priority_data.xml
  partner_priority/i18n/partner_priority.pot
  partner_priority/models/__init__.py
  partner_priority/models/partner_priority.py
  partner_priority/models/res_partner.py
  partner_priority/readme/CONTRIBUTORS.rst
  partner_priority/readme/DESCRIPTION.rst
  partner_priority/readme/USAGE.rst
  partner_priority/security/ir.model.access.csv
  partner_priority/static/description/icon.png
  partner_priority/static/description/index.html
  partner_priority/views/partner_priority.xml
  partner_priority/views/res_partner.xml
  setup/partner_priority/odoo/addons/partner_priority
  setup/partner_priority/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1235 [15.0] Migration of partner_vat_unique
  partner_vat_unique/README.rst
  partner_vat_unique/__init__.py
  partner_vat_unique/__manifest__.py
  partner_vat_unique/i18n/es.po
  partner_vat_unique/i18n/it.po
  partner_vat_unique/i18n/partner_vat_unique.pot
  partner_vat_unique/i18n/pt.po
  partner_vat_unique/models/__init__.py
  partner_vat_unique/models/res_partner.py
  partner_vat_unique/readme/CONTRIBUTORS.rst
  partner_vat_unique/readme/DESCRIPTION.rst
  partner_vat_unique/readme/INSTALL.rst
  partner_vat_unique/readme/ROADMAP.rst
  partner_vat_unique/static/description/icon.png
  partner_vat_unique/static/description/index.html
  partner_vat_unique/tests/__init__.py
  partner_vat_unique/tests/test_vat_unique.py
  setup/partner_vat_unique/odoo/addons/partner_vat_unique
  setup/partner_vat_unique/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1300 [15.0][MIG] partner_deduplicate_by_ref: Migration to 15.0
  partner_deduplicate_by_ref/README.rst
  partner_deduplicate_by_ref/__init__.py
  partner_deduplicate_by_ref/__manifest__.py
  partner_deduplicate_by_ref/i18n/ar.po
  partner_deduplicate_by_ref/i18n/bs.po
  partner_deduplicate_by_ref/i18n/cs.po
  partner_deduplicate_by_ref/i18n/de.po
  partner_deduplicate_by_ref/i18n/en_GB.po
  partner_deduplicate_by_ref/i18n/es.po
  partner_deduplicate_by_ref/i18n/es_CR.po
  partner_deduplicate_by_ref/i18n/es_EC.po
  partner_deduplicate_by_ref/i18n/es_MX.po
  partner_deduplicate_by_ref/i18n/et.po
  partner_deduplicate_by_ref/i18n/fr.po
  partner_deduplicate_by_ref/i18n/gl.po
  partner_deduplicate_by_ref/i18n/hr.po
  partner_deduplicate_by_ref/i18n/hu.po
  partner_deduplicate_by_ref/i18n/it.po
  partner_deduplicate_by_ref/i18n/ja.po
  partner_deduplicate_by_ref/i18n/lt.po
  partner_deduplicate_by_ref/i18n/lv.po
  partner_deduplicate_by_ref/i18n/mk.po
  partner_deduplicate_by_ref/i18n/mn.po
  partner_deduplicate_by_ref/i18n/nb.po
  partner_deduplicate_by_ref/i18n/nl.po
  partner_deduplicate_by_ref/i18n/nl_BE.po
  partner_deduplicate_by_ref/i18n/nl_NL.po
  partner_deduplicate_by_ref/i18n/partner_deduplicate_by_ref.pot
  partner_deduplicate_by_ref/i18n/pt.po
  partner_deduplicate_by_ref/i18n/pt_BR.po
  partner_deduplicate_by_ref/i18n/pt_PT.po
  partner_deduplicate_by_ref/i18n/ro.po
  partner_deduplicate_by_ref/i18n/ru.po
  partner_deduplicate_by_ref/i18n/sk.po
  partner_deduplicate_by_ref/i18n/sl.po
  partner_deduplicate_by_ref/i18n/sv.po
  partner_deduplicate_by_ref/i18n/th.po
  partner_deduplicate_by_ref/i18n/tr.po
  partner_deduplicate_by_ref/i18n/zh_CN.po
  partner_deduplicate_by_ref/i18n/zh_TW.po
  partner_deduplicate_by_ref/readme/CONTRIBUTORS.rst
  partner_deduplicate_by_ref/readme/DESCRIPTION.rst
  partner_deduplicate_by_ref/readme/USAGE.rst
  partner_deduplicate_by_ref/static/description/icon.png
  partner_deduplicate_by_ref/static/description/icon.svg
  partner_deduplicate_by_ref/static/description/index.html
  partner_deduplicate_by_ref/tests/__init__.py
  partner_deduplicate_by_ref/tests/test_partner_deduplicate_by_ref.py
  partner_deduplicate_by_ref/wizards/__init__.py
  partner_deduplicate_by_ref/wizards/partner_merge.py
  partner_deduplicate_by_ref/wizards/partner_merge_view.xml
  setup/partner_deduplicate_by_ref/odoo/addons/partner_deduplicate_by_ref
  setup/partner_deduplicate_by_ref/setup.py
Labels: approved, bot is merging ⏳

#1152 [14.0][MIG] partner_data_vies_populator
  partner_data_vies_populator/README.rst
  partner_data_vies_populator/__init__.py
  partner_data_vies_populator/__manifest__.py
  partner_data_vies_populator/i18n/partner_data_vies_populator.pot
  partner_data_vies_populator/models/__init__.py
  partner_data_vies_populator/models/res_partner.py
  partner_data_vies_populator/readme/CONTRIBUTORS.rst
  partner_data_vies_populator/readme/DESCRIPTION.rst
  partner_data_vies_populator/readme/INSTALL.rst
  partner_data_vies_populator/readme/USAGE.rst
  partner_data_vies_populator/static/description/icon.png
  partner_data_vies_populator/static/description/index.html
  partner_data_vies_populator/tests/__init__.py
  partner_data_vies_populator/tests/test_partner_data_vies_populator.py
  requirements.txt
  setup/partner_data_vies_populator/odoo/addons/partner_data_vies_populator
  setup/partner_data_vies_populator/setup.py
Labels: needs review, approved, bot is merging ⏳

#1288 [15.0][MIG] partner_contact_address_default
  partner_contact_address_default/README.rst
  partner_contact_address_default/__init__.py
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/i18n/es.po
  partner_contact_address_default/i18n/fr.po
  partner_contact_address_default/i18n/fr_FR.po
  partner_contact_address_default/i18n/partner_contact_address_default.pot
  partner_contact_address_default/i18n/pt.po
  partner_contact_address_default/models/__init__.py
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/readme/CONTRIBUTORS.rst
  partner_contact_address_default/readme/DESCRIPTION.rst
  partner_contact_address_default/readme/USAGE.rst
  partner_contact_address_default/static/description/icon.png
  partner_contact_address_default/static/description/index.html
  partner_contact_address_default/tests/__init__.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
  partner_contact_address_default/views/res_partner_views.xml
  setup/partner_contact_address_default/odoo/addons/partner_contact_address_default
  setup/partner_contact_address_default/setup.py
Labels: bot is merging ⏳
