Repository OCA/partner-contact, pull requests merged in 2022-11, with the labels that each got.

#1390 [16.0][MIG] partner_contact_access_link: Migration to 16.0
  partner_contact_access_link/README.rst
  partner_contact_access_link/__init__.py
  partner_contact_access_link/__manifest__.py
  partner_contact_access_link/i18n/ca.po
  partner_contact_access_link/i18n/partner_contact_access_link.pot
  partner_contact_access_link/models/__init__.py
  partner_contact_access_link/models/res_partner.py
  partner_contact_access_link/readme/CONTRIBUTORS.rst
  partner_contact_access_link/readme/DESCRIPTION.rst
  partner_contact_access_link/readme/USAGE.rst
  partner_contact_access_link/static/description/full-form.gif
  partner_contact_access_link/static/description/icon.png
  partner_contact_access_link/static/description/index.html
  partner_contact_access_link/tests/__init__.py
  partner_contact_access_link/tests/test_partner_contact_access_link.py
  partner_contact_access_link/views/res_partner_views.xml
  setup/partner_contact_access_link/odoo/addons/partner_contact_access_link
  setup/partner_contact_access_link/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1394 [FIX] pre-commit py-lint error
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  animal/data/ir.module.category.csv
  animal/security/res_groups.xml
  animal/views/menu.xml
Labels: bot is merging ⏳

#1393 [15.0][MIG] portal_partner_data_no_edit: Migration to 15.0
  portal_partner_data_no_edit/README.rst
  portal_partner_data_no_edit/__init__.py
  portal_partner_data_no_edit/__manifest__.py
  portal_partner_data_no_edit/controllers/__init__.py
  portal_partner_data_no_edit/controllers/portal.py
  portal_partner_data_no_edit/i18n/es.po
  portal_partner_data_no_edit/i18n/portal_partner_data_no_edit.pot
  portal_partner_data_no_edit/models/__init__.py
  portal_partner_data_no_edit/models/ir_ui_view.py
  portal_partner_data_no_edit/models/res_partner.py
  portal_partner_data_no_edit/readme/CONFIGURE.rst
  portal_partner_data_no_edit/readme/CONTRIBUTORS.rst
  portal_partner_data_no_edit/readme/DESCRIPTION.rst
  portal_partner_data_no_edit/readme/ROADMAP.rst
  portal_partner_data_no_edit/readme/USAGE.rst
  portal_partner_data_no_edit/static/description/icon.png
  portal_partner_data_no_edit/static/description/index.html
  portal_partner_data_no_edit/static/src/js/portal_partner_data_no_edit_tour.js
  portal_partner_data_no_edit/tests/__init__.py
  portal_partner_data_no_edit/tests/test_portal_partner_data_no_edit.py
  portal_partner_data_no_edit/views/portal_template.xml
  portal_partner_data_no_edit/views/res_partner_views.xml
  setup/portal_partner_data_no_edit/odoo/addons/portal_partner_data_no_edit
  setup/portal_partner_data_no_edit/setup.py
Labels: approved, bot is merging ⏳

#1401 [14.0] Update from copier template
  .copier-answers.yml
  .pre-commit-config.yaml
  README.md
  animal/data/ir.module.category.csv
  animal/security/res_groups.xml
  animal/views/menu.xml
Labels: needs review, approved, bot is merging ⏳

#1400 [14.0] [FIX] category in manifest files
  base_country_state_translatable/__manifest__.py
  base_location_nuts/__manifest__.py
Labels: approved, bot is merging ⏳

#1349 [15.0][MIG] partner_contact_role: Migrate to version 15.0
  .pre-commit-config.yaml
  partner_contact_role/README.rst
  partner_contact_role/__init__.py
  partner_contact_role/__manifest__.py
  partner_contact_role/i18n/partner_contact_role.pot
  partner_contact_role/models/__init__.py
  partner_contact_role/models/res_partner.py
  partner_contact_role/readme/CONFIGURE.rst
  partner_contact_role/readme/CONTRIBUTORS.rst
  partner_contact_role/readme/CREDITS.rst
  partner_contact_role/readme/DESCRIPTION.rst
  partner_contact_role/readme/USAGE.rst
  partner_contact_role/security/ir.model.access.csv
  partner_contact_role/static/description/icon.png
  partner_contact_role/views/res_partner.xml
  partner_contact_role/views/res_partner_role.xml
  setup/partner_contact_role/odoo/addons/partner_contact_role
  setup/partner_contact_role/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#1396 [ADD] res_partner_journal_items_link: black, isort
  res_partner_journal_items_link/README.rst
  res_partner_journal_items_link/__manifest__.py
  res_partner_journal_items_link/i18n/es.po
  res_partner_journal_items_link/i18n/res_partner_journal_items_link.pot
  res_partner_journal_items_link/readme/CONTRIBUTORS.rst
  res_partner_journal_items_link/readme/DESCRIPTION.rst
  res_partner_journal_items_link/static/description/icon.png
  res_partner_journal_items_link/static/description/index.html
  res_partner_journal_items_link/views/account_move_line.xml
  res_partner_journal_items_link/views/res_partner_view.xml
  setup/res_partner_journal_items_link/odoo/addons/res_partner_journal_items_link
  setup/res_partner_journal_items_link/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1403 [12.0] Switch to GH actions
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  base_location_nuts/__manifest__.py
  partner_address_two_lines/__manifest__.py
  partner_address_version/models/__init__.py
  partner_address_version/tests/__init__.py
  partner_address_version/wizards/base_partner_merge.py
  partner_coc/__manifest__.py
  partner_contact_birthplace/__manifest__.py
  partner_contact_gender/__manifest__.py
  partner_contact_lang/__manifest__.py
  partner_contact_nationality/__manifest__.py
  partner_deduplicate_by_ref/__manifest__.py
  partner_deduplicate_by_website/__manifest__.py
  partner_firstname/__manifest__.py
  partner_helper/__manifest__.py
  partner_label/__manifest__.py
  partner_multi_name/__init__.py
  partner_multi_name/__manifest__.py
  partner_multi_name/models/__init__.py
  partner_multi_name/models/res_config_settings.py
  partner_multi_name/models/res_partner.py
  partner_multi_name/models/res_users.py
  partner_multi_relation/i18n/es_AR.po
  partner_multi_relation/i18n/it.po
  partner_multi_relation/models/res_partner_relation_all.py
  partner_multi_relation/views/res_partner_relation_all.xml
  partner_multi_relation_tabs/__manifest__.py
  partner_phone_extension/__manifest__.py
  partner_ref_unique/__manifest__.py
  portal_partner_data_no_edit/__manifest__.py
  portal_partner_select_all/__manifest__.py
  requirements.txt
Labels: needs review

#1410 [16] Update from copier template in order to fix pre-commit
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: approved
