Repository OCA/partner-contact, pull requests merged in 2022-01, with the labels that each got.

#1203 [14.0][FIX] animal_owner: Fix tracking parameter
  animal_owner/models/animal.py
Labels: approved, ready to merge, bot is merging ⏳

#979 [12.0] partner multi relation improvements
  oca_dependencies.txt
  partner_multi_relation/__init__.py
  partner_multi_relation/__manifest__.py
  partner_multi_relation/data/demo.xml
  partner_multi_relation/demo/res_partner_category_demo.xml
  partner_multi_relation/demo/res_partner_demo.xml
  partner_multi_relation/demo/res_partner_relation_demo.xml
  partner_multi_relation/demo/res_partner_relation_type_demo.xml
  partner_multi_relation/models/__init__.py
  partner_multi_relation/models/res_partner.py
  partner_multi_relation/models/res_partner_relation.py
  partner_multi_relation/models/res_partner_relation_all.py
  partner_multi_relation/models/res_partner_relation_type.py
  partner_multi_relation/models/res_partner_relation_type_selection.py
  partner_multi_relation/security/ir.model.access.csv
  partner_multi_relation/tests/__init__.py
  partner_multi_relation/tests/common.py
  partner_multi_relation/tests/test_partner_action.py
  partner_multi_relation/tests/test_partner_relation.py
  partner_multi_relation/tests/test_partner_relation_all.py
  partner_multi_relation/tests/test_partner_relation_common.py
  partner_multi_relation/tests/test_partner_search.py
  partner_multi_relation/views/menu.xml
  partner_multi_relation/views/res_partner.xml
  partner_multi_relation/views/res_partner_relation.xml
  partner_multi_relation/views/res_partner_relation_all.xml
  partner_multi_relation/views/res_partner_relation_type.xml
  partner_multi_relation_tabs/__manifest__.py
  partner_multi_relation_tabs/models/__init__.py
  partner_multi_relation_tabs/models/res_partner.py
  partner_multi_relation_tabs/models/res_partner_relation_all.py
  partner_multi_relation_tabs/models/res_partner_relation_type.py
  partner_multi_relation_tabs/models/res_partner_relation_type_selection.py
  partner_multi_relation_tabs/models/res_partner_tab.py
  partner_multi_relation_tabs/models/res_partner_tab_sequence.py
  partner_multi_relation_tabs/tablib/tab.py
  partner_multi_relation_tabs/tests/__init__.py
  partner_multi_relation_tabs/tests/common.py
  partner_multi_relation_tabs/tests/test_partner_tabs.py
  partner_multi_relation_tabs/tests/test_partner_view_actions.py
  partner_multi_relation_tabs/tests/test_tab.py
  partner_multi_relation_tabs/views/menu.xml
  partner_multi_relation_tabs/views/res_partner_relation_type.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1208 [15.0][MIG] partner_contact_access_link
  partner_contact_access_link/README.rst
  partner_contact_access_link/__init__.py
  partner_contact_access_link/__manifest__.py
  partner_contact_access_link/i18n/partner_contact_access_link.pot
  partner_contact_access_link/models/__init__.py
  partner_contact_access_link/models/res_partner.py
  partner_contact_access_link/readme/CONTRIBUTORS.rst
  partner_contact_access_link/readme/DESCRIPTION.rst
  partner_contact_access_link/readme/USAGE.rst
  partner_contact_access_link/static/description/full-form.gif
  partner_contact_access_link/static/description/icon.png
  partner_contact_access_link/static/description/index.html
  partner_contact_access_link/tests/__init__.py
  partner_contact_access_link/tests/test_partner_contact_access_link.py
  partner_contact_access_link/views/res_partner_views.xml
  setup/partner_contact_access_link/odoo/addons/partner_contact_access_link
  setup/partner_contact_access_link/setup.py
Labels: approved, bot is merging ⏳
