Repository OCA/partner-contact, pull requests merged in 2022-10, with the labels that each got.

#1311 [13.0][MIG] partner_stage: Backport from 14.0
  partner_stage/README.rst
  partner_stage/__init__.py
  partner_stage/__manifest__.py
  partner_stage/data/partner_stage_data.xml
  partner_stage/i18n/partner_stage.pot
  partner_stage/init_hook.py
  partner_stage/migrations/14.0.2.0.0/post-migration.py
  partner_stage/migrations/14.0.2.0.0/pre-migrate.py
  partner_stage/models/__init__.py
  partner_stage/models/res_partner.py
  partner_stage/models/res_partner_stage.py
  partner_stage/readme/CONFIGURATION.rst
  partner_stage/readme/CONTRIBUTORS.rst
  partner_stage/readme/DESCRIPTION.rst
  partner_stage/readme/USAGE.rst
  partner_stage/security/ir.model.access.csv
  partner_stage/static/description/icon.png
  partner_stage/static/description/index.html
  partner_stage/tests/__init__.py
  partner_stage/tests/test_partner_stage.py
  partner_stage/views/res_partner_stage_views.xml
  partner_stage/views/res_partner_views.xml
  setup/partner_stage/odoo/addons/partner_stage
  setup/partner_stage/setup.py
Labels: approved, bot is merging ⏳

#1287 [ADD] search method for partner age
  partner_contact_birthdate/models/res_partner.py
  partner_contact_birthdate/tests/test_res_partner.py
Labels: approved, ready to merge, bot is merging ⏳

#1351 [13.0][FIX] partner_pricelist_search: speedup search
  partner_pricelist_search/models/res_partner.py
  partner_pricelist_search/tests/test_partner_pricelist_search.py
Labels: approved, bot is merging ⏳

#1377 [16.0] [MIG] partner_contact_personal_information_page
  partner_contact_personal_information_page/README.rst
  partner_contact_personal_information_page/__init__.py
  partner_contact_personal_information_page/__manifest__.py
  partner_contact_personal_information_page/i18n/ca.po
  partner_contact_personal_information_page/i18n/da.po
  partner_contact_personal_information_page/i18n/de.po
  partner_contact_personal_information_page/i18n/en.po
  partner_contact_personal_information_page/i18n/es.po
  partner_contact_personal_information_page/i18n/fi.po
  partner_contact_personal_information_page/i18n/fr.po
  partner_contact_personal_information_page/i18n/hr_HR.po
  partner_contact_personal_information_page/i18n/hu.po
  partner_contact_personal_information_page/i18n/it.po
  partner_contact_personal_information_page/i18n/nl.po
  partner_contact_personal_information_page/i18n/partner_contact_personal_information_page.pot
  partner_contact_personal_information_page/i18n/pt.po
  partner_contact_personal_information_page/i18n/pt_BR.po
  partner_contact_personal_information_page/i18n/pt_PT.po
  partner_contact_personal_information_page/i18n/sl.po
  partner_contact_personal_information_page/readme/CONTRIBUTORS.rst
  partner_contact_personal_information_page/readme/DESCRIPTION.rst
  partner_contact_personal_information_page/readme/USAGE.rst
  partner_contact_personal_information_page/static/description/icon.png
  partner_contact_personal_information_page/static/description/index.html
  partner_contact_personal_information_page/views/res_partner.xml
  setup/partner_contact_personal_information_page/odoo/addons/partner_contact_personal_information_page
  setup/partner_contact_personal_information_page/setup.py
Labels: approved, bot is merging ⏳

#1245 [ADD] crm_partner_company_group
  crm_partner_company_group/README.rst
  crm_partner_company_group/__init__.py
  crm_partner_company_group/__manifest__.py
  crm_partner_company_group/hooks.py
  crm_partner_company_group/i18n/es.po
  crm_partner_company_group/i18n/partner_company_group.pot
  crm_partner_company_group/i18n/zh_CN.po
  crm_partner_company_group/models/__init__.py
  crm_partner_company_group/models/crm_lead.py
  crm_partner_company_group/readme/CONTRIBUTORS.rst
  crm_partner_company_group/readme/DESCRIPTION.rst
  crm_partner_company_group/static/description/icon.png
  crm_partner_company_group/static/description/index.html
  crm_partner_company_group/views/opportunity_view.xml
  setup/crm_partner_company_group/odoo/addons/crm_partner_company_group
  setup/crm_partner_company_group/setup.py
Labels: approved, bot is merging ⏳

#1247 [ADD] sale_partner_company_group
  sale_partner_company_group/README.rst
  sale_partner_company_group/__init__.py
  sale_partner_company_group/__manifest__.py
  sale_partner_company_group/hooks.py
  sale_partner_company_group/i18n/es.po
  sale_partner_company_group/i18n/partner_company_group.pot
  sale_partner_company_group/i18n/zh_CN.po
  sale_partner_company_group/models/__init__.py
  sale_partner_company_group/models/res_partner.py
  sale_partner_company_group/models/sale_order.py
  sale_partner_company_group/readme/CONTRIBUTORS.rst
  sale_partner_company_group/readme/DESCRIPTION.rst
  sale_partner_company_group/static/description/icon.png
  sale_partner_company_group/static/description/index.html
  sale_partner_company_group/tests/__init__.py
  sale_partner_company_group/tests/test_sale_partner_company_group.py
  sale_partner_company_group/views/sale_order_view.xml
  setup/sale_partner_company_group/odoo/addons/sale_partner_company_group
  setup/sale_partner_company_group/setup.py
Labels: approved, bot is merging ⏳

#1246 [ADD] account_partner_company_group
  account_partner_company_group/README.rst
  account_partner_company_group/__init__.py
  account_partner_company_group/__manifest__.py
  account_partner_company_group/hooks.py
  account_partner_company_group/i18n/es.po
  account_partner_company_group/i18n/partner_company_group.pot
  account_partner_company_group/i18n/zh_CN.po
  account_partner_company_group/models/__init__.py
  account_partner_company_group/models/account_move.py
  account_partner_company_group/readme/CONTRIBUTORS.rst
  account_partner_company_group/readme/DESCRIPTION.rst
  account_partner_company_group/static/description/icon.png
  account_partner_company_group/static/description/index.html
  account_partner_company_group/views/account_move_views.xml
  setup/account_partner_company_group/odoo/addons/account_partner_company_group
  setup/account_partner_company_group/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1302 Updated typos in readme
  animal/README.rst
Labels: bot is merging ⏳

#1268 [15.0][FIX] partner_firstname: Bug in required conditions for contacts
  partner_firstname/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#1383 [13.0][FIX] partner_pricelist_search: Remove list type also from search arguments
  partner_pricelist_search/models/res_partner.py
Labels: approved, bot is merging ⏳

#1384 [14.0][FIX] partner_pricelist_search: speedup search + Remove list type also from search arguments
  partner_pricelist_search/models/res_partner.py
  partner_pricelist_search/tests/test_partner_pricelist_search.py
Labels: approved, bot is merging ⏳

#1347 [FIX] partner_company_group: module was splitted, this allows safe remove
  partner_company_group/README.rst
  partner_company_group/__init__.py
  partner_company_group/__manifest__.py
  partner_company_group/hooks.py
  partner_company_group/models/__init__.py
  partner_company_group/models/account_move.py
  partner_company_group/models/crm_lead.py
  partner_company_group/models/res_partner.py
  partner_company_group/models/sale_order.py
  partner_company_group/tests/__init__.py
  partner_company_group/tests/test_partner_company_group.py
  partner_company_group/views/account_move_views.xml
  partner_company_group/views/contact_view.xml
  partner_company_group/views/opportunity_view.xml
  partner_company_group/views/sale_order_view.xml
Labels: bot is merging ⏳

#1350 [15.0][MIG] partner_pricelist_search: Migration to 15.0
  partner_pricelist_search/README.rst
  partner_pricelist_search/__init__.py
  partner_pricelist_search/__manifest__.py
  partner_pricelist_search/i18n/es.po
  partner_pricelist_search/i18n/partner_pricelist_search.pot
  partner_pricelist_search/models/__init__.py
  partner_pricelist_search/models/product_pricelist.py
  partner_pricelist_search/models/res_partner.py
  partner_pricelist_search/readme/CONTRIBUTORS.rst
  partner_pricelist_search/readme/DESCRIPTION.rst
  partner_pricelist_search/readme/ROADMAP.rst
  partner_pricelist_search/static/description/icon.png
  partner_pricelist_search/static/description/index.html
  partner_pricelist_search/tests/__init__.py
  partner_pricelist_search/tests/test_partner_pricelist_search.py
  partner_pricelist_search/views/product_pricelist_views.xml
  setup/partner_pricelist_search/odoo/addons/partner_pricelist_search
  setup/partner_pricelist_search/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1354 [ADD][14.0] partner_mobile_unique
  partner_mobile_unique/README.rst
  partner_mobile_unique/__init__.py
  partner_mobile_unique/__manifest__.py
  partner_mobile_unique/models/__init__.py
  partner_mobile_unique/models/res_company.py
  partner_mobile_unique/models/res_config_settings.py
  partner_mobile_unique/models/res_partner.py
  partner_mobile_unique/readme/CONFIGURE.rst
  partner_mobile_unique/readme/CONTRIBUTORS.rst
  partner_mobile_unique/readme/DESCRIPTION.rst
  partner_mobile_unique/readme/USAGE.rst
  partner_mobile_unique/static/description/icon.png
  partner_mobile_unique/static/description/partner_duplicate_error.png
  partner_mobile_unique/tests/__init__.py
  partner_mobile_unique/tests/test_mobile_check_unique.py
  partner_mobile_unique/views/res_config_settings_view.xml
  setup/partner_mobile_unique/odoo/addons/partner_mobile_unique
  setup/partner_mobile_unique/setup.py
Labels: approved, bot is merging ⏳

#1359 [16][MIG] partner vat unique
  partner_vat_unique/README.rst
  partner_vat_unique/__init__.py
  partner_vat_unique/__manifest__.py
  partner_vat_unique/i18n/es.po
  partner_vat_unique/i18n/it.po
  partner_vat_unique/i18n/partner_vat_unique.pot
  partner_vat_unique/i18n/pt.po
  partner_vat_unique/models/__init__.py
  partner_vat_unique/models/res_partner.py
  partner_vat_unique/readme/CONTRIBUTORS.rst
  partner_vat_unique/readme/DESCRIPTION.rst
  partner_vat_unique/readme/INSTALL.rst
  partner_vat_unique/readme/ROADMAP.rst
  partner_vat_unique/static/description/icon.png
  partner_vat_unique/static/description/index.html
  partner_vat_unique/tests/__init__.py
  partner_vat_unique/tests/test_vat_unique.py
  setup/partner_vat_unique/odoo/addons/partner_vat_unique
  setup/partner_vat_unique/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1388 [16.0][MIG] partner_disable_gravatar
  partner_disable_gravatar/README.rst
  partner_disable_gravatar/__init__.py
  partner_disable_gravatar/__manifest__.py
  partner_disable_gravatar/i18n/it.po
  partner_disable_gravatar/i18n/partner_disable_gravatar.pot
  partner_disable_gravatar/models/__init__.py
  partner_disable_gravatar/models/res_partner.py
  partner_disable_gravatar/readme/CONTRIBUTORS.rst
  partner_disable_gravatar/readme/DESCRIPTION.rst
  partner_disable_gravatar/static/description/icon.png
  partner_disable_gravatar/static/description/index.html
  partner_disable_gravatar/tests/__init__.py
  partner_disable_gravatar/tests/test_partner_disable_gravatar.py
  setup/partner_disable_gravatar/odoo/addons/partner_disable_gravatar
  setup/partner_disable_gravatar/setup.py
Labels: approved, bot is merging ⏳
