Repository OCA/partner-contact, pull requests merged in 2022-12, with the labels that each got.

#1365 [MIG] partner_bank_code: Migration to 15.0
  partner_bank_code/README.rst
  partner_bank_code/__init__.py
  partner_bank_code/__manifest__.py
  partner_bank_code/i18n/fr.po
  partner_bank_code/i18n/hr.po
  partner_bank_code/i18n/partner_bank_code.pot
  partner_bank_code/models/__init__.py
  partner_bank_code/models/res_bank.py
  partner_bank_code/readme/CONTRIBUTORS.rst
  partner_bank_code/readme/DESCRIPTION.rst
  partner_bank_code/readme/USAGE.rst
  partner_bank_code/static/description/icon.png
  partner_bank_code/static/description/index.html
  partner_bank_code/views/res_bank.xml
  setup/partner_bank_code/odoo/addons/partner_bank_code
  setup/partner_bank_code/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1407 [ADD][14.0] partner_create_format_phone: initial commit
  partner_create_format_phone/README.rst
  partner_create_format_phone/__init__.py
  partner_create_format_phone/__manifest__.py
  partner_create_format_phone/models/__init__.py
  partner_create_format_phone/models/res_partner.py
  partner_create_format_phone/readme/CONTRIBUTORS.rst
  partner_create_format_phone/readme/DESCRIPTION.rst
  setup/partner_create_format_phone/odoo/addons/partner_create_format_phone
  setup/partner_create_format_phone/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1335 [Fix] Opening Deduplicate Contacts when clicking on main Contacts men…
  partner_deduplicate_acl/README.rst
  partner_deduplicate_acl/readme/USAGE.rst
  partner_deduplicate_acl/views/base_partner_merge_view.xml
Labels: bot is merging ⏳

#1299 [15.0][MIG] partner_deduplicate_filter: Migration to 15.0
  partner_deduplicate_filter/README.rst
  partner_deduplicate_filter/__init__.py
  partner_deduplicate_filter/__manifest__.py
  partner_deduplicate_filter/i18n/crm_deduplicate_filter.pot
  partner_deduplicate_filter/i18n/de.po
  partner_deduplicate_filter/i18n/es.po
  partner_deduplicate_filter/i18n/hr.po
  partner_deduplicate_filter/i18n/nl_NL.po
  partner_deduplicate_filter/i18n/partner_deduplicate_filter.pot
  partner_deduplicate_filter/i18n/sk.po
  partner_deduplicate_filter/i18n/sl.po
  partner_deduplicate_filter/i18n/tr.po
  partner_deduplicate_filter/readme/CONTRIBUTORS.rst
  partner_deduplicate_filter/readme/DESCRIPTION.rst
  partner_deduplicate_filter/readme/USAGE.rst
  partner_deduplicate_filter/static/description/icon.png
  partner_deduplicate_filter/static/description/icon.svg
  partner_deduplicate_filter/static/description/index.html
  partner_deduplicate_filter/tests/__init__.py
  partner_deduplicate_filter/tests/test_partner_deduplicate_filter.py
  partner_deduplicate_filter/wizards/__init__.py
  partner_deduplicate_filter/wizards/partner_merge.py
  partner_deduplicate_filter/wizards/partner_merge_view.xml
  setup/partner_deduplicate_filter/odoo/addons/partner_deduplicate_filter
  setup/partner_deduplicate_filter/setup.py
Labels: approved, bot is merging ⏳, stale

#1409 [14.0] [ADD] `partner_duns`
  partner_duns/README.rst
  partner_duns/__init__.py
  partner_duns/__manifest__.py
  partner_duns/models/__init__.py
  partner_duns/models/res_partner.py
  partner_duns/readme/CONTRIBUTORS.rst
  partner_duns/readme/DESCRIPTION.rst
  partner_duns/tests/__init__.py
  partner_duns/tests/test_partner_duns.py
  partner_duns/views/res_partner.xml
  setup/partner_duns/odoo/addons/partner_duns
  setup/partner_duns/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1411 16.0 [MIG] base_country_state_translatable: Migration to 16.0
  base_country_state_translatable/README.rst
  base_country_state_translatable/__init__.py
  base_country_state_translatable/__manifest__.py
  base_country_state_translatable/i18n/base_country_state_translatable.pot
  base_country_state_translatable/i18n/ca.po
  base_country_state_translatable/i18n/da.po
  base_country_state_translatable/i18n/de.po
  base_country_state_translatable/i18n/es.po
  base_country_state_translatable/i18n/fr.po
  base_country_state_translatable/i18n/hr.po
  base_country_state_translatable/i18n/hr_HR.po
  base_country_state_translatable/i18n/it.po
  base_country_state_translatable/i18n/pt_BR.po
  base_country_state_translatable/i18n/sl.po
  base_country_state_translatable/models/__init__.py
  base_country_state_translatable/models/res_country.py
  base_country_state_translatable/readme/CONTRIBUTORS.rst
  base_country_state_translatable/readme/DESCRIPTION.rst
  base_country_state_translatable/readme/USAGE.rst
  base_country_state_translatable/static/description/icon.png
  base_country_state_translatable/static/description/index.html
  setup/base_country_state_translatable/odoo/addons/base_country_state_translatable
  setup/base_country_state_translatable/setup.py
Labels: needs review, approved, migration, ready to merge

#1426 16.0 [ADD] partner_accreditation
  partner_accreditation/README.rst
  partner_accreditation/__init__.py
  partner_accreditation/__manifest__.py
  partner_accreditation/models/__init__.py
  partner_accreditation/models/res_partner.py
  partner_accreditation/models/res_partner_accreditation.py
  partner_accreditation/readme/CONTRIBUTORS.rst
  partner_accreditation/readme/DESCRIPTION.rst
  partner_accreditation/security/ir.model.access.csv
  partner_accreditation/static/description/index.html
  partner_accreditation/views/res_partner_accreditation_view.xml
  partner_accreditation/views/res_partner_view.xml
  setup/partner_accreditation/odoo/addons/partner_accreditation
  setup/partner_accreditation/setup.py
Labels: approved, ready to merge, bot is merging ⏳
