Repository OCA/partner-contact, pull requests merged in 2023-05, with the labels that each got.

#1514 [15.0][FIX] partner_phonecall_schedule: Change SavepointCase to TransactionCase
  partner_phonecall_schedule/tests/test_schedule.py
Labels: bot is merging ⏳

#1188 [14.0][MIG]sale_customer_rank: Migration to 14.0
  sale_customer_rank/README.rst
  sale_customer_rank/__init__.py
  sale_customer_rank/__manifest__.py
  sale_customer_rank/i18n/sale_customer_rank.pot
  sale_customer_rank/models/__init__.py
  sale_customer_rank/models/sale_order.py
  sale_customer_rank/readme/CONTRIBUTORS.rst
  sale_customer_rank/readme/DESCRIPTION.rst
  sale_customer_rank/static/description/icon.png
  sale_customer_rank/static/description/index.html
  sale_customer_rank/tests/__init__.py
  sale_customer_rank/tests/test_sale_customer_rank.py
  setup/sale_customer_rank/odoo/addons/sale_customer_rank
  setup/sale_customer_rank/setup.py
Labels: approved, bot is merging ⏳

#1504 [16.0][MIG] base_partner_company_group
  base_partner_company_group/README.rst
  base_partner_company_group/__init__.py
  base_partner_company_group/__manifest__.py
  base_partner_company_group/i18n/base_partner_company_group.pot
  base_partner_company_group/i18n/ca.po
  base_partner_company_group/i18n/es.po
  base_partner_company_group/i18n/fr.po
  base_partner_company_group/i18n/fr_FR.po
  base_partner_company_group/i18n/it.po
  base_partner_company_group/i18n/partner_company_group.pot
  base_partner_company_group/i18n/zh_CN.po
  base_partner_company_group/models/__init__.py
  base_partner_company_group/models/res_partner.py
  base_partner_company_group/readme/CONTRIBUTORS.rst
  base_partner_company_group/readme/DESCRIPTION.rst
  base_partner_company_group/static/description/icon.png
  base_partner_company_group/static/description/index.html
  base_partner_company_group/tests/__init__.py
  base_partner_company_group/tests/test_base_partner_company_group.py
  base_partner_company_group/views/contact_view.xml
  setup/base_partner_company_group/odoo/addons/base_partner_company_group
  setup/base_partner_company_group/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1529 [13.0][ADD] company_default_partner_pricelist
  company_default_partner_pricelist/README.rst
  company_default_partner_pricelist/__init__.py
  company_default_partner_pricelist/__manifest__.py
  company_default_partner_pricelist/models/__init__.py
  company_default_partner_pricelist/models/product_pricelist.py
  company_default_partner_pricelist/models/res_company.py
  company_default_partner_pricelist/readme/CONTRIBUTORS.rst
  company_default_partner_pricelist/readme/DESCRIPTION.rst
  company_default_partner_pricelist/readme/USAGE.rst
  company_default_partner_pricelist/static/description/icon.png
  company_default_partner_pricelist/static/description/index.html
  company_default_partner_pricelist/tests/__init__.py
  company_default_partner_pricelist/tests/test_company_default_partner_pricelist.py
  company_default_partner_pricelist/views/res_company_views.xml
  setup/company_default_partner_pricelist/odoo/addons/company_default_partner_pricelist
  setup/company_default_partner_pricelist/setup.py
Labels: needs review, approved, bot is merging ⏳
