Repository OCA/partner-contact, pull requests merged in 2023-04, with the labels that each got.

#1505 [15.0][FIX] partner_contact_access_link: Pretty arrow
  partner_contact_access_link/views/res_partner_views.xml
Labels: needs review, approved, bot is merging ⏳

#1503 [16.0][ADD] partner_middlename
  .copier-answers.yml
  .github/workflows/test.yml
  partner_middlename/README.rst
  partner_middlename/__init__.py
  partner_middlename/__manifest__.py
  partner_middlename/models/__init__.py
  partner_middlename/models/res_config_settings.py
  partner_middlename/models/res_partner.py
  partner_middlename/readme/CONFIGURE.rst
  partner_middlename/readme/CONTRIBUTORS.rst
  partner_middlename/readme/DESCRIPTION.rst
  partner_middlename/readme/USAGE.rst
  partner_middlename/static/description/icon.png
  partner_middlename/tests/__init__.py
  partner_middlename/tests/test_config.py
  partner_middlename/tests/test_name.py
  partner_middlename/views/res_partner.xml
  partner_middlename/views/res_user.xml
  setup/partner_middlename/odoo/addons/partner_middlename
  setup/partner_middlename/setup.py
Labels: approved

#1511 [13.0][FIX]partner_exception: fix order, use odoo's value as fallback
  partner_exception/models/res_partner.py
Labels: approved, bot is merging ⏳
