Repository OCA/partner-contact, pull requests merged in 2023-11, with the labels that each got.

#1572 [16.0][MIG] partner-label: Migration to 16.0
  partner_label/README.rst
  partner_label/__init__.py
  partner_label/__manifest__.py
  partner_label/i18n/cs_CZ.po
  partner_label/i18n/da.po
  partner_label/i18n/de.po
  partner_label/i18n/es.po
  partner_label/i18n/fr.po
  partner_label/i18n/hr.po
  partner_label/i18n/hr_HR.po
  partner_label/i18n/it.po
  partner_label/i18n/nl_NL.po
  partner_label/i18n/partner_label.pot
  partner_label/i18n/pt_BR.po
  partner_label/i18n/pt_PT.po
  partner_label/i18n/sl.po
  partner_label/models/__init__.py
  partner_label/models/res_company.py
  partner_label/models/res_config_settings.py
  partner_label/readme/CONFIGURE.rst
  partner_label/readme/CONTRIBUTORS.rst
  partner_label/readme/DESCRIPTION.rst
  partner_label/readme/USAGE.rst
  partner_label/reports/res_partner.xml
  partner_label/static/description/icon.png
  partner_label/static/description/index.html
  partner_label/tests/__init__.py
  partner_label/tests/test_partner_label.py
  partner_label/views/base_config_settings.xml
  setup/partner_label/odoo/addons/partner_label
  setup/partner_label/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1500 [15.0][MIG] partner_disable_gravatar: Migration to 15.0
  partner_disable_gravatar/README.rst
  partner_disable_gravatar/__init__.py
  partner_disable_gravatar/__manifest__.py
  partner_disable_gravatar/i18n/it.po
  partner_disable_gravatar/i18n/partner_disable_gravatar.pot
  partner_disable_gravatar/models/__init__.py
  partner_disable_gravatar/models/res_partner.py
  partner_disable_gravatar/readme/CONTRIBUTORS.rst
  partner_disable_gravatar/readme/DESCRIPTION.rst
  partner_disable_gravatar/static/description/icon.png
  partner_disable_gravatar/static/description/index.html
  partner_disable_gravatar/tests/__init__.py
  partner_disable_gravatar/tests/test_partner_disable_gravatar.py
  setup/partner_disable_gravatar/odoo/addons/partner_disable_gravatar
  setup/partner_disable_gravatar/setup.py
Labels: bot is merging ⏳

#1596 [12.0][TEMP] base_location_nuts: do not run tests as it makes all CI pipeli…
  base_location_nuts/tests/__init__.py
Labels: bot is merging ⏳

#1493 [15.0][mig]-partner_stage
  partner_stage/README.rst
  partner_stage/__init__.py
  partner_stage/__manifest__.py
  partner_stage/data/partner_stage_data.xml
  partner_stage/i18n/it.po
  partner_stage/i18n/partner_stage.pot
  partner_stage/i18n/pt.po
  partner_stage/init_hook.py
  partner_stage/models/__init__.py
  partner_stage/models/res_partner.py
  partner_stage/models/res_partner_stage.py
  partner_stage/readme/CONFIGURATION.rst
  partner_stage/readme/CONTRIBUTORS.rst
  partner_stage/readme/DESCRIPTION.rst
  partner_stage/readme/USAGE.rst
  partner_stage/security/ir.model.access.csv
  partner_stage/static/description/icon.png
  partner_stage/static/description/index.html
  partner_stage/tests/__init__.py
  partner_stage/tests/test_partner_stage.py
  partner_stage/views/res_partner_stage_views.xml
  partner_stage/views/res_partner_views.xml
  setup/partner_stage/odoo/addons/partner_stage
  setup/partner_stage/setup.py
Labels: approved, bot is merging ⏳, stale

#1491 [12.0][MIG] partner_iterative_archive: Migration to 12.0
  partner_iterative_archive/README.rst
  partner_iterative_archive/__init__.py
  partner_iterative_archive/__manifest__.py
  partner_iterative_archive/i18n/partner_iterative_archive.pot
  partner_iterative_archive/models/__init__.py
  partner_iterative_archive/models/res_partner.py
  partner_iterative_archive/readme/CONTRIBUTORS.rst
  partner_iterative_archive/readme/DESCRIPTION.rst
  partner_iterative_archive/static/description/icon.png
  partner_iterative_archive/static/description/index.html
  partner_iterative_archive/tests/__init__.py
  partner_iterative_archive/tests/test_partner_iterative_archive.py
  setup/partner_iterative_archive/odoo/addons/partner_iterative_archive
  setup/partner_iterative_archive/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1497 [16.0][MIG] partner_email_check: Migration to 16.0
  partner_email_check/README.rst
  partner_email_check/__init__.py
  partner_email_check/__manifest__.py
  partner_email_check/demo/res_company_demo.xml
  partner_email_check/i18n/fr.po
  partner_email_check/i18n/it.po
  partner_email_check/i18n/partner_email_check.pot
  partner_email_check/models/__init__.py
  partner_email_check/models/res_company.py
  partner_email_check/models/res_config_settings.py
  partner_email_check/models/res_partner.py
  partner_email_check/readme/CONFIGURE.rst
  partner_email_check/readme/CONTRIBUTORS.rst
  partner_email_check/readme/DESCRIPTION.rst
  partner_email_check/readme/USAGE.rst
  partner_email_check/static/description/icon.png
  partner_email_check/static/description/index.html
  partner_email_check/tests/__init__.py
  partner_email_check/tests/test_partner_email_check.py
  partner_email_check/views/base_config_view.xml
  requirements.txt
  setup/partner_email_check/odoo/addons/partner_email_check
  setup/partner_email_check/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1545 [16.0][FIX] partner_company_default: multi company creation
  partner_company_default/models/__init__.py
  partner_company_default/models/res_company.py
  partner_company_default/models/res_partner.py
  partner_company_default/tests/__init__.py
  partner_company_default/tests/test_partner_company_default.py
Labels: approved, ready to merge, bot is merging ⏳

#1589 [16.0][MIG] partner_deduplicate_filter: Migration to version 16.0
  partner_deduplicate_filter/README.rst
  partner_deduplicate_filter/__init__.py
  partner_deduplicate_filter/__manifest__.py
  partner_deduplicate_filter/i18n/crm_deduplicate_filter.pot
  partner_deduplicate_filter/i18n/de.po
  partner_deduplicate_filter/i18n/es.po
  partner_deduplicate_filter/i18n/hr.po
  partner_deduplicate_filter/i18n/nl_NL.po
  partner_deduplicate_filter/i18n/partner_deduplicate_filter.pot
  partner_deduplicate_filter/i18n/sk.po
  partner_deduplicate_filter/i18n/sl.po
  partner_deduplicate_filter/i18n/tr.po
  partner_deduplicate_filter/readme/CONTRIBUTORS.rst
  partner_deduplicate_filter/readme/DESCRIPTION.rst
  partner_deduplicate_filter/readme/USAGE.rst
  partner_deduplicate_filter/static/description/icon.png
  partner_deduplicate_filter/static/description/icon.svg
  partner_deduplicate_filter/static/description/index.html
  partner_deduplicate_filter/tests/__init__.py
  partner_deduplicate_filter/tests/test_partner_deduplicate_filter.py
  partner_deduplicate_filter/wizards/__init__.py
  partner_deduplicate_filter/wizards/partner_merge.py
  partner_deduplicate_filter/wizards/partner_merge_view.xml
  setup/partner_deduplicate_filter/odoo/addons/partner_deduplicate_filter
  setup/partner_deduplicate_filter/setup.py
Labels: approved, bot is merging ⏳

#1586 [16.0][FIX] base_partner_sequence: consider written values in _needs_ref check
  base_partner_sequence/models/partner.py
  base_partner_sequence/tests/test_base_partner_sequence.py
Labels: approved, ready to merge, bot is merging ⏳

#1582 [16.0][ADD] partner_country_state_required
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  partner_country_state_required/README.rst
  partner_country_state_required/__init__.py
  partner_country_state_required/__manifest__.py
  partner_country_state_required/hooks.py
  partner_country_state_required/models/__init__.py
  partner_country_state_required/models/res_partner.py
  partner_country_state_required/readme/CONTRIBUTORS.rst
  partner_country_state_required/readme/DESCRIPTION.rst
  partner_country_state_required/static/description/index.html
  partner_country_state_required/tests/__init__.py
  partner_country_state_required/tests/test_state_required.py
  setup/partner_country_state_required/odoo/addons/partner_country_state_required
  setup/partner_country_state_required/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1461 [16.0] [ADD] partner_subject_to_vat
  partner_subject_to_vat/README.rst
  partner_subject_to_vat/__init__.py
  partner_subject_to_vat/__manifest__.py
  partner_subject_to_vat/models/__init__.py
  partner_subject_to_vat/models/res_partner.py
  partner_subject_to_vat/readme/CONTRIBUTORS.rst
  partner_subject_to_vat/readme/DESCRIPTION.rst
  partner_subject_to_vat/static/description/index.html
  partner_subject_to_vat/views/res_partner_view.xml
  setup/partner_subject_to_vat/odoo/addons/partner_subject_to_vat
  setup/partner_subject_to_vat/setup.py
Labels: approved, bot is merging ⏳

#1607 [16.0][MIG] partner_mobile_duplicate_warn
  partner_mobile_duplicate_warn/README.rst
  partner_mobile_duplicate_warn/__init__.py
  partner_mobile_duplicate_warn/__manifest__.py
  partner_mobile_duplicate_warn/i18n/fr.po
  partner_mobile_duplicate_warn/i18n/fr_BE.po
  partner_mobile_duplicate_warn/i18n/fr_CH.po
  partner_mobile_duplicate_warn/i18n/partner_mobile_duplicate_warn.pot
  partner_mobile_duplicate_warn/models/__init__.py
  partner_mobile_duplicate_warn/models/res_partner.py
  partner_mobile_duplicate_warn/readme/CONFIGURE.rst
  partner_mobile_duplicate_warn/readme/CONTRIBUTORS.rst
  partner_mobile_duplicate_warn/readme/DESCRIPTION.rst
  partner_mobile_duplicate_warn/readme/USAGE.rst
  partner_mobile_duplicate_warn/static/description/icon.png
  partner_mobile_duplicate_warn/static/description/index.html
  partner_mobile_duplicate_warn/static/description/partner_warn_banner.png
  partner_mobile_duplicate_warn/tests/__init__.py
  partner_mobile_duplicate_warn/tests/test_mobile_duplicate.py
  partner_mobile_duplicate_warn/views/res_partner.xml
  requirements.txt
  setup/partner_mobile_duplicate_warn/odoo/addons/partner_mobile_duplicate_warn
  setup/partner_mobile_duplicate_warn/setup.py
Labels: bot is merging ⏳

#1605 [ADD] partner_purchase_manager
  partner_purchase_manager/README.rst
  partner_purchase_manager/__init__.py
  partner_purchase_manager/__manifest__.py
  partner_purchase_manager/i18n/es.po
  partner_purchase_manager/i18n/partner_purchase_manager.pot
  partner_purchase_manager/models/__init__.py
  partner_purchase_manager/models/res_partner.py
  partner_purchase_manager/readme/CONTRIBUTORS.rst
  partner_purchase_manager/readme/DESCRIPTION.rst
  partner_purchase_manager/readme/USAGE.rst
  partner_purchase_manager/static/description/icon.png
  partner_purchase_manager/static/description/index.html
  partner_purchase_manager/views/res_partner_view.xml
  setup/partner_purchase_manager/odoo/addons/partner_purchase_manager
  setup/partner_purchase_manager/setup.py
Labels: needs review, approved, bot is merging ⏳

#1588 [16.0][ADD] partner_category_type
  partner_category_type/README.rst
  partner_category_type/__init__.py
  partner_category_type/__manifest__.py
  partner_category_type/models/__init__.py
  partner_category_type/models/res_partner_category.py
  partner_category_type/readme/CONTRIBUTORS.rst
  partner_category_type/readme/DESCRIPTION.rst
  partner_category_type/static/description/icon.png
  partner_category_type/static/description/index.html
  partner_category_type/views/res_partner_category_views.xml
  setup/partner_category_type/odoo/addons/partner_category_type
  setup/partner_category_type/setup.py
Labels: approved, bot is merging ⏳
