Repository OCA/partner-contact, pull requests merged in 2023-08, with the labels that each got.

#1466 [REF] partner_second_lastname: clean firstname and lastname2 when partner is a company
  partner_second_lastname/models/res_partner.py
  partner_second_lastname/tests/test_name.py
Labels: approved

#1520 [16.0][MIG] sale_partner_company_group
  sale_partner_company_group/README.rst
  sale_partner_company_group/__init__.py
  sale_partner_company_group/__manifest__.py
  sale_partner_company_group/hooks.py
  sale_partner_company_group/i18n/es.po
  sale_partner_company_group/i18n/sale_partner_company_group.pot
  sale_partner_company_group/i18n/zh_CN.po
  sale_partner_company_group/models/__init__.py
  sale_partner_company_group/models/res_partner.py
  sale_partner_company_group/models/sale_order.py
  sale_partner_company_group/readme/CONTRIBUTORS.rst
  sale_partner_company_group/readme/DESCRIPTION.rst
  sale_partner_company_group/static/description/icon.png
  sale_partner_company_group/static/description/index.html
  sale_partner_company_group/tests/__init__.py
  sale_partner_company_group/tests/test_sale_partner_company_group.py
  sale_partner_company_group/views/sale_order_view.xml
  setup/sale_partner_company_group/odoo/addons/sale_partner_company_group
  setup/sale_partner_company_group/setup.py
Labels: approved, bot is merging ⏳

#1560 [14.0][TEMP] base_location_nuts: do not run tests as it makes all CI pipelines to fail
  base_location_nuts/tests/__init__.py
Labels: bot is merging ⏳

#1550 [16.0][MIG] partner_bank_code
  partner_bank_code/README.rst
  partner_bank_code/__init__.py
  partner_bank_code/__manifest__.py
  partner_bank_code/i18n/fr.po
  partner_bank_code/i18n/hr.po
  partner_bank_code/i18n/partner_bank_code.pot
  partner_bank_code/models/__init__.py
  partner_bank_code/models/res_bank.py
  partner_bank_code/readme/CONTRIBUTORS.rst
  partner_bank_code/readme/DESCRIPTION.rst
  partner_bank_code/readme/USAGE.rst
  partner_bank_code/static/description/icon.png
  partner_bank_code/static/description/index.html
  partner_bank_code/tests/__init__.py
  partner_bank_code/tests/test_partner_bank_code.py
  partner_bank_code/views/res_bank.xml
  setup/partner_bank_code/odoo/addons/partner_bank_code
  setup/partner_bank_code/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#1541 [14.0][IMP] partner_manual_rank
  partner_manual_rank/models/res_partner.py
Labels: approved, bot is merging ⏳

#1563 [15.0][IMP] partner_manual_rank: don't disable automatically customer or supplier flags if already settled
  partner_manual_rank/models/res_partner.py
Labels: approved, bot is merging ⏳

#1564 [16.0][IMP] partner_manual_rank: don't disable automatically customer or supplier flags if already settled
  partner_manual_rank/models/res_partner.py
Labels: approved, bot is merging ⏳

#1533 [14.0][IMP] partner_manual_rank: Set default value based on `res_partner_search_mode` context
  partner_manual_rank/models/res_partner.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#1534 [16.0][IMP] partner_manual_rank: Set default value based on res_partner_search_mode context
  partner_manual_rank/models/res_partner.py
Labels: work in progress, approved, bot is merging ⏳

#1535 [15.0][IMP] partner_manual_rank: Set default value based on res_partner_search_mode context
  partner_manual_rank/models/res_partner.py
Labels: work in progress, approved, bot is merging ⏳

#1492 [15.0][mig]-partner_exception
  partner_exception/README.rst
  partner_exception/__init__.py
  partner_exception/__manifest__.py
  partner_exception/i18n/partner_exception.pot
  partner_exception/models/__init__.py
  partner_exception/models/res_partner.py
  partner_exception/readme/CONTRIBUTORS.rst
  partner_exception/readme/DESCRIPTION.rst
  partner_exception/readme/USAGE.rst
  partner_exception/static/description/icon.png
  partner_exception/static/description/index.html
  partner_exception/views/contact_views.xml
  setup/partner_exception/odoo/addons/partner_exception
  setup/partner_exception/setup.py
Labels: approved, bot is merging ⏳, stale

#1476 [16.0][IMP] partner_identification: use odoo_test_helper in tests
  partner_identification/tests/fake_models.py
  partner_identification/tests/test_res_partner.py
  test-requirements.txt
Labels: enhancement, approved, bot is merging ⏳, stale

#1561 [16.0][MIG] partner_contact_type_end_user
  partner_contact_type_end_user/README.rst
  partner_contact_type_end_user/__init__.py
  partner_contact_type_end_user/__manifest__.py
  partner_contact_type_end_user/models/__init__.py
  partner_contact_type_end_user/models/res_partner.py
  partner_contact_type_end_user/readme/CONTRIBUTORS.rst
  partner_contact_type_end_user/readme/DESCRIPTION.rst
  partner_contact_type_end_user/static/description/icon.png
  partner_contact_type_end_user/static/description/index.html
  setup/partner_contact_type_end_user/odoo/addons/partner_contact_type_end_user
  setup/partner_contact_type_end_user/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
