Repository OCA/partner-contact, pull requests merged in 2023-02, with the labels that each got.

#1449 [16.0][MIG] partner_contact_address_default: Migration to 16.0
  partner_contact_address_default/README.rst
  partner_contact_address_default/__init__.py
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/i18n/es.po
  partner_contact_address_default/i18n/fr.po
  partner_contact_address_default/i18n/fr_FR.po
  partner_contact_address_default/i18n/partner_contact_address_default.pot
  partner_contact_address_default/i18n/pt.po
  partner_contact_address_default/models/__init__.py
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/readme/CONTRIBUTORS.rst
  partner_contact_address_default/readme/DESCRIPTION.rst
  partner_contact_address_default/readme/USAGE.rst
  partner_contact_address_default/static/description/icon.png
  partner_contact_address_default/static/description/index.html
  partner_contact_address_default/tests/__init__.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
  partner_contact_address_default/views/res_partner_views.xml
  setup/partner_contact_address_default/odoo/addons/partner_contact_address_default
  setup/partner_contact_address_default/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1348 Patch typos & 404 on link
  partner_data_vies_populator/readme/DESCRIPTION.rst
  partner_data_vies_populator/readme/INSTALL.rst
Labels: approved, bot is merging ⏳

#1448 [16.0][MIG] partner_manual_rank: Migration to 16.0
  partner_manual_rank/README.rst
  partner_manual_rank/__init__.py
  partner_manual_rank/__manifest__.py
  partner_manual_rank/i18n/es.po
  partner_manual_rank/i18n/it.po
  partner_manual_rank/i18n/partner_manual_rank.pot
  partner_manual_rank/i18n/pt.po
  partner_manual_rank/models/__init__.py
  partner_manual_rank/models/res_partner.py
  partner_manual_rank/readme/CONTRIBUTORS.rst
  partner_manual_rank/readme/CREDITS.rst
  partner_manual_rank/readme/DESCRIPTION.rst
  partner_manual_rank/static/description/icon.png
  partner_manual_rank/static/description/index.html
  partner_manual_rank/tests/__init__.py
  partner_manual_rank/tests/test_res_partner.py
  partner_manual_rank/views/res_partner.xml
  setup/partner_manual_rank/odoo/addons/partner_manual_rank
  setup/partner_manual_rank/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1462 [13.0][FIX] base_location: Force saving city_id
  base_location/models/res_partner.py
Labels: approved, bot is merging ⏳

#1442 [16.0][MIG] partner_fax: Migration to 16.0
  partner_fax/README.rst
  partner_fax/__init__.py
  partner_fax/__manifest__.py
  partner_fax/i18n/ca.po
  partner_fax/i18n/de.po
  partner_fax/i18n/es.po
  partner_fax/i18n/fr.po
  partner_fax/i18n/he.po
  partner_fax/i18n/hr_HR.po
  partner_fax/i18n/it.po
  partner_fax/i18n/nl.po
  partner_fax/i18n/partner_fax.pot
  partner_fax/i18n/pt_BR.po
  partner_fax/i18n/sl.po
  partner_fax/i18n/zh_CN.po
  partner_fax/models/__init__.py
  partner_fax/models/res_partner.py
  partner_fax/readme/CONTRIBUTORS.rst
  partner_fax/readme/DESCRIPTION.rst
  partner_fax/readme/USAGE.rst
  partner_fax/static/description/icon.png
  partner_fax/static/description/index.html
  partner_fax/views/res_partner.xml
  setup/partner_fax/odoo/addons/partner_fax
  setup/partner_fax/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#1423 [16.0][MIG] partner_email_duplicate_warn
  partner_email_duplicate_warn/README.rst
  partner_email_duplicate_warn/__init__.py
  partner_email_duplicate_warn/__manifest__.py
  partner_email_duplicate_warn/i18n/partner_email_duplicate_warn.pot
  partner_email_duplicate_warn/models/__init__.py
  partner_email_duplicate_warn/models/res_partner.py
  partner_email_duplicate_warn/readme/CONFIGURE.rst
  partner_email_duplicate_warn/readme/CONTRIBUTORS.rst
  partner_email_duplicate_warn/readme/DESCRIPTION.rst
  partner_email_duplicate_warn/readme/ROADMAP.rst
  partner_email_duplicate_warn/readme/USAGE.rst
  partner_email_duplicate_warn/static/description/icon.png
  partner_email_duplicate_warn/static/description/index.html
  partner_email_duplicate_warn/static/description/partner_warn_banner.png
  partner_email_duplicate_warn/tests/__init__.py
  partner_email_duplicate_warn/tests/test_email_duplicate.py
  partner_email_duplicate_warn/views/res_partner.xml
  setup/partner_email_duplicate_warn/odoo/addons/partner_email_duplicate_warn
  setup/partner_email_duplicate_warn/setup.py
Labels: bot is merging ⏳

#1430 [15.0][MIG] partner_email_check
  partner_email_check/README.rst
  partner_email_check/__init__.py
  partner_email_check/__manifest__.py
  partner_email_check/demo/res_company_demo.xml
  partner_email_check/i18n/fr.po
  partner_email_check/i18n/it.po
  partner_email_check/i18n/partner_email_check.pot
  partner_email_check/models/__init__.py
  partner_email_check/models/res_company.py
  partner_email_check/models/res_config_settings.py
  partner_email_check/models/res_partner.py
  partner_email_check/readme/CONFIGURE.rst
  partner_email_check/readme/CONTRIBUTORS.rst
  partner_email_check/readme/DESCRIPTION.rst
  partner_email_check/readme/USAGE.rst
  partner_email_check/static/description/icon.png
  partner_email_check/static/description/index.html
  partner_email_check/tests/__init__.py
  partner_email_check/tests/test_partner_email_check.py
  partner_email_check/views/base_config_view.xml
  requirements.txt
  setup/partner_email_check/odoo/addons/partner_email_check
  setup/partner_email_check/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1471 [FIX] base_location: Waadt state already exists in Odoo
  base_location/tests/test_base_location.py
Labels: bot is merging ⏳

#1470 [16.0][MIG] partner_address_two_lines: Migration to 16.0
  partner_address_two_lines/README.rst
  partner_address_two_lines/__init__.py
  partner_address_two_lines/__manifest__.py
  partner_address_two_lines/i18n/partner_address_two_lines.pot
  partner_address_two_lines/models/__init__.py
  partner_address_two_lines/models/ir_actions_report.py
  partner_address_two_lines/models/res_partner.py
  partner_address_two_lines/readme/CONTRIBUTORS.rst
  partner_address_two_lines/readme/DESCRIPTION.rst
  partner_address_two_lines/static/description/icon.png
  partner_address_two_lines/static/description/index.html
  setup/partner_address_two_lines/odoo/addons/partner_address_two_lines
  setup/partner_address_two_lines/setup.py
Labels: approved, bot is merging ⏳

#1319 [13.0][ADD] partner_country_lang: New addon.
  partner_country_lang/README.rst
  partner_country_lang/__init__.py
  partner_country_lang/__manifest__.py
  partner_country_lang/i18n/es.po
  partner_country_lang/i18n/partner_country_lang.pot
  partner_country_lang/models/__init__.py
  partner_country_lang/models/res_country.py
  partner_country_lang/models/res_partner.py
  partner_country_lang/readme/CONFIGURE.rst
  partner_country_lang/readme/CONTRIBUTORS.rst
  partner_country_lang/readme/DESCRIPTION.rst
  partner_country_lang/readme/USAGE.rst
  partner_country_lang/static/description/icon.png
  partner_country_lang/static/description/index.html
  partner_country_lang/tests/__init__.py
  partner_country_lang/tests/test_partner_country_lang.py
  partner_country_lang/views/res_country_view.xml
  setup/partner_country_lang/odoo/addons/partner_country_lang
  setup/partner_country_lang/setup.py
Labels: needs review, approved, bot is merging ⏳

#1468 [15.0][MIG] partner_pricelist_tracking: Migration to version 15.0
  partner_pricelist_tracking/README.rst
  partner_pricelist_tracking/__init__.py
  partner_pricelist_tracking/__manifest__.py
  partner_pricelist_tracking/i18n/partner_pricelist_tracking.pot
  partner_pricelist_tracking/models/__init__.py
  partner_pricelist_tracking/models/res_partner.py
  partner_pricelist_tracking/readme/CONFIGURE.rst
  partner_pricelist_tracking/readme/CONTRIBUTORS.rst
  partner_pricelist_tracking/readme/DESCRIPTION.rst
  partner_pricelist_tracking/readme/ROADMAP.rst
  partner_pricelist_tracking/static/description/icon.png
  partner_pricelist_tracking/static/description/index.html
  setup/partner_pricelist_tracking/odoo/addons/partner_pricelist_tracking
  setup/partner_pricelist_tracking/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1473 [15.0][MIG] partner_country_lang: Migration to version 15.0
  partner_country_lang/README.rst
  partner_country_lang/__init__.py
  partner_country_lang/__manifest__.py
  partner_country_lang/i18n/es.po
  partner_country_lang/i18n/partner_country_lang.pot
  partner_country_lang/models/__init__.py
  partner_country_lang/models/res_country.py
  partner_country_lang/models/res_partner.py
  partner_country_lang/readme/CONFIGURE.rst
  partner_country_lang/readme/CONTRIBUTORS.rst
  partner_country_lang/readme/DESCRIPTION.rst
  partner_country_lang/readme/USAGE.rst
  partner_country_lang/static/description/icon.png
  partner_country_lang/static/description/index.html
  partner_country_lang/tests/__init__.py
  partner_country_lang/tests/test_partner_country_lang.py
  partner_country_lang/views/res_country_view.xml
  setup/partner_country_lang/odoo/addons/partner_country_lang
  setup/partner_country_lang/setup.py
Labels: approved, bot is merging ⏳
