Repository OCA/partner-contact, pull requests merged in 2023-03, with the labels that each got.

#1447 [15.0][FIX] partner_company_group: avoid non-deterministic error
  sale_partner_company_group/models/res_partner.py
Labels: bot is merging ⏳

#1408 [13.0][ADD] partner_exception
  partner_company_group/models/res_partner.py
  partner_exception/__init__.py
  partner_exception/__manifest__.py
  partner_exception/models/__init__.py
  partner_exception/models/res_partner.py
  partner_exception/views/contact_views.xml
  setup/partner_exception/odoo/addons/partner_exception
  setup/partner_exception/setup.py
Labels: approved, bot is merging ⏳

#1464 [16.0][MIG] partner_tz
  partner_tz/README.rst
  partner_tz/__init__.py
  partner_tz/__manifest__.py
  partner_tz/i18n/partner_tz.pot
  partner_tz/readme/CONTRIBUTORS.rst
  partner_tz/readme/CREDITS.rst
  partner_tz/readme/DESCRIPTION.rst
  partner_tz/readme/ROADMAP.rst
  partner_tz/static/description/icon.png
  partner_tz/static/description/index.html
  partner_tz/tests/__init__.py
  partner_tz/tests/common.py
  partner_tz/tests/test_tz.py
  partner_tz/tools/__init__.py
  partner_tz/tools/tz_utils.py
  partner_tz/views/res_partner.xml
  setup/partner_tz/odoo/addons/partner_tz
  setup/partner_tz/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1486 [15.0][FIX] base_location: City/locations completion object display_name is…
  base_location/models/res_city_zip.py
  base_location/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#1338 [15.0][ADD] partner_name_hide_parent : New Module
  partner_name_hide_parent/README.rst
  partner_name_hide_parent/__init__.py
  partner_name_hide_parent/__manifest__.py
  partner_name_hide_parent/i18n/ja.po
  partner_name_hide_parent/models/__init__.py
  partner_name_hide_parent/models/res_partner.py
  partner_name_hide_parent/readme/DESCRIPTION.rst
  partner_name_hide_parent/readme/USAGE.rst
  partner_name_hide_parent/static/description/index.html
  partner_name_hide_parent/tests/__init__.py
  partner_name_hide_parent/tests/test_partner_name_hide_parent.py
  partner_name_hide_parent/views/res_partner_views.xml
  setup/partner_name_hide_parent/odoo/addons/partner_name_hide_parent
  setup/partner_name_hide_parent/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1467 [MIG] partner_company_default: Migration to 16.0
  partner_company_default/README.rst
  partner_company_default/__init__.py
  partner_company_default/__manifest__.py
  partner_company_default/i18n/partner_company_default.pot
  partner_company_default/models/__init__.py
  partner_company_default/models/res_partner.py
  partner_company_default/readme/DESCRIPTION.rst
  partner_company_default/static/description/icon.png
  partner_company_default/static/description/index.html
  setup/partner_company_default/odoo/addons/partner_company_default
  setup/partner_company_default/setup.py
Labels: approved, ready to merge, bot is merging ⏳
