Repository OCA/partner-contact, pull requests merged in 2023-07, with the labels that each got.

#1549 [16.0][UPD] partner_interest_group no_create on interest_group_ids
  partner_interest_group/views/res_partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1536 [16.0][MIG] sale_customer_rank: Migration to 16.0
  sale_customer_rank/README.rst
  sale_customer_rank/__init__.py
  sale_customer_rank/__manifest__.py
  sale_customer_rank/i18n/es.po
  sale_customer_rank/i18n/fr.po
  sale_customer_rank/i18n/sale_customer_rank.pot
  sale_customer_rank/models/__init__.py
  sale_customer_rank/models/sale_order.py
  sale_customer_rank/readme/CONTRIBUTORS.rst
  sale_customer_rank/readme/DESCRIPTION.rst
  sale_customer_rank/static/description/icon.png
  sale_customer_rank/static/description/index.html
  sale_customer_rank/tests/__init__.py
  sale_customer_rank/tests/test_sale_customer_rank.py
  setup/sale_customer_rank/odoo/addons/sale_customer_rank
  setup/sale_customer_rank/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1543 [16.0][MIG] partner helper + rename it partner_address_split
  partner_address_split/README.rst
  partner_address_split/__init__.py
  partner_address_split/__manifest__.py
  partner_address_split/models/__init__.py
  partner_address_split/models/partner.py
  partner_address_split/readme/CONTRIBUTORS.rst
  partner_address_split/readme/DESCRIPTION.rst
  partner_address_split/static/description/icon.png
  partner_address_split/static/description/index.html
  partner_address_split/tests/__init__.py
  partner_address_split/tests/test_split_address.py
  setup/partner_address_split/odoo/addons/partner_address_split
  setup/partner_address_split/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1521 [16.0][MIG] account_partner_company_group
  account_partner_company_group/README.rst
  account_partner_company_group/__init__.py
  account_partner_company_group/__manifest__.py
  account_partner_company_group/hooks.py
  account_partner_company_group/i18n/account_partner_company_group.pot
  account_partner_company_group/i18n/es.po
  account_partner_company_group/i18n/partner_company_group.pot
  account_partner_company_group/i18n/zh_CN.po
  account_partner_company_group/models/__init__.py
  account_partner_company_group/models/account_move.py
  account_partner_company_group/readme/CONTRIBUTORS.rst
  account_partner_company_group/readme/DESCRIPTION.rst
  account_partner_company_group/static/description/icon.png
  account_partner_company_group/static/description/index.html
  account_partner_company_group/views/account_move_views.xml
  setup/account_partner_company_group/odoo/addons/account_partner_company_group
  setup/account_partner_company_group/setup.py
Labels: bot is merging ⏳
