Repository OCA/partner-contact, pull requests merged in 2023-10, with the labels that each got.

#1525 [16.0][MIG] partner_deduplicate_by_ref
  partner_deduplicate_by_ref/README.rst
  partner_deduplicate_by_ref/__init__.py
  partner_deduplicate_by_ref/__manifest__.py
  partner_deduplicate_by_ref/i18n/ar.po
  partner_deduplicate_by_ref/i18n/bs.po
  partner_deduplicate_by_ref/i18n/cs.po
  partner_deduplicate_by_ref/i18n/de.po
  partner_deduplicate_by_ref/i18n/en_GB.po
  partner_deduplicate_by_ref/i18n/es.po
  partner_deduplicate_by_ref/i18n/es_CR.po
  partner_deduplicate_by_ref/i18n/es_EC.po
  partner_deduplicate_by_ref/i18n/es_MX.po
  partner_deduplicate_by_ref/i18n/et.po
  partner_deduplicate_by_ref/i18n/fr.po
  partner_deduplicate_by_ref/i18n/gl.po
  partner_deduplicate_by_ref/i18n/hr.po
  partner_deduplicate_by_ref/i18n/hu.po
  partner_deduplicate_by_ref/i18n/it.po
  partner_deduplicate_by_ref/i18n/ja.po
  partner_deduplicate_by_ref/i18n/lt.po
  partner_deduplicate_by_ref/i18n/lv.po
  partner_deduplicate_by_ref/i18n/mk.po
  partner_deduplicate_by_ref/i18n/mn.po
  partner_deduplicate_by_ref/i18n/nb.po
  partner_deduplicate_by_ref/i18n/nl.po
  partner_deduplicate_by_ref/i18n/nl_BE.po
  partner_deduplicate_by_ref/i18n/nl_NL.po
  partner_deduplicate_by_ref/i18n/partner_deduplicate_by_ref.pot
  partner_deduplicate_by_ref/i18n/pt.po
  partner_deduplicate_by_ref/i18n/pt_BR.po
  partner_deduplicate_by_ref/i18n/pt_PT.po
  partner_deduplicate_by_ref/i18n/ro.po
  partner_deduplicate_by_ref/i18n/ru.po
  partner_deduplicate_by_ref/i18n/sk.po
  partner_deduplicate_by_ref/i18n/sl.po
  partner_deduplicate_by_ref/i18n/sv.po
  partner_deduplicate_by_ref/i18n/th.po
  partner_deduplicate_by_ref/i18n/tr.po
  partner_deduplicate_by_ref/i18n/zh_CN.po
  partner_deduplicate_by_ref/i18n/zh_TW.po
  partner_deduplicate_by_ref/readme/CONTRIBUTORS.rst
  partner_deduplicate_by_ref/readme/DESCRIPTION.rst
  partner_deduplicate_by_ref/readme/USAGE.rst
  partner_deduplicate_by_ref/static/description/icon.png
  partner_deduplicate_by_ref/static/description/icon.svg
  partner_deduplicate_by_ref/static/description/index.html
  partner_deduplicate_by_ref/tests/__init__.py
  partner_deduplicate_by_ref/tests/test_partner_deduplicate_by_ref.py
  partner_deduplicate_by_ref/wizards/__init__.py
  partner_deduplicate_by_ref/wizards/partner_merge.py
  partner_deduplicate_by_ref/wizards/partner_merge_view.xml
  setup/partner_deduplicate_by_ref/odoo/addons/partner_deduplicate_by_ref
  setup/partner_deduplicate_by_ref/setup.py
Labels: bot is merging ⏳, stale

#1538 [16.0][MIG] purchase_supplier_rank (from 13.0)
  purchase_supplier_rank/README.rst
  purchase_supplier_rank/__init__.py
  purchase_supplier_rank/__manifest__.py
  purchase_supplier_rank/i18n/es.po
  purchase_supplier_rank/i18n/purchase_supplier_rank.pot
  purchase_supplier_rank/models/__init__.py
  purchase_supplier_rank/models/purchase_order.py
  purchase_supplier_rank/readme/CONTRIBUTORS.rst
  purchase_supplier_rank/readme/DESCRIPTION.rst
  purchase_supplier_rank/static/description/icon.png
  purchase_supplier_rank/static/description/index.html
  purchase_supplier_rank/tests/__init__.py
  purchase_supplier_rank/tests/test_purchase_supplier_rank.py
  setup/purchase_supplier_rank/odoo/addons/purchase_supplier_rank
  setup/purchase_supplier_rank/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1573 [16.0][MIG] partner_identification_gln: Migration to 16.0
  partner_identification_gln/README.rst
  partner_identification_gln/__init__.py
  partner_identification_gln/__manifest__.py
  partner_identification_gln/data/partner_identification_gln.xml
  partner_identification_gln/i18n/partner_identification_gln.pot
  partner_identification_gln/i18n/sl.po
  partner_identification_gln/models/__init__.py
  partner_identification_gln/models/res_partner_id_category.py
  partner_identification_gln/readme/CONTRIBUTORS.rst
  partner_identification_gln/readme/CREDITS.rst
  partner_identification_gln/readme/DESCRIPTION.rst
  partner_identification_gln/readme/INSTALL.rst
  partner_identification_gln/static/description/icon.svg
  partner_identification_gln/static/description/index.html
  partner_identification_gln/tests/__init__.py
  partner_identification_gln/tests/test_gln.py
  setup/partner_identification_gln/odoo/addons/partner_identification_gln
  setup/partner_identification_gln/setup.py
Labels: approved, bot is merging ⏳

#1579 [16.0][MIG] partner_company_group: Migration to 16.0
  partner_company_group/README.rst
  partner_company_group/__init__.py
  partner_company_group/__manifest__.py
  partner_company_group/i18n/ca.po
  partner_company_group/i18n/es.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/i18n/zh_CN.po
  partner_company_group/readme/CONTRIBUTORS.rst
  partner_company_group/readme/DESCRIPTION.rst
  partner_company_group/static/description/icon.png
  partner_company_group/static/description/index.html
  partner_company_group/views/account_move_views.xml
  partner_company_group/views/contact_view.xml
  partner_company_group/views/opportunity_view.xml
  partner_company_group/views/sale_order_view.xml
  setup/partner_company_group/odoo/addons/partner_company_group
  setup/partner_company_group/setup.py
Labels: bot is merging ⏳

#1580 [16.0][IMP] partner_manual_rank: hide base customer and supplier filters
  partner_manual_rank/views/res_partner.xml
Labels: approved, bot is merging ⏳

#1583 [16.0][ADD] partner_identification_eori
  partner_identification/__manifest__.py
  partner_identification/models/res_partner_id_category.py
  partner_identification_eori/README.rst
  partner_identification_eori/__init__.py
  partner_identification_eori/__manifest__.py
  partner_identification_eori/data/partner_identification_eori.xml
  partner_identification_eori/models/__init__.py
  partner_identification_eori/models/res_partner_id_category.py
  partner_identification_eori/readme/CONTRIBUTORS.rst
  partner_identification_eori/readme/DESCRIPTION.rst
  partner_identification_eori/static/description/icon.svg
  partner_identification_eori/static/description/index.html
  partner_identification_eori/tests/__init__.py
  partner_identification_eori/tests/test_eori.py
  partner_identification_gln/__manifest__.py
  partner_identification_gln/models/res_partner_id_category.py
  setup/partner_identification_eori/odoo/addons/partner_identification_eori
  setup/partner_identification_eori/setup.py
Labels: approved, bot is merging ⏳

#1413 [15.0][ADD] partner_supplierinfo: New module
  partner_supplierinfo/README.rst
  partner_supplierinfo/__init__.py
  partner_supplierinfo/__manifest__.py
  partner_supplierinfo/models/__init__.py
  partner_supplierinfo/models/partner_supplierinfo.py
  partner_supplierinfo/models/res_partner.py
  partner_supplierinfo/readme/CONTRIBUTORS.rst
  partner_supplierinfo/readme/DESCRIPTION.rst
  partner_supplierinfo/readme/ROADMAP.rst
  partner_supplierinfo/readme/USAGE.rst
  partner_supplierinfo/security/ir.model.access.csv
  partner_supplierinfo/static/description/index.html
  partner_supplierinfo/tests/__init__.py
  partner_supplierinfo/tests/test_partner_supplierinfo.py
  partner_supplierinfo/views/res_partner_view.xml
  setup/partner_supplierinfo/odoo/addons/partner_supplierinfo
  setup/partner_supplierinfo/setup.py
Labels: needs review, approved, bot is merging ⏳

#1591 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  animal/i18n/animal.pot
  res_partner_journal_items_link/__init__.py
Labels: help wanted, needs review
