Repository OCA/partner-contact, pull requests merged in 2023-01, with the labels that each got.

#1149 [14.0][IMP][partner_identification] Allow attachments and chatter for res_partner_id_number model
  partner_identification/models/res_partner_id_number.py
  partner_identification/views/res_partner_id_number_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1443 [13.0][IMP] base_partner_sequence: improve write performance
  base_partner_sequence/models/partner.py
Labels: approved, ready to merge, bot is merging ⏳

#1451 [14.0][FW][IMP] base_partner_sequence: improve write performance
  base_partner_sequence/models/partner.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1457 [UPD] Copier update
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳
