Repository OCA/partner-contact, pull requests merged in 2024-03, with the labels that each got.

#1648 [17.0][MIG] partner_vat_unique: Migration to 17.0
  partner_vat_unique/README.rst
  partner_vat_unique/__init__.py
  partner_vat_unique/__manifest__.py
  partner_vat_unique/i18n/de.po
  partner_vat_unique/i18n/es.po
  partner_vat_unique/i18n/fr.po
  partner_vat_unique/i18n/hr.po
  partner_vat_unique/i18n/it.po
  partner_vat_unique/i18n/partner_vat_unique.pot
  partner_vat_unique/i18n/pt.po
  partner_vat_unique/models/__init__.py
  partner_vat_unique/models/res_partner.py
  partner_vat_unique/pyproject.toml
  partner_vat_unique/readme/CONTRIBUTORS.md
  partner_vat_unique/readme/DESCRIPTION.md
  partner_vat_unique/readme/INSTALL.md
  partner_vat_unique/readme/ROADMAP.md
  partner_vat_unique/static/description/icon.png
  partner_vat_unique/static/description/index.html
  partner_vat_unique/tests/__init__.py
  partner_vat_unique/tests/test_vat_unique.py
Labels: approved, ready to merge, bot is merging ⏳

#1684 [15.0][IMP] partner_pricelist_search: support searching subfields
  partner_pricelist_search/README.rst
  partner_pricelist_search/models/res_partner.py
  partner_pricelist_search/readme/CONTRIBUTORS.rst
  partner_pricelist_search/readme/ROADMAP.rst
  partner_pricelist_search/static/description/index.html
  partner_pricelist_search/tests/test_partner_pricelist_search.py
Labels: approved, bot is merging ⏳

#1655 [16.0][IMP] base_partner_sequence: improve write performance
  base_partner_sequence/models/partner.py
  partner_contact_age_range/tests/test_res_partner_age_range.py
Labels: approved, ready to merge, bot is merging ⏳

#1577 [16.0][ADD] partner_lastname_uppercase
  partner_lastname_uppercase/README.rst
  partner_lastname_uppercase/__init__.py
  partner_lastname_uppercase/__manifest__.py
  partner_lastname_uppercase/data/actions.xml
  partner_lastname_uppercase/models/__init__.py
  partner_lastname_uppercase/models/res_config_settings.py
  partner_lastname_uppercase/models/res_partner.py
  partner_lastname_uppercase/readme/CONFIGURE.rst
  partner_lastname_uppercase/readme/CONTRIBUTORS.rst
  partner_lastname_uppercase/readme/DESCRIPTION.rst
  partner_lastname_uppercase/readme/USAGE.rst
  partner_lastname_uppercase/static/description/index.html
  partner_lastname_uppercase/tests/__init__.py
  partner_lastname_uppercase/tests/test_res_partner.py
  partner_lastname_uppercase/views/res_config_settings.xml
  setup/partner_lastname_uppercase/odoo/addons/partner_lastname_uppercase
  setup/partner_lastname_uppercase/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1691 [IMP] partner_(ref,vat)_unique: enable name search by the VAT Identification Number and Reference
  partner_ref_unique/__manifest__.py
  partner_ref_unique/models/res_partner.py
  partner_ref_unique/tests/test_res_partner_ref.py
  partner_vat_unique/__manifest__.py
  partner_vat_unique/models/res_partner.py
  partner_vat_unique/tests/test_vat_unique.py
Labels: approved, ready to merge, bot is merging ⏳

#1695 [16.0][IMP] partner_contact_address_default: set default contact
  partner_contact_address_default/README.rst
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/i18n/es.po
  partner_contact_address_default/i18n/partner_contact_address_default.pot
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/readme/CONTRIBUTORS.rst
  partner_contact_address_default/readme/DESCRIPTION.rst
  partner_contact_address_default/readme/USAGE.rst
  partner_contact_address_default/static/description/index.html
  partner_contact_address_default/tests/test_partner_contact_address_default.py
  partner_contact_address_default/views/res_partner_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1644 [16.0][FIX] partner_interest_group: solution to correlation problems with multi-company
  partner_interest_group/__manifest__.py
  partner_interest_group/i18n/es.po
  partner_interest_group/models/res_partner_interest_group.py
  partner_interest_group/security/interest_group_rules.xml
  partner_interest_group/views/res_partner_interest_group_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1706 [16.0][partner_stage] remove old v14 migration scripts
  partner_stage/migrations/14.0.2.0.0/post-migration.py
  partner_stage/migrations/14.0.2.0.0/pre-migrate.py
Labels: bot is merging ⏳

#1658 [17.0][MIG] partner_manual_rank: Migration to 17.0
  partner_manual_rank/README.rst
  partner_manual_rank/__init__.py
  partner_manual_rank/__manifest__.py
  partner_manual_rank/i18n/es.po
  partner_manual_rank/i18n/fr.po
  partner_manual_rank/i18n/it.po
  partner_manual_rank/i18n/partner_manual_rank.pot
  partner_manual_rank/i18n/pt.po
  partner_manual_rank/models/__init__.py
  partner_manual_rank/models/res_partner.py
  partner_manual_rank/pyproject.toml
  partner_manual_rank/readme/CONTRIBUTORS.md
  partner_manual_rank/readme/CREDITS.md
  partner_manual_rank/readme/DESCRIPTION.md
  partner_manual_rank/static/description/icon.png
  partner_manual_rank/static/description/index.html
  partner_manual_rank/tests/__init__.py
  partner_manual_rank/tests/test_res_partner.py
  partner_manual_rank/views/res_partner.xml
Labels: approved, bot is merging ⏳
