Repository OCA/partner-contact, pull requests merged in 2024-05, with the labels that each got.

#1710 [17.0][MIG] partner_stage_only_confirmed: Migration to 17.0
  partner_stage_only_confirmed/README.rst
  partner_stage_only_confirmed/__init__.py
  partner_stage_only_confirmed/__manifest__.py
  partner_stage_only_confirmed/models/__init__.py
  partner_stage_only_confirmed/models/base.py
  partner_stage_only_confirmed/pyproject.toml
  partner_stage_only_confirmed/readme/CONFIGURATION.rst
  partner_stage_only_confirmed/readme/CONTRIBUTORS.md
  partner_stage_only_confirmed/readme/DESCRIPTION.md
  partner_stage_only_confirmed/readme/USAGE.md
  partner_stage_only_confirmed/static/description/icon.png
  partner_stage_only_confirmed/static/description/index.html
  setup/partner_stage_only_confirmed/odoo/addons/partner_stage_only_confirmed
  setup/partner_stage_only_confirmed/setup.py
Labels: approved, bot is merging ⏳

#1530 [15.0][mig]partner_label
  partner_label/README.rst
  partner_label/__init__.py
  partner_label/__manifest__.py
  partner_label/i18n/cs_CZ.po
  partner_label/i18n/da.po
  partner_label/i18n/de.po
  partner_label/i18n/es.po
  partner_label/i18n/fr.po
  partner_label/i18n/hr.po
  partner_label/i18n/hr_HR.po
  partner_label/i18n/it.po
  partner_label/i18n/nl_NL.po
  partner_label/i18n/partner_label.pot
  partner_label/i18n/pt_BR.po
  partner_label/i18n/pt_PT.po
  partner_label/i18n/sl.po
  partner_label/models/__init__.py
  partner_label/models/res_company.py
  partner_label/models/res_config_settings.py
  partner_label/readme/CONFIGURE.rst
  partner_label/readme/CONTRIBUTORS.rst
  partner_label/readme/DESCRIPTION.rst
  partner_label/readme/USAGE.rst
  partner_label/reports/res_partner.xml
  partner_label/static/description/icon.png
  partner_label/static/description/index.html
  partner_label/tests/__init__.py
  partner_label/tests/test_partner_label.py
  partner_label/views/base_config_settings.xml
  setup/partner_label/odoo/addons/partner_label
  setup/partner_label/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, no stale

#1546 [16.0] Replace partner_address_two_lines by partner_display_name_line_break
  partner_address_two_lines/models/res_partner.py
  partner_display_name_line_break/README.rst
  partner_display_name_line_break/__init__.py
  partner_display_name_line_break/__manifest__.py
  partner_display_name_line_break/i18n/it.po
  partner_display_name_line_break/i18n/partner_address_two_lines.pot
  partner_display_name_line_break/models/__init__.py
  partner_display_name_line_break/models/ir_actions_report.py
  partner_display_name_line_break/models/res_partner.py
  partner_display_name_line_break/readme/CONTRIBUTORS.rst
  partner_display_name_line_break/readme/DESCRIPTION.rst
  partner_display_name_line_break/static/description/icon.png
  partner_display_name_line_break/static/description/index.html
  partner_display_name_line_break/tests/__init__.py
  partner_display_name_line_break/tests/test_res_partner.py
  setup/partner_address_two_lines/odoo/addons/partner_address_two_lines
  setup/partner_display_name_line_break/odoo/addons/partner_display_name_line_break
  setup/partner_display_name_line_break/setup.py
Labels: enhancement, needs fixing, bot is merging ⏳

#1745 [17.0][MIG] base_partner_company_group: Migration to 17.0
  base_partner_company_group/README.rst
  base_partner_company_group/__init__.py
  base_partner_company_group/__manifest__.py
  base_partner_company_group/i18n/base_partner_company_group.pot
  base_partner_company_group/i18n/ca.po
  base_partner_company_group/i18n/es.po
  base_partner_company_group/i18n/fr.po
  base_partner_company_group/i18n/fr_FR.po
  base_partner_company_group/i18n/hr.po
  base_partner_company_group/i18n/it.po
  base_partner_company_group/i18n/partner_company_group.pot
  base_partner_company_group/i18n/pt_BR.po
  base_partner_company_group/i18n/zh_CN.po
  base_partner_company_group/models/__init__.py
  base_partner_company_group/models/res_partner.py
  base_partner_company_group/pyproject.toml
  base_partner_company_group/readme/CONTRIBUTORS.md
  base_partner_company_group/readme/DESCRIPTION.md
  base_partner_company_group/static/description/icon.png
  base_partner_company_group/static/description/index.html
  base_partner_company_group/tests/__init__.py
  base_partner_company_group/tests/test_base_partner_company_group.py
  base_partner_company_group/views/contact_view.xml
Labels: approved, bot is merging ⏳

#1728 [MIG] partner_country_lang: Migration to 14.0
  partner_country_lang/README.rst
  partner_country_lang/__init__.py
  partner_country_lang/__manifest__.py
  partner_country_lang/i18n/es.po
  partner_country_lang/i18n/partner_country_lang.pot
  partner_country_lang/models/__init__.py
  partner_country_lang/models/res_country.py
  partner_country_lang/models/res_partner.py
  partner_country_lang/readme/CONFIGURE.rst
  partner_country_lang/readme/CONTRIBUTORS.rst
  partner_country_lang/readme/DESCRIPTION.rst
  partner_country_lang/readme/USAGE.rst
  partner_country_lang/static/description/icon.png
  partner_country_lang/static/description/index.html
  partner_country_lang/tests/__init__.py
  partner_country_lang/tests/test_partner_country_lang.py
  partner_country_lang/views/res_country_view.xml
  setup/partner_country_lang/odoo/addons/partner_country_lang
  setup/partner_country_lang/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1744 [UPD] partner_manual_rank
  partner_manual_rank/models/res_partner.py
  partner_manual_rank/tests/__init__.py
  partner_manual_rank/tests/test_res_partner.py
Labels: approved, bot is merging ⏳

#1758 [17.0][MIG] partner_contact_access_link: Migration to 17.0
  partner_contact_access_link/README.rst
  partner_contact_access_link/__init__.py
  partner_contact_access_link/__manifest__.py
  partner_contact_access_link/i18n/ca.po
  partner_contact_access_link/i18n/es.po
  partner_contact_access_link/i18n/fr.po
  partner_contact_access_link/i18n/hr.po
  partner_contact_access_link/i18n/it.po
  partner_contact_access_link/i18n/partner_contact_access_link.pot
  partner_contact_access_link/i18n/pt_BR.po
  partner_contact_access_link/models/__init__.py
  partner_contact_access_link/models/res_partner.py
  partner_contact_access_link/pyproject.toml
  partner_contact_access_link/readme/CONTRIBUTORS.md
  partner_contact_access_link/readme/DESCRIPTION.md
  partner_contact_access_link/readme/USAGE.md
  partner_contact_access_link/static/description/full-form.gif
  partner_contact_access_link/static/description/icon.png
  partner_contact_access_link/static/description/index.html
  partner_contact_access_link/tests/__init__.py
  partner_contact_access_link/tests/test_partner_contact_access_link.py
  partner_contact_access_link/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#1760 [17.0] [IMP] partner_affiliate: add button in kanban to open form
  partner_affiliate/README.rst
  partner_affiliate/models/res_partner.py
  partner_affiliate/readme/CONTRIBUTORS.md
  partner_affiliate/static/description/index.html
  partner_affiliate/tests/__init__.py
  partner_affiliate/tests/test_partner_affiliate.py
  partner_affiliate/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1720 [17.0][MIG] partner_email_check: Migration to 17.0
  partner_email_check/README.rst
  partner_email_check/__init__.py
  partner_email_check/__manifest__.py
  partner_email_check/demo/res_company_demo.xml
  partner_email_check/i18n/es.po
  partner_email_check/i18n/fr.po
  partner_email_check/i18n/it.po
  partner_email_check/i18n/partner_email_check.pot
  partner_email_check/models/__init__.py
  partner_email_check/models/res_company.py
  partner_email_check/models/res_config_settings.py
  partner_email_check/models/res_partner.py
  partner_email_check/pyproject.toml
  partner_email_check/readme/CONFIGURE.md
  partner_email_check/readme/CONTRIBUTORS.md
  partner_email_check/readme/DESCRIPTION.md
  partner_email_check/readme/USAGE.md
  partner_email_check/static/description/icon.png
  partner_email_check/static/description/index.html
  partner_email_check/tests/__init__.py
  partner_email_check/tests/test_partner_email_check.py
  partner_email_check/views/base_config_view.xml
  requirements.txt
Labels: bot is merging ⏳

#1730 [17.0][MIG] crm_partner_company_group: Migration to 17.0
  crm_partner_company_group/README.rst
  crm_partner_company_group/__init__.py
  crm_partner_company_group/__manifest__.py
  crm_partner_company_group/hooks.py
  crm_partner_company_group/i18n/crm_partner_company_group.pot
  crm_partner_company_group/i18n/es.po
  crm_partner_company_group/i18n/it.po
  crm_partner_company_group/i18n/pt_BR.po
  crm_partner_company_group/i18n/zh_CN.po
  crm_partner_company_group/models/__init__.py
  crm_partner_company_group/models/crm_lead.py
  crm_partner_company_group/pyproject.toml
  crm_partner_company_group/readme/CONTRIBUTORS.md
  crm_partner_company_group/readme/DESCRIPTION.md
  crm_partner_company_group/static/description/icon.png
  crm_partner_company_group/static/description/index.html
  crm_partner_company_group/views/opportunity_view.xml
Labels: approved, bot is merging ⏳

#1753 [17.0][MIG] account_partner_company_group: Migration to 17.0
  account_partner_company_group/README.rst
  account_partner_company_group/__init__.py
  account_partner_company_group/__manifest__.py
  account_partner_company_group/hooks.py
  account_partner_company_group/i18n/account_partner_company_group.pot
  account_partner_company_group/i18n/es.po
  account_partner_company_group/i18n/it.po
  account_partner_company_group/i18n/partner_company_group.pot
  account_partner_company_group/i18n/pt_BR.po
  account_partner_company_group/i18n/zh_CN.po
  account_partner_company_group/models/__init__.py
  account_partner_company_group/models/account_move.py
  account_partner_company_group/pyproject.toml
  account_partner_company_group/readme/CONTRIBUTORS.md
  account_partner_company_group/readme/DESCRIPTION.md
  account_partner_company_group/static/description/icon.png
  account_partner_company_group/static/description/index.html
  account_partner_company_group/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#1727 [17.0][MIG] sale_partner_company_group: Migration to 17.0
  sale_partner_company_group/README.rst
  sale_partner_company_group/__init__.py
  sale_partner_company_group/__manifest__.py
  sale_partner_company_group/hooks.py
  sale_partner_company_group/i18n/es.po
  sale_partner_company_group/i18n/it.po
  sale_partner_company_group/i18n/pt_BR.po
  sale_partner_company_group/i18n/sale_partner_company_group.pot
  sale_partner_company_group/i18n/zh_CN.po
  sale_partner_company_group/models/__init__.py
  sale_partner_company_group/models/res_partner.py
  sale_partner_company_group/models/sale_order.py
  sale_partner_company_group/pyproject.toml
  sale_partner_company_group/readme/CONTRIBUTORS.md
  sale_partner_company_group/readme/DESCRIPTION.md
  sale_partner_company_group/static/description/icon.png
  sale_partner_company_group/static/description/index.html
  sale_partner_company_group/tests/__init__.py
  sale_partner_company_group/tests/test_sale_partner_company_group.py
  sale_partner_company_group/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#1765 [16.0][IMP] partner_deduplicate_acl: Test compatibility with website.visitor records
  partner_deduplicate_acl/tests/test_partner_deduplicate_acl.py
Labels: bot is merging ⏳

#1731 [17.0][MIG] partner_company_group: Migration to 17.0
  partner_company_group/README.rst
  partner_company_group/__init__.py
  partner_company_group/__manifest__.py
  partner_company_group/i18n/ca.po
  partner_company_group/i18n/es.po
  partner_company_group/i18n/it.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/i18n/pt_BR.po
  partner_company_group/i18n/zh_CN.po
  partner_company_group/pyproject.toml
  partner_company_group/readme/CONTRIBUTORS.md
  partner_company_group/readme/DESCRIPTION.md
  partner_company_group/static/description/icon.png
  partner_company_group/static/description/index.html
  partner_company_group/views/account_move_views.xml
  partner_company_group/views/contact_view.xml
  partner_company_group/views/opportunity_view.xml
  partner_company_group/views/sale_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1772 [15.0][ADD] partner_readonly_security: New module
  partner_readonly_security/README.rst
  partner_readonly_security/__init__.py
  partner_readonly_security/__manifest__.py
  partner_readonly_security/i18n/es.po
  partner_readonly_security/i18n/partner_readonly_security.pot
  partner_readonly_security/models/__init__.py
  partner_readonly_security/models/res_partner.py
  partner_readonly_security/readme/CONTEXT.rst
  partner_readonly_security/readme/CONTRIBUTORS.rst
  partner_readonly_security/readme/DESCRIPTION.rst
  partner_readonly_security/readme/USAGE.rst
  partner_readonly_security/security/partner_readonly_security_security.xml
  partner_readonly_security/static/description/icon.png
  partner_readonly_security/static/description/index.html
  partner_readonly_security/tests/__init__.py
  partner_readonly_security/tests/test_partner_readonly_security.py
  setup/partner_readonly_security/odoo/addons/partner_readonly_security
  setup/partner_readonly_security/setup.py
Labels: approved, bot is merging ⏳
