Repository OCA/partner-contact, pull requests merged in 2024-02, with the labels that each got.

#1663 [14.0] [ADD] partner_sequence_address_type
  partner_sequence_address_type/README.rst
  partner_sequence_address_type/__init__.py
  partner_sequence_address_type/__manifest__.py
  partner_sequence_address_type/hooks.py
  partner_sequence_address_type/models/__init__.py
  partner_sequence_address_type/models/res_partner.py
  partner_sequence_address_type/models/res_partner_sequence_type.py
  partner_sequence_address_type/readme/CONTRIBUTORS.rst
  partner_sequence_address_type/readme/DESCRIPTION.rst
  partner_sequence_address_type/readme/USAGE.rst
  partner_sequence_address_type/security/ir.model.access.csv
  partner_sequence_address_type/static/description/index.html
  partner_sequence_address_type/views/ir_sequence_views.xml
  partner_sequence_address_type/views/res_partner_views.xml
  setup/partner_sequence_address_type/odoo/addons/partner_sequence_address_type
  setup/partner_sequence_address_type/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1673 [16.0] [IMP] partner_industry_secondary: add unaccent=False on parent_path field
  partner_industry_secondary/models/res_partner_industry.py
Labels: bot is merging ⏳

#1635 [16.0][FIX] partner_multi_relation: fix name_get and name_search
  partner_multi_relation/models/res_partner_relation_all.py
Labels: approved, bot is merging ⏳

#1568 [13.0][FIX] company_default_partner_pricelist
  company_default_partner_pricelist/__manifest__.py
  company_default_partner_pricelist/migrations/13.0.1.0.1/post-migration.py
  company_default_partner_pricelist/models/__init__.py
  company_default_partner_pricelist/models/product_pricelist.py
  company_default_partner_pricelist/models/res_company.py
  company_default_partner_pricelist/tests/test_company_default_partner_pricelist.py
Labels: approved, bot is merging ⏳

#1553 [14.0] backport partner_bank_acc_type_constraint from 16 to 14
  partner_bank_acc_type_constraint/README.rst
  partner_bank_acc_type_constraint/__init__.py
  partner_bank_acc_type_constraint/__manifest__.py
  partner_bank_acc_type_constraint/i18n/fr.po
  partner_bank_acc_type_constraint/i18n/partner_bank_acc_type_constraint.pot
  partner_bank_acc_type_constraint/models/__init__.py
  partner_bank_acc_type_constraint/models/res_partner_bank.py
  partner_bank_acc_type_constraint/post_install.py
  partner_bank_acc_type_constraint/readme/CONTRIBUTORS.rst
  partner_bank_acc_type_constraint/readme/DESCRIPTION.rst
  partner_bank_acc_type_constraint/static/description/icon.png
  partner_bank_acc_type_constraint/static/description/index.html
  partner_bank_acc_type_constraint/static/description/partner_bank_acc_type_raise.png
  partner_bank_acc_type_constraint/views/res_partner.xml
  partner_bank_acc_type_constraint/views/res_partner_bank.xml
  setup/partner_bank_acc_type_constraint/odoo/addons/partner_bank_acc_type_constraint
  setup/partner_bank_acc_type_constraint/setup.py
Labels: needs review, approved, bot is merging ⏳

#1668 [16.0][ADD] partner_auto_archive
  partner_auto_archive/README.rst
  partner_auto_archive/__init__.py
  partner_auto_archive/__manifest__.py
  partner_auto_archive/data/ir_cron.xml
  partner_auto_archive/models/__init__.py
  partner_auto_archive/models/res_partner.py
  partner_auto_archive/readme/CONTRIBUTORS.rst
  partner_auto_archive/readme/DESCRIPTION.rst
  partner_auto_archive/readme/USAGE.rst
  partner_auto_archive/static/description/index.html
  partner_auto_archive/tests/__init__.py
  partner_auto_archive/tests/test_partner_auto_archive.py
  partner_auto_archive/views/res_partner_views.xml
  setup/partner_auto_archive/odoo/addons/partner_auto_archive
  setup/partner_auto_archive/setup.py
Labels: approved, bot is merging ⏳

#1671 [16.0][FIX] partner_tier_validation: Change invalidate_cache() to invalidate_recordset()
  partner_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#1670 [16.0][FIX] partner_contact_department: Change SavepointCase to TransactionCase
  partner_contact_department/models/res_partner.py
  partner_contact_department/tests/test_recursion.py
Labels: bot is merging ⏳

#1669 [16.0][MIG] partner_category_security: Migration to 16.0
  partner_category_security/README.rst
  partner_category_security/__init__.py
  partner_category_security/__manifest__.py
  partner_category_security/i18n/es.po
  partner_category_security/i18n/it.po
  partner_category_security/i18n/partner_category_security.pot
  partner_category_security/models/__init__.py
  partner_category_security/models/res_partner.py
  partner_category_security/readme/CONTRIBUTORS.rst
  partner_category_security/readme/DESCRIPTION.rst
  partner_category_security/readme/USAGE.rst
  partner_category_security/security/ir.model.access.csv
  partner_category_security/security/security.xml
  partner_category_security/static/description/icon.png
  partner_category_security/static/description/index.html
  partner_category_security/tests/__init__.py
  partner_category_security/tests/test_partner_category_security.py
  partner_category_security/views/menu.xml
  setup/partner_category_security/odoo/addons/partner_category_security
  setup/partner_category_security/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1676 [16.0][MIG] partner_category_security_crm: Migration to 16.0
  partner_category_security_crm/README.rst
  partner_category_security_crm/__init__.py
  partner_category_security_crm/__manifest__.py
  partner_category_security_crm/i18n/es.po
  partner_category_security_crm/i18n/it.po
  partner_category_security_crm/i18n/partner_category_security_crm.pot
  partner_category_security_crm/readme/CONTRIBUTORS.rst
  partner_category_security_crm/readme/DESCRIPTION.rst
  partner_category_security_crm/readme/USAGE.rst
  partner_category_security_crm/security/ir.model.access.csv
  partner_category_security_crm/static/description/icon.png
  partner_category_security_crm/static/description/index.html
  partner_category_security_crm/tests/__init__.py
  partner_category_security_crm/tests/test_partner_category_security_crm.py
  setup/partner_category_security_crm/odoo/addons/partner_category_security_crm
  setup/partner_category_security_crm/setup.py
Labels: approved, bot is merging ⏳
