Repository OCA/partner-contact, pull requests merged in 2024-10, with the labels that each got.

#1864 [17.0][MIG] partner_property: Migration to version 17.0
  partner_property/README.rst
  partner_property/__init__.py
  partner_property/__manifest__.py
  partner_property/i18n/es.po
  partner_property/i18n/it.po
  partner_property/i18n/partner_property.pot
  partner_property/models/__init__.py
  partner_property/models/res_company.py
  partner_property/models/res_partner.py
  partner_property/pyproject.toml
  partner_property/readme/CONTRIBUTORS.md
  partner_property/readme/DESCRIPTION.md
  partner_property/readme/ROADMAP.md
  partner_property/readme/USAGE.md
  partner_property/static/description/icon.png
  partner_property/static/description/index.html
  partner_property/tests/__init__.py
  partner_property/tests/test_res_partner.py
  partner_property/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#1861 [18.0][MIG] partner_tz: Migration to 18.0
  partner_tz/README.rst
  partner_tz/__init__.py
  partner_tz/__manifest__.py
  partner_tz/i18n/it.po
  partner_tz/i18n/partner_tz.pot
  partner_tz/pyproject.toml
  partner_tz/readme/CONTRIBUTORS.md
  partner_tz/readme/CREDITS.md
  partner_tz/readme/DESCRIPTION.md
  partner_tz/readme/ROADMAP.md
  partner_tz/static/description/icon.png
  partner_tz/static/description/index.html
  partner_tz/tests/__init__.py
  partner_tz/tests/common.py
  partner_tz/tests/test_tz.py
  partner_tz/tools/__init__.py
  partner_tz/tools/tz_utils.py
  partner_tz/views/res_partner.xml
Labels: approved, migration, bot is merging ⏳

#1851 [17.0] [IMP] partner_contact_gender: improve readme and icon
  partner_contact_gender/readme/DESCRIPTION.md
  partner_contact_gender/readme/USAGE.md
  partner_contact_gender/static/description/icon.png
  partner_contact_gender/static/description/icon.svg
Labels: approved, ready to merge, bot is merging ⏳

#1866 [18.0][MIG] partner_pricelist_search: Migration to 18.0
  partner_pricelist_search/README.rst
  partner_pricelist_search/__init__.py
  partner_pricelist_search/__manifest__.py
  partner_pricelist_search/i18n/es.po
  partner_pricelist_search/i18n/it.po
  partner_pricelist_search/i18n/partner_pricelist_search.pot
  partner_pricelist_search/models/__init__.py
  partner_pricelist_search/models/product_pricelist.py
  partner_pricelist_search/models/res_partner.py
  partner_pricelist_search/pyproject.toml
  partner_pricelist_search/readme/CONTRIBUTORS.md
  partner_pricelist_search/readme/CREDITS.md
  partner_pricelist_search/readme/DESCRIPTION.md
  partner_pricelist_search/readme/ROADMAP.md
  partner_pricelist_search/static/description/icon.png
  partner_pricelist_search/static/description/index.html
  partner_pricelist_search/tests/__init__.py
  partner_pricelist_search/tests/test_partner_pricelist_search.py
  partner_pricelist_search/views/product_pricelist_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1871 [18.0][MIG] base_partner_company_group: Migration to 18.0
  base_partner_company_group/README.rst
  base_partner_company_group/__init__.py
  base_partner_company_group/__manifest__.py
  base_partner_company_group/i18n/base_partner_company_group.pot
  base_partner_company_group/i18n/ca.po
  base_partner_company_group/i18n/es.po
  base_partner_company_group/i18n/fr.po
  base_partner_company_group/i18n/fr_FR.po
  base_partner_company_group/i18n/hr.po
  base_partner_company_group/i18n/it.po
  base_partner_company_group/i18n/partner_company_group.pot
  base_partner_company_group/i18n/pt_BR.po
  base_partner_company_group/i18n/zh_CN.po
  base_partner_company_group/models/__init__.py
  base_partner_company_group/models/res_partner.py
  base_partner_company_group/pyproject.toml
  base_partner_company_group/readme/CONTRIBUTORS.md
  base_partner_company_group/readme/CREDITS.md
  base_partner_company_group/readme/DESCRIPTION.md
  base_partner_company_group/static/description/icon.png
  base_partner_company_group/static/description/index.html
  base_partner_company_group/tests/__init__.py
  base_partner_company_group/tests/test_base_partner_company_group.py
  base_partner_company_group/views/contact_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1876 [17.0][MIG] partner_company_default
  partner_company_default/README.rst
  partner_company_default/__init__.py
  partner_company_default/__manifest__.py
  partner_company_default/i18n/it.po
  partner_company_default/i18n/partner_company_default.pot
  partner_company_default/models/__init__.py
  partner_company_default/models/res_company.py
  partner_company_default/models/res_partner.py
  partner_company_default/pyproject.toml
  partner_company_default/readme/CONTEXT.md
  partner_company_default/readme/DESCRIPTION.md
  partner_company_default/static/description/icon.png
  partner_company_default/static/description/index.html
  partner_company_default/tests/__init__.py
  partner_company_default/tests/test_partner_company_default.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1881 [17.0][MIG] partner_category_security: Migration to version 17.0
  partner_category_security/README.rst
  partner_category_security/__init__.py
  partner_category_security/__manifest__.py
  partner_category_security/i18n/es.po
  partner_category_security/i18n/it.po
  partner_category_security/i18n/partner_category_security.pot
  partner_category_security/models/__init__.py
  partner_category_security/models/ir_ui_menu.py
  partner_category_security/models/res_partner.py
  partner_category_security/pyproject.toml
  partner_category_security/readme/CONTRIBUTORS.md
  partner_category_security/readme/DESCRIPTION.md
  partner_category_security/readme/USAGE.md
  partner_category_security/security/ir.model.access.csv
  partner_category_security/security/security.xml
  partner_category_security/static/description/icon.png
  partner_category_security/static/description/index.html
  partner_category_security/tests/__init__.py
  partner_category_security/tests/test_partner_category_security.py
  partner_category_security/views/menu.xml
Labels: approved, bot is merging ⏳

#1859 [18.0][MIG] partner_identification_unique_by_category: Migration to 18.0
  partner_identification_unique_by_category/README.rst
  partner_identification_unique_by_category/__init__.py
  partner_identification_unique_by_category/__manifest__.py
  partner_identification_unique_by_category/i18n/es.po
  partner_identification_unique_by_category/i18n/it.po
  partner_identification_unique_by_category/i18n/partner_identification_unique_by_category.pot
  partner_identification_unique_by_category/models/__init__.py
  partner_identification_unique_by_category/models/res_partner_id_category.py
  partner_identification_unique_by_category/models/res_partner_id_number.py
  partner_identification_unique_by_category/pyproject.toml
  partner_identification_unique_by_category/readme/CONTRIBUTORS.md
  partner_identification_unique_by_category/readme/CREDITS.md
  partner_identification_unique_by_category/readme/DESCRIPTION.md
  partner_identification_unique_by_category/static/description/icon.png
  partner_identification_unique_by_category/static/description/index.html
  partner_identification_unique_by_category/tests/__init__.py
  partner_identification_unique_by_category/tests/test_partner_identification_unique_by_category.py
  partner_identification_unique_by_category/views/res_partner_id_category_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
