Repository OCA/partner-contact, pull requests merged in 2024-09, with the labels that each got.

#1838 [16.0][FIX] partner_contact_address_default: Tidy up view
  partner_contact_address_default/views/res_partner_views.xml
Labels: bot is merging ⏳

#1736 [16.0][MIG] animal
  animal/README.rst
  animal/__init__.py
  animal/__manifest__.py
  animal/data/animal.breed.csv
  animal/data/animal.color.csv
  animal/data/animal.species.csv
  animal/data/ir.module.category.csv
  animal/i18n/animal.pot
  animal/i18n/ca.po
  animal/i18n/es.po
  animal/models/__init__.py
  animal/models/animal.py
  animal/models/animal_breed.py
  animal/models/animal_color.py
  animal/models/animal_species.py
  animal/readme/CONTRIBUTORS.rst
  animal/readme/DESCRIPTION.rst
  animal/readme/USAGE.rst
  animal/security/ir.model.access.csv
  animal/security/res_groups.xml
  animal/static/description/icon.png
  animal/static/description/index.html
  animal/static/img/avatar.png
  animal/tests/__init__.py
  animal/tests/test_animal.py
  animal/views/animal.xml
  animal/views/animal_breed.xml
  animal/views/animal_color.xml
  animal/views/animal_species.xml
  animal/views/menu.xml
  setup/animal/odoo/addons/animal
  setup/animal/setup.py
Labels: approved, bot is merging ⏳

#1799 [16.0][Feat] Added store location type contact
  partner_store/README.rst
  partner_store/__init__.py
  partner_store/__manifest__.py
  partner_store/models/__init__.py
  partner_store/models/res_partner.py
  partner_store/readme/CONFIGURATION.rst
  partner_store/readme/CONTRIBUTORS.rst
  partner_store/readme/DESCRIPTION.rst
  partner_store/readme/USAGE.rst
  partner_store/static/description/icon.png
  partner_store/static/img/store.png
  partner_store/tests/__init__.py
  partner_store/tests/test_res_partner.py
  setup/partner_store/odoo/addons/partner_store
  setup/partner_store/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1790 [14.0] partner_helper: add strict mode that raise an error if address is too long
  partner_helper/models/partner.py
  partner_helper/tests/test_split_address.py
Labels: approved, bot is merging ⏳
