Repository OCA/partner-contact, pull requests merged in 2024-12, with the labels that each got.

#1874 [18.0][MIG] sale_partner_company_group: Migration to 18.0
  .oca/oca-port/blacklist/sale_partner_company_group.json
  sale_partner_company_group/README.rst
  sale_partner_company_group/__init__.py
  sale_partner_company_group/__manifest__.py
  sale_partner_company_group/hooks.py
  sale_partner_company_group/i18n/es.po
  sale_partner_company_group/i18n/it.po
  sale_partner_company_group/i18n/pt_BR.po
  sale_partner_company_group/i18n/sale_partner_company_group.pot
  sale_partner_company_group/i18n/zh_CN.po
  sale_partner_company_group/models/__init__.py
  sale_partner_company_group/models/res_partner.py
  sale_partner_company_group/models/sale_order.py
  sale_partner_company_group/pyproject.toml
  sale_partner_company_group/readme/CONTRIBUTORS.md
  sale_partner_company_group/readme/CREDITS.md
  sale_partner_company_group/readme/DESCRIPTION.md
  sale_partner_company_group/static/description/icon.png
  sale_partner_company_group/static/description/index.html
  sale_partner_company_group/tests/__init__.py
  sale_partner_company_group/tests/test_sale_partner_company_group.py
  sale_partner_company_group/views/sale_order_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1873 [18.0][MIG] crm_partner_company_group: Migration to 18.0
  .oca/oca-port/blacklist/crm_partner_company_group.json
  crm_partner_company_group/README.rst
  crm_partner_company_group/__init__.py
  crm_partner_company_group/__manifest__.py
  crm_partner_company_group/i18n/crm_partner_company_group.pot
  crm_partner_company_group/i18n/es.po
  crm_partner_company_group/i18n/it.po
  crm_partner_company_group/i18n/pt_BR.po
  crm_partner_company_group/i18n/zh_CN.po
  crm_partner_company_group/models/__init__.py
  crm_partner_company_group/models/crm_lead.py
  crm_partner_company_group/pyproject.toml
  crm_partner_company_group/readme/CONTRIBUTORS.md
  crm_partner_company_group/readme/CREDITS.md
  crm_partner_company_group/readme/DESCRIPTION.md
  crm_partner_company_group/static/description/icon.png
  crm_partner_company_group/static/description/index.html
  crm_partner_company_group/views/opportunity_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1911 [16.0][FIX] base_location_geonames_import: Fixes for re-imports
  base_location_geonames_import/wizard/geonames_import.py
Labels: approved, bot is merging ⏳

#1870 [18.0][MIG] partner_company_group: Migration to 18.0
  .oca/oca-port/blacklist/partner_company_group.json
  partner_company_group/README.rst
  partner_company_group/__init__.py
  partner_company_group/__manifest__.py
  partner_company_group/i18n/ca.po
  partner_company_group/i18n/es.po
  partner_company_group/i18n/it.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/i18n/pt_BR.po
  partner_company_group/i18n/zh_CN.po
  partner_company_group/pyproject.toml
  partner_company_group/readme/CONTRIBUTORS.md
  partner_company_group/readme/CREDITS.md
  partner_company_group/readme/DESCRIPTION.md
  partner_company_group/static/description/icon.png
  partner_company_group/static/description/index.html
  partner_company_group/views/account_move_views.xml
  partner_company_group/views/contact_view.xml
  partner_company_group/views/opportunity_view.xml
  partner_company_group/views/sale_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1927 [18.0][FW] [14.0][ADD] index on partner_company_group
  base_partner_company_group/models/res_partner.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1935 [18.0][MIG] partner_identification_gln
  partner_identification/models/res_partner_id_category.py
  partner_identification_gln/README.rst
  partner_identification_gln/__init__.py
  partner_identification_gln/__manifest__.py
  partner_identification_gln/data/partner_identification_gln.xml
  partner_identification_gln/i18n/es.po
  partner_identification_gln/i18n/it.po
  partner_identification_gln/i18n/partner_identification_gln.pot
  partner_identification_gln/i18n/sl.po
  partner_identification_gln/models/__init__.py
  partner_identification_gln/models/res_partner_id_category.py
  partner_identification_gln/pyproject.toml
  partner_identification_gln/readme/CONTRIBUTORS.md
  partner_identification_gln/readme/CREDITS.md
  partner_identification_gln/readme/DESCRIPTION.md
  partner_identification_gln/readme/INSTALL.md
  partner_identification_gln/static/description/icon.svg
  partner_identification_gln/static/description/index.html
  partner_identification_gln/tests/__init__.py
  partner_identification_gln/tests/test_gln.py
Labels: approved, bot is merging ⏳

#1924 [17.0][IMP] Add birthdate in search view
  partner_contact_birthdate/views/res_partner.xml
Labels: enhancement, needs review, bot is merging ⏳

#1900 [18.0] [MIG] partner_contact_personal_information_page: Migration to 18.0
  partner_contact_personal_information_page/README.rst
  partner_contact_personal_information_page/__init__.py
  partner_contact_personal_information_page/__manifest__.py
  partner_contact_personal_information_page/i18n/ca.po
  partner_contact_personal_information_page/i18n/da.po
  partner_contact_personal_information_page/i18n/de.po
  partner_contact_personal_information_page/i18n/es.po
  partner_contact_personal_information_page/i18n/fi.po
  partner_contact_personal_information_page/i18n/fr.po
  partner_contact_personal_information_page/i18n/hr.po
  partner_contact_personal_information_page/i18n/hr_HR.po
  partner_contact_personal_information_page/i18n/hu.po
  partner_contact_personal_information_page/i18n/it.po
  partner_contact_personal_information_page/i18n/nl.po
  partner_contact_personal_information_page/i18n/partner_contact_personal_information_page.pot
  partner_contact_personal_information_page/i18n/pt.po
  partner_contact_personal_information_page/i18n/pt_BR.po
  partner_contact_personal_information_page/i18n/pt_PT.po
  partner_contact_personal_information_page/i18n/sl.po
  partner_contact_personal_information_page/pyproject.toml
  partner_contact_personal_information_page/readme/CONTRIBUTORS.md
  partner_contact_personal_information_page/readme/DESCRIPTION.md
  partner_contact_personal_information_page/readme/USAGE.md
  partner_contact_personal_information_page/static/description/icon.png
  partner_contact_personal_information_page/static/description/index.html
  partner_contact_personal_information_page/views/res_partner.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1923 [18.0][MIG] partner_fax: Migration to 18.0
  partner_fax/README.rst
  partner_fax/__init__.py
  partner_fax/__manifest__.py
  partner_fax/i18n/ca.po
  partner_fax/i18n/de.po
  partner_fax/i18n/es.po
  partner_fax/i18n/fr.po
  partner_fax/i18n/he.po
  partner_fax/i18n/hr_HR.po
  partner_fax/i18n/it.po
  partner_fax/i18n/nl.po
  partner_fax/i18n/partner_fax.pot
  partner_fax/i18n/pt_BR.po
  partner_fax/i18n/sl.po
  partner_fax/i18n/zh_CN.po
  partner_fax/models/__init__.py
  partner_fax/models/res_partner.py
  partner_fax/pyproject.toml
  partner_fax/readme/CONTRIBUTORS.md
  partner_fax/readme/DESCRIPTION.md
  partner_fax/readme/USAGE.md
  partner_fax/static/description/icon.png
  partner_fax/static/description/index.html
  partner_fax/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#1740 [16.0][FIX] partner_multi_relation: fix name search on relation
  partner_multi_relation/models/res_partner_relation_all.py
Labels: bot is merging ⏳, stale
