Repository OCA/partner-contact, pull requests merged in 2024-11, with the labels that each got.

#1882 [17.0][FIX] partner_display_name_line_break: Do not split with empty name
  partner_display_name_line_break/models/res_partner.py
  partner_display_name_line_break/tests/test_res_partner.py
Labels: approved, ready to merge, bot is merging ⏳

#1887 [FIX] [16.0] partner_contact_access_link: Hide icon when contact is not saved
  partner_contact_access_link/views/res_partner_views.xml
Labels: needs review, approved, bot is merging ⏳

#1893 [17.0][FIX] partner_firstname: Wrong contact type
  partner_firstname/views/res_partner.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳
