Repository OCA/partner-contact, pull requests merged in 2024-07, with the labels that each got.

#1794 [17.0][FIX] partner_firstname : bug "create and edit" from invoice and sale order
  partner_firstname/models/res_partner.py
Labels: approved, ready to merge, bot is merging ⏳

#1811 [16.0][IMP] partner_property: Define different properties for Individiaul or Company partners
  partner_property/README.rst
  partner_property/__manifest__.py
  partner_property/migrations/16.0.1.1.0/pre-migration.py
  partner_property/models/res_company.py
  partner_property/models/res_partner.py
  partner_property/readme/DESCRIPTION.rst
  partner_property/readme/USAGE.rst
  partner_property/static/description/index.html
  partner_property/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#1805 [17.0] [MIG] partner_deduplicate_acl
  partner_deduplicate_acl/README.rst
  partner_deduplicate_acl/__init__.py
  partner_deduplicate_acl/__manifest__.py
  partner_deduplicate_acl/i18n/de.po
  partner_deduplicate_acl/i18n/es.po
  partner_deduplicate_acl/i18n/fr.po
  partner_deduplicate_acl/i18n/hr.po
  partner_deduplicate_acl/i18n/it.po
  partner_deduplicate_acl/i18n/nl_NL.po
  partner_deduplicate_acl/i18n/partner_deduplicate_acl.pot
  partner_deduplicate_acl/i18n/pt_BR.po
  partner_deduplicate_acl/i18n/sk.po
  partner_deduplicate_acl/i18n/sl.po
  partner_deduplicate_acl/i18n/tr.po
  partner_deduplicate_acl/i18n/zh_CN.po
  partner_deduplicate_acl/images/perms.png
  partner_deduplicate_acl/pyproject.toml
  partner_deduplicate_acl/readme/CONFIGURE.md
  partner_deduplicate_acl/readme/CONTRIBUTORS.md
  partner_deduplicate_acl/readme/DESCRIPTION.md
  partner_deduplicate_acl/readme/USAGE.md
  partner_deduplicate_acl/security/ir.model.access.csv
  partner_deduplicate_acl/security/partner_deduplicate_acl_security.xml
  partner_deduplicate_acl/static/description/icon.png
  partner_deduplicate_acl/static/description/icon.svg
  partner_deduplicate_acl/static/description/index.html
  partner_deduplicate_acl/tests/__init__.py
  partner_deduplicate_acl/tests/test_partner_deduplicate_acl.py
  partner_deduplicate_acl/views/base_partner_merge_view.xml
  partner_deduplicate_acl/wizards/__init__.py
  partner_deduplicate_acl/wizards/partner_merge.py
  partner_deduplicate_acl/wizards/partner_merge_view.xml
Labels: bot is merging ⏳

#1806 [17.0][MIG] partner_deduplicate_filter: Migration to 17.0
  partner_deduplicate_filter/README.rst
  partner_deduplicate_filter/__init__.py
  partner_deduplicate_filter/__manifest__.py
  partner_deduplicate_filter/i18n/crm_deduplicate_filter.pot
  partner_deduplicate_filter/i18n/de.po
  partner_deduplicate_filter/i18n/es.po
  partner_deduplicate_filter/i18n/hr.po
  partner_deduplicate_filter/i18n/it.po
  partner_deduplicate_filter/i18n/nl_NL.po
  partner_deduplicate_filter/i18n/partner_deduplicate_filter.pot
  partner_deduplicate_filter/i18n/sk.po
  partner_deduplicate_filter/i18n/sl.po
  partner_deduplicate_filter/i18n/tr.po
  partner_deduplicate_filter/pyproject.toml
  partner_deduplicate_filter/readme/CONTRIBUTORS.md
  partner_deduplicate_filter/readme/DESCRIPTION.md
  partner_deduplicate_filter/readme/USAGE.md
  partner_deduplicate_filter/static/description/icon.png
  partner_deduplicate_filter/static/description/icon.svg
  partner_deduplicate_filter/static/description/index.html
  partner_deduplicate_filter/tests/__init__.py
  partner_deduplicate_filter/tests/test_partner_deduplicate_filter.py
  partner_deduplicate_filter/wizards/__init__.py
  partner_deduplicate_filter/wizards/partner_merge.py
  partner_deduplicate_filter/wizards/partner_merge_view.xml
Labels: approved, bot is merging ⏳

#1815 [16.0][FIX] base_location_nuts: Modified field definition
  base_location_nuts/models/res_partner_nuts.py
Labels: bot is merging ⏳

#1623 [17.0][MIG] partner_identification_gln: Migration to 17.0
  partner_identification_gln/README.rst
  partner_identification_gln/__init__.py
  partner_identification_gln/__manifest__.py
  partner_identification_gln/data/partner_identification_gln.xml
  partner_identification_gln/i18n/es.po
  partner_identification_gln/i18n/partner_identification_gln.pot
  partner_identification_gln/i18n/sl.po
  partner_identification_gln/models/__init__.py
  partner_identification_gln/models/res_partner_id_category.py
  partner_identification_gln/pyproject.toml
  partner_identification_gln/readme/CONTRIBUTORS.md
  partner_identification_gln/readme/CREDITS.md
  partner_identification_gln/readme/DESCRIPTION.md
  partner_identification_gln/readme/INSTALL.md
  partner_identification_gln/static/description/icon.svg
  partner_identification_gln/static/description/index.html
  partner_identification_gln/tests/__init__.py
  partner_identification_gln/tests/test_gln.py
Labels: approved, ready to merge, bot is merging ⏳

#1734 [16.0][MIG] partner_contact_birthplace
  partner_contact_birthplace/README.rst
  partner_contact_birthplace/__init__.py
  partner_contact_birthplace/__manifest__.py
  partner_contact_birthplace/i18n/ca.po
  partner_contact_birthplace/i18n/es.po
  partner_contact_birthplace/i18n/es_ES.po
  partner_contact_birthplace/i18n/it.po
  partner_contact_birthplace/i18n/partner_contact_birthplace.pot
  partner_contact_birthplace/models/__init__.py
  partner_contact_birthplace/models/res_partner.py
  partner_contact_birthplace/readme/CONFIGURE.rst
  partner_contact_birthplace/readme/CONTRIBUTORS.rst
  partner_contact_birthplace/readme/DESCRIPTION.rst
  partner_contact_birthplace/readme/INSTALLATION.rst
  partner_contact_birthplace/readme/USAGE.rst
  partner_contact_birthplace/static/description/icon.png
  partner_contact_birthplace/static/description/index.html
  partner_contact_birthplace/views/res_partner.xml
  setup/partner_contact_birthplace/odoo/addons/partner_contact_birthplace
  setup/partner_contact_birthplace/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1825 [16.0][ADD] Description field in contact's tag
  partner_category_description/README.rst
  partner_category_description/__init__.py
  partner_category_description/__manifest__.py
  partner_category_description/i18n/es.po
  partner_category_description/i18n/partner_category_description.pot
  partner_category_description/models/__init__.py
  partner_category_description/models/res_partner_category.py
  partner_category_description/readme/CONTRIBUTORS.md
  partner_category_description/readme/DESCRIPTION.md
  partner_category_description/readme/USAGE.md
  partner_category_description/static/description/icon.png
  partner_category_description/static/description/index.html
  partner_category_description/views/res_partner_category_views.xml
  setup/partner_category_description/odoo/addons/partner_category_description
  setup/partner_category_description/setup.py
Labels: bot is merging ⏳

#1827 [16.0][FIX] partner_category_description - fix license
  partner_category_description/README.rst
  partner_category_description/__manifest__.py
  partner_category_description/models/res_partner_category.py
  partner_category_description/static/description/index.html
  partner_category_description/views/res_partner_category_views.xml
Labels: approved, bot is merging ⏳

#1489 [16.0][ADD] partner_contact_tags_in_popup
  partner_contact_tags_in_popup/README.rst
  partner_contact_tags_in_popup/__init__.py
  partner_contact_tags_in_popup/__manifest__.py
  partner_contact_tags_in_popup/readme/CONTRIBUTORS.rst
  partner_contact_tags_in_popup/readme/DESCRIPTION.rst
  partner_contact_tags_in_popup/static/description/index.html
  partner_contact_tags_in_popup/views/res_partner_views.xml
  setup/partner_contact_tags_in_popup/odoo/addons/partner_contact_tags_in_popup
  setup/partner_contact_tags_in_popup/setup.py
Labels: approved, bot is merging ⏳, stale
