Repository OCA/partner-contact, pull requests merged in 2024-06, with the labels that each got.

#1585 [16.0][MIG] partner_duns
  partner_duns/README.rst
  partner_duns/__init__.py
  partner_duns/__manifest__.py
  partner_duns/i18n/partner_duns.pot
  partner_duns/models/__init__.py
  partner_duns/models/res_partner.py
  partner_duns/readme/CONTRIBUTORS.rst
  partner_duns/readme/DESCRIPTION.rst
  partner_duns/static/description/icon.png
  partner_duns/static/description/index.html
  partner_duns/tests/__init__.py
  partner_duns/tests/test_partner_duns.py
  partner_duns/views/res_partner.xml
  setup/partner_duns/odoo/addons/partner_duns
  setup/partner_duns/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1774 [17.0][MIG] partner_address_split: Migration to 17.0
  partner_address_split/README.rst
  partner_address_split/__init__.py
  partner_address_split/__manifest__.py
  partner_address_split/models/__init__.py
  partner_address_split/models/partner.py
  partner_address_split/pyproject.toml
  partner_address_split/readme/CONTRIBUTORS.md
  partner_address_split/readme/DESCRIPTION.md
  partner_address_split/static/description/icon.png
  partner_address_split/static/description/index.html
  partner_address_split/tests/__init__.py
  partner_address_split/tests/test_split_address.py
  setup/partner_address_split/odoo/addons/partner_address_split
  setup/partner_address_split/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1789 [17.0][FIX] partner_affiliate: active_id => id
  partner_affiliate/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1767 [17.0][MIG] partner_email_duplicate_warn: Migration to 17.0
  partner_email_duplicate_warn/README.rst
  partner_email_duplicate_warn/__init__.py
  partner_email_duplicate_warn/__manifest__.py
  partner_email_duplicate_warn/i18n/fr.po
  partner_email_duplicate_warn/i18n/hr.po
  partner_email_duplicate_warn/i18n/it.po
  partner_email_duplicate_warn/i18n/partner_email_duplicate_warn.pot
  partner_email_duplicate_warn/models/__init__.py
  partner_email_duplicate_warn/models/res_partner.py
  partner_email_duplicate_warn/pyproject.toml
  partner_email_duplicate_warn/readme/CONFIGURE.md
  partner_email_duplicate_warn/readme/CONTRIBUTORS.md
  partner_email_duplicate_warn/readme/DESCRIPTION.md
  partner_email_duplicate_warn/readme/ROADMAP.md
  partner_email_duplicate_warn/readme/USAGE.md
  partner_email_duplicate_warn/static/description/icon.png
  partner_email_duplicate_warn/static/description/index.html
  partner_email_duplicate_warn/static/description/partner_warn_banner.png
  partner_email_duplicate_warn/tests/__init__.py
  partner_email_duplicate_warn/tests/test_email_duplicate.py
  partner_email_duplicate_warn/views/res_partner.xml
Labels: bot is merging ⏳

#1785 [16.0][ADD] partner_property: New module
  partner_property/README.rst
  partner_property/__init__.py
  partner_property/__manifest__.py
  partner_property/i18n/es.po
  partner_property/i18n/partner_property.pot
  partner_property/models/__init__.py
  partner_property/models/res_company.py
  partner_property/models/res_partner.py
  partner_property/readme/CONTRIBUTORS.rst
  partner_property/readme/DESCRIPTION.rst
  partner_property/readme/ROADMAP.rst
  partner_property/readme/USAGE.rst
  partner_property/static/description/icon.png
  partner_property/static/description/index.html
  partner_property/views/res_partner_views.xml
  setup/partner_property/odoo/addons/partner_property
  setup/partner_property/setup.py
Labels: approved, ready to merge, bot is merging ⏳
