Repository OCA/partner-contact, pull requests merged in 2025-02, with the labels that each got.

#1949 [17.0][IMP] crm_partner_company_group: show company_group_id on list and form view
  crm_partner_company_group/views/opportunity_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1940 [18.0][MIG] partner_disable_gravatar
  partner_disable_gravatar/README.rst
  partner_disable_gravatar/__init__.py
  partner_disable_gravatar/__manifest__.py
  partner_disable_gravatar/i18n/de.po
  partner_disable_gravatar/i18n/fr.po
  partner_disable_gravatar/i18n/it.po
  partner_disable_gravatar/i18n/partner_disable_gravatar.pot
  partner_disable_gravatar/models/__init__.py
  partner_disable_gravatar/models/res_partner.py
  partner_disable_gravatar/pyproject.toml
  partner_disable_gravatar/readme/CONTRIBUTORS.md
  partner_disable_gravatar/readme/DESCRIPTION.md
  partner_disable_gravatar/static/description/icon.png
  partner_disable_gravatar/static/description/index.html
  partner_disable_gravatar/tests/__init__.py
  partner_disable_gravatar/tests/test_partner_disable_gravatar.py
Labels: bot is merging ⏳

#1982 [FIX] partner_contact_job_position: avoid accidental job position creations
  partner_contact_job_position/views/res_partner_view.xml
Labels: bug, needs review, approved, bot is merging ⏳

#1981 [FIX] partner_contact_department: avoid accidental department creations
  partner_contact_department/views/res_partner_view.xml
Labels: bug, needs review, approved, bot is merging ⏳

#1983 [IMP] partner_contact_department: sort by name
  partner_contact_department/models/res_partner.py
Labels: bug, needs review, approved, bot is merging ⏳

#1833 [16.0][ADD] partner_search_alias
  partner_search_alias/README.rst
  partner_search_alias/__init__.py
  partner_search_alias/__manifest__.py
  partner_search_alias/models/__init__.py
  partner_search_alias/models/res_partner.py
  partner_search_alias/readme/DESCRIPTION.rst
  partner_search_alias/static/description/index.html
  partner_search_alias/tests/__init__.py
  partner_search_alias/tests/test_partner_search_alias.py
  partner_search_alias/views/res_partner_views.xml
  setup/partner_search_alias/odoo/addons/partner_search_alias
  setup/partner_search_alias/setup.py
Labels: approved, ready to merge, bot is merging ⏳
