Repository OCA/partner-contact, pull requests merged in 2025-09, with the labels that each got.

#2130 [18.0][MIG] partner_manual_rank : Migration to 18.0.
  partner_manual_rank/README.rst
  partner_manual_rank/__init__.py
  partner_manual_rank/__manifest__.py
  partner_manual_rank/i18n/ca.po
  partner_manual_rank/i18n/ca_ES.po
  partner_manual_rank/i18n/de.po
  partner_manual_rank/i18n/es.po
  partner_manual_rank/i18n/fi.po
  partner_manual_rank/i18n/fr.po
  partner_manual_rank/i18n/it.po
  partner_manual_rank/i18n/partner_manual_rank.pot
  partner_manual_rank/i18n/pt.po
  partner_manual_rank/models/__init__.py
  partner_manual_rank/models/res_partner.py
  partner_manual_rank/pyproject.toml
  partner_manual_rank/readme/CONTRIBUTORS.md
  partner_manual_rank/readme/CREDITS.md
  partner_manual_rank/readme/DESCRIPTION.md
  partner_manual_rank/static/description/icon.png
  partner_manual_rank/static/description/index.html
  partner_manual_rank/tests/__init__.py
  partner_manual_rank/tests/test_res_partner.py
  partner_manual_rank/views/res_partner.xml
Labels: approved, bot is merging ⏳

#1839 [16.0}[IMP] ...multi_relation: better overlapping constraint error
  partner_multi_relation/models/res_partner_relation.py
Labels: enhancement, needs review, bot is merging ⏳, no stale

#1987 [18.0][MIG] partner_contact_age_range: Migration to 18.0
  partner_contact_age_range/README.rst
  partner_contact_age_range/__init__.py
  partner_contact_age_range/__manifest__.py
  partner_contact_age_range/data/age_range_cron.xml
  partner_contact_age_range/i18n/ca.po
  partner_contact_age_range/i18n/es.po
  partner_contact_age_range/i18n/fr.po
  partner_contact_age_range/i18n/it.po
  partner_contact_age_range/i18n/partner_contact_age_range.pot
  partner_contact_age_range/models/__init__.py
  partner_contact_age_range/models/res_partner.py
  partner_contact_age_range/models/res_partner_age_range.py
  partner_contact_age_range/pyproject.toml
  partner_contact_age_range/readme/CONTRIBUTORS.md
  partner_contact_age_range/readme/DESCRIPTION.md
  partner_contact_age_range/readme/USAGE.md
  partner_contact_age_range/security/ir.model.access.csv
  partner_contact_age_range/static/description/icon.png
  partner_contact_age_range/static/description/image1.png
  partner_contact_age_range/static/description/image2.png
  partner_contact_age_range/static/description/index.html
  partner_contact_age_range/tests/__init__.py
  partner_contact_age_range/tests/test_res_partner_age_range.py
  partner_contact_age_range/views/res_partner_age_range_view.xml
  partner_contact_age_range/views/res_partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1399 [12.0] Backport `partner_stage`
  partner_stage/README.rst
  partner_stage/__init__.py
  partner_stage/__manifest__.py
  partner_stage/data/partner_stage_data.xml
  partner_stage/i18n/partner_stage.pot
  partner_stage/init_hook.py
  partner_stage/models/__init__.py
  partner_stage/models/res_partner.py
  partner_stage/models/res_partner_stage.py
  partner_stage/readme/CONFIGURATION.rst
  partner_stage/readme/CONTRIBUTORS.rst
  partner_stage/readme/DESCRIPTION.rst
  partner_stage/readme/USAGE.rst
  partner_stage/security/ir.model.access.csv
  partner_stage/static/description/icon.png
  partner_stage/static/description/index.html
  partner_stage/tests/__init__.py
  partner_stage/tests/test_partner_stage.py
  partner_stage/views/res_partner_stage_views.xml
  partner_stage/views/res_partner_views.xml
  setup/partner_stage/odoo/addons/partner_stage
  setup/partner_stage/setup.py
Labels: approved, bot is merging ⏳, no stale

#1604 [16.0][IMP] partner_company_type: allow to set up countries and states, display shortcut in name
  partner_company_type/README.rst
  partner_company_type/__manifest__.py
  partner_company_type/migrations/16.0.1.0.1/post-migration.py
  partner_company_type/models/res_partner.py
  partner_company_type/models/res_partner_company_type.py
  partner_company_type/readme/CONTRIBUTORS.rst
  partner_company_type/readme/DESCRIPTION.rst
  partner_company_type/static/description/index.html
  partner_company_type/tests/test_res_partner_company_type.py
  partner_company_type/views/res_partner.xml
  partner_company_type/views/res_partner_company_type.xml
Labels: approved, bot is merging ⏳, needs more information

#2070 [14.0][IMP][partner_tier_validation] ensure default state at partner …
  partner_tier_validation/models/res_partner.py
  partner_tier_validation/tests/test_tier_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#2072 [16.0][IMP] partner_contact_department: add active and sequence fields
  partner_contact_department/models/res_partner.py
  partner_contact_department/views/res_partner_department_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2096 [18.0] [MIG] partner_search_alias: Migration to 18.0
  partner_search_alias/README.rst
  partner_search_alias/__init__.py
  partner_search_alias/__manifest__.py
  partner_search_alias/i18n/it.po
  partner_search_alias/i18n/partner_search_alias.pot
  partner_search_alias/models/__init__.py
  partner_search_alias/models/res_partner.py
  partner_search_alias/pyproject.toml
  partner_search_alias/readme/DESCRIPTION.md
  partner_search_alias/static/description/icon.png
  partner_search_alias/static/description/index.html
  partner_search_alias/tests/__init__.py
  partner_search_alias/tests/test_partner_search_alias.py
  partner_search_alias/views/res_partner_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2147 [18.0][PORT][IMP] crm_partner_company_group: show company_group_id on list and form view
  crm_partner_company_group/views/opportunity_view.xml
Labels: approved, bot is merging ⏳
