Repository OCA/partner-contact, pull requests merged in 2025-01, with the labels that each got.

#1926 [FIX] partner_second_lastname: required was not done properly
  partner_second_lastname/views/res_partner.xml
  partner_second_lastname/views/res_user.xml
Labels: approved, bot is merging ⏳

#1877 [18.0][MIG] partner_stage: Migration to 18.0
  partner_stage/README.rst
  partner_stage/__init__.py
  partner_stage/__manifest__.py
  partner_stage/data/partner_stage_data.xml
  partner_stage/i18n/es.po
  partner_stage/i18n/it.po
  partner_stage/i18n/partner_stage.pot
  partner_stage/i18n/pt.po
  partner_stage/init_hook.py
  partner_stage/models/__init__.py
  partner_stage/models/res_partner.py
  partner_stage/models/res_partner_stage.py
  partner_stage/pyproject.toml
  partner_stage/readme/CONFIGURATION.rst
  partner_stage/readme/CONTRIBUTORS.md
  partner_stage/readme/DESCRIPTION.md
  partner_stage/readme/USAGE.md
  partner_stage/security/ir.model.access.csv
  partner_stage/static/description/icon.png
  partner_stage/static/description/index.html
  partner_stage/tests/__init__.py
  partner_stage/tests/test_partner_stage.py
  partner_stage/views/res_partner_stage_views.xml
  partner_stage/views/res_partner_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1953 [16.0][FIX] partner_duns: Replace deprecated SavepointCase with TransactionCase
  partner_duns/static/description/index.html
  partner_duns/tests/test_partner_duns.py
Labels: bot is merging ⏳

#1821 [16.0][IMP] partner_multi_relation: connections for inactive partners should be inactive
  partner_multi_relation/__manifest__.py
  partner_multi_relation/models/res_partner_relation_all.py
  partner_multi_relation/views/ir_actions_act_window.xml
  partner_multi_relation/views/ir_ui_menu.xml
  partner_multi_relation/views/res_partner.xml
  partner_multi_relation/views/res_partner_relation_all.xml
Labels: bot is merging ⏳, stale

#1964 [18.0][MIG] partner_priority: Migration to 18.0
  partner_priority/README.rst
  partner_priority/__init__.py
  partner_priority/__manifest__.py
  partner_priority/data/partner_priority_data.xml
  partner_priority/i18n/es.po
  partner_priority/i18n/partner_priority.pot
  partner_priority/models/__init__.py
  partner_priority/models/partner_priority.py
  partner_priority/models/res_partner.py
  partner_priority/pyproject.toml
  partner_priority/readme/CONTRIBUTORS.md
  partner_priority/readme/DESCRIPTION.md
  partner_priority/readme/USAGE.md
  partner_priority/security/ir.model.access.csv
  partner_priority/static/description/icon.png
  partner_priority/static/description/index.html
  partner_priority/views/partner_priority.xml
  partner_priority/views/res_partner.xml
Labels: bot is merging ⏳

#1958 [IMP] [16.0] partner_industry_secondary: Add an option to display Child Industries first on it's name
  partner_industry_secondary/README.rst
  partner_industry_secondary/i18n/es.po
  partner_industry_secondary/i18n/partner_industry_secondary.pot
  partner_industry_secondary/models/res_config_settings.py
  partner_industry_secondary/models/res_partner_industry.py
  partner_industry_secondary/readme/CONFIGURE.rst
  partner_industry_secondary/readme/CONTRIBUTORS.rst
  partner_industry_secondary/readme/DESCRIPTION.rst
  partner_industry_secondary/readme/USAGE.rst
  partner_industry_secondary/static/description/index.html
  partner_industry_secondary/tests/test_res_partner_industry.py
  partner_industry_secondary/views/res_config_settings.xml
Labels: needs review, approved, bot is merging ⏳

#1869 [17.0][ADD] partner_title_active
  partner_title_active/README.rst
  partner_title_active/__init__.py
  partner_title_active/__manifest__.py
  partner_title_active/models/__init__.py
  partner_title_active/models/res_partner_title.py
  partner_title_active/pyproject.toml
  partner_title_active/tests/__init__.py
  partner_title_active/tests/test_partner_title.py
  partner_title_active/views/res_partner_title.xml
Labels: approved, ready to merge, bot is merging ⏳

#1962 [17.0][FIX] partner_stage: rule access_partner_stage_read has no group
  partner_stage/security/ir.model.access.csv
Labels: approved, ready to merge, bot is merging ⏳

#1963 [16.0][ADD] partner_salesperson_propagate
  partner_salesperson_propagate/README.rst
  partner_salesperson_propagate/__init__.py
  partner_salesperson_propagate/__manifest__.py
  partner_salesperson_propagate/models/__init__.py
  partner_salesperson_propagate/models/res_partner.py
  partner_salesperson_propagate/readme/CONTRIBUTORS.rst
  partner_salesperson_propagate/readme/DESCRIPTION.rst
  partner_salesperson_propagate/static/description/index.html
  partner_salesperson_propagate/tests/__init__.py
  partner_salesperson_propagate/tests/test_partner_salesperson_propagate.py
  setup/partner_salesperson_propagate/odoo/addons/partner_salesperson_propagate
  setup/partner_salesperson_propagate/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1932 [17.0][IMP] partner_identification: Add chatter in res.partner.id_number form pop-up
  partner_identification/views/res_partner_id_number_view.xml
  partner_identification/views/res_partner_view.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1936 [17.0] [IMP] partner_fax: option to display fax in the qweb contact widget
  partner_fax/README.rst
  partner_fax/__manifest__.py
  partner_fax/models/ir_qweb_fields.py
  partner_fax/readme/CONTRIBUTORS.md
  partner_fax/static/description/index.html
  partner_fax/tests/__init__.py
  partner_fax/tests/test_qweb_contact_field.py
  partner_fax/views/templates.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1841 [16.0][IMP] base_location_geonames_import: manually add zip files to folder
  base_location_geonames_import/README.rst
  base_location_geonames_import/data/zips/GR.txt
  base_location_geonames_import/data/zips/KY.txt
  base_location_geonames_import/readme/CONFIGURE.rst
  base_location_geonames_import/static/description/index.html
  base_location_geonames_import/wizard/geonames_import.py
Labels: approved, bot is merging ⏳, stale
