Repository OCA/partner-contact, pull requests merged in 2025-06, with the labels that each got.

#2012 [17.0][MIG] partner_category_type: Migration to 17.0
  partner_category_type/README.rst
  partner_category_type/__init__.py
  partner_category_type/__manifest__.py
  partner_category_type/i18n/it.po
  partner_category_type/i18n/partner_category_type.pot
  partner_category_type/models/__init__.py
  partner_category_type/models/res_partner_category.py
  partner_category_type/pyproject.toml
  partner_category_type/readme/CONTRIBUTORS.md
  partner_category_type/readme/DESCRIPTION.md
  partner_category_type/static/description/icon.png
  partner_category_type/static/description/index.html
  partner_category_type/tests/__init__.py
  partner_category_type/tests/test_partner_category_type.py
  partner_category_type/views/res_partner_category_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1997 [18.0][MIG] partner_deduplicate_filter: Migration to 18.0
  partner_deduplicate_filter/README.rst
  partner_deduplicate_filter/__init__.py
  partner_deduplicate_filter/__manifest__.py
  partner_deduplicate_filter/i18n/crm_deduplicate_filter.pot
  partner_deduplicate_filter/i18n/de.po
  partner_deduplicate_filter/i18n/es.po
  partner_deduplicate_filter/i18n/hr.po
  partner_deduplicate_filter/i18n/it.po
  partner_deduplicate_filter/i18n/nl_NL.po
  partner_deduplicate_filter/i18n/partner_deduplicate_filter.pot
  partner_deduplicate_filter/i18n/sk.po
  partner_deduplicate_filter/i18n/sl.po
  partner_deduplicate_filter/i18n/tr.po
  partner_deduplicate_filter/pyproject.toml
  partner_deduplicate_filter/readme/CONTRIBUTORS.md
  partner_deduplicate_filter/readme/DESCRIPTION.md
  partner_deduplicate_filter/readme/USAGE.md
  partner_deduplicate_filter/static/description/icon.png
  partner_deduplicate_filter/static/description/icon.svg
  partner_deduplicate_filter/static/description/index.html
  partner_deduplicate_filter/tests/__init__.py
  partner_deduplicate_filter/tests/test_partner_deduplicate_filter.py
  partner_deduplicate_filter/wizards/__init__.py
  partner_deduplicate_filter/wizards/partner_merge.py
  partner_deduplicate_filter/wizards/partner_merge_view.xml
Labels: approved, bot is merging ⏳

#2073 [16.0][FIX] partner_contact_department: zip() takes no keyword arguments
  partner_contact_department/models/res_partner.py
Labels: approved, ready to merge, bot is merging ⏳
