Repository OCA/partner-contact, pull requests merged in 2025-03, with the labels that each got.

#2009 [FIX] partner_contact_department: really order by name
  partner_contact_department/models/res_partner.py
  partner_contact_department/tests/test_recursion.py
Labels: bug, approved, ready to merge, bot is merging ⏳

#1906 [18.0][MIG] partner_vat_unique: Migration to 18.0
  partner_vat_unique/README.rst
  partner_vat_unique/__init__.py
  partner_vat_unique/__manifest__.py
  partner_vat_unique/i18n/de.po
  partner_vat_unique/i18n/es.po
  partner_vat_unique/i18n/fr.po
  partner_vat_unique/i18n/hr.po
  partner_vat_unique/i18n/it.po
  partner_vat_unique/i18n/partner_vat_unique.pot
  partner_vat_unique/i18n/pt.po
  partner_vat_unique/models/__init__.py
  partner_vat_unique/models/res_config_settings.py
  partner_vat_unique/models/res_partner.py
  partner_vat_unique/pyproject.toml
  partner_vat_unique/readme/CONTRIBUTORS.md
  partner_vat_unique/readme/DESCRIPTION.md
  partner_vat_unique/readme/INSTALL.md
  partner_vat_unique/readme/ROADMAP.md
  partner_vat_unique/static/description/icon.png
  partner_vat_unique/static/description/index.html
  partner_vat_unique/tests/__init__.py
  partner_vat_unique/tests/test_vat_unique.py
  partner_vat_unique/views/res_config_settings_views.xml
Labels: needs review, migration, bot is merging ⏳

#1732 [17.0][MIG] partner_tier_validation: Migrate to 17.0
  partner_tier_validation/README.rst
  partner_tier_validation/__init__.py
  partner_tier_validation/__manifest__.py
  partner_tier_validation/data/tier_definition.xml
  partner_tier_validation/i18n/es.po
  partner_tier_validation/i18n/it.po
  partner_tier_validation/i18n/partner_tier_validation.pot
  partner_tier_validation/models/__init__.py
  partner_tier_validation/models/res_partner.py
  partner_tier_validation/models/tier_definition.py
  partner_tier_validation/pyproject.toml
  partner_tier_validation/readme/CONFIGURATION.rst
  partner_tier_validation/readme/CONTRIBUTORS.md
  partner_tier_validation/readme/DESCRIPTION.md
  partner_tier_validation/readme/INSTALL.md
  partner_tier_validation/readme/USAGE.md
  partner_tier_validation/static/description/icon.png
  partner_tier_validation/static/description/index.html
  partner_tier_validation/test-requirements.txt
  partner_tier_validation/tests/__init__.py
  partner_tier_validation/tests/test_tier_validation.py
  partner_tier_validation/views/res_partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1888 [18.0][mig] partner_contact_role
  partner_contact_role/README.rst
  partner_contact_role/__init__.py
  partner_contact_role/__manifest__.py
  partner_contact_role/i18n/es.po
  partner_contact_role/i18n/fr.po
  partner_contact_role/i18n/it.po
  partner_contact_role/i18n/partner_contact_role.pot
  partner_contact_role/models/__init__.py
  partner_contact_role/models/res_partner.py
  partner_contact_role/pyproject.toml
  partner_contact_role/readme/CONFIGURE.md
  partner_contact_role/readme/CONTRIBUTORS.md
  partner_contact_role/readme/CREDITS.md
  partner_contact_role/readme/DESCRIPTION.md
  partner_contact_role/readme/USAGE.md
  partner_contact_role/security/ir.model.access.csv
  partner_contact_role/static/description/icon.png
  partner_contact_role/static/description/index.html
  partner_contact_role/views/res_partner.xml
  partner_contact_role/views/res_partner_role.xml
Labels: approved, ready to merge, bot is merging ⏳

#1943 [MIG][18.0] partner_contact_tags_in_popup from 16.0
  partner_contact_tags_in_popup/README.rst
  partner_contact_tags_in_popup/__init__.py
  partner_contact_tags_in_popup/__manifest__.py
  partner_contact_tags_in_popup/i18n/it.po
  partner_contact_tags_in_popup/i18n/partner_contact_tags_in_popup.pot
  partner_contact_tags_in_popup/pyproject.toml
  partner_contact_tags_in_popup/readme/CONTRIBUTORS.md
  partner_contact_tags_in_popup/readme/DESCRIPTION.md
  partner_contact_tags_in_popup/static/description/icon.png
  partner_contact_tags_in_popup/static/description/index.html
  partner_contact_tags_in_popup/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#2023 [FIX] partner_contact_department: make display name lang-aware
  partner_contact_department/README.rst
  partner_contact_department/__manifest__.py
  partner_contact_department/migrations/16.0.1.3.0/post-migration.py
  partner_contact_department/models/res_partner.py
  partner_contact_department/static/description/index.html
  partner_contact_department/tests/test_recursion.py
  partner_contact_department/views/res_partner_department_view.xml
Labels: needs review, approved, bot is merging ⏳

#1980 [18.0][MIG] partner_deduplicate_acl: Migration to 18.0
  partner_deduplicate_acl/README.rst
  partner_deduplicate_acl/__init__.py
  partner_deduplicate_acl/__manifest__.py
  partner_deduplicate_acl/i18n/de.po
  partner_deduplicate_acl/i18n/es.po
  partner_deduplicate_acl/i18n/fr.po
  partner_deduplicate_acl/i18n/hr.po
  partner_deduplicate_acl/i18n/it.po
  partner_deduplicate_acl/i18n/nl_NL.po
  partner_deduplicate_acl/i18n/partner_deduplicate_acl.pot
  partner_deduplicate_acl/i18n/pt_BR.po
  partner_deduplicate_acl/i18n/sk.po
  partner_deduplicate_acl/i18n/sl.po
  partner_deduplicate_acl/i18n/tr.po
  partner_deduplicate_acl/i18n/zh_CN.po
  partner_deduplicate_acl/images/perms.png
  partner_deduplicate_acl/pyproject.toml
  partner_deduplicate_acl/readme/CONFIGURE.md
  partner_deduplicate_acl/readme/CONTRIBUTORS.md
  partner_deduplicate_acl/readme/DESCRIPTION.md
  partner_deduplicate_acl/readme/USAGE.md
  partner_deduplicate_acl/security/ir.model.access.csv
  partner_deduplicate_acl/security/partner_deduplicate_acl_security.xml
  partner_deduplicate_acl/static/description/icon.png
  partner_deduplicate_acl/static/description/icon.svg
  partner_deduplicate_acl/static/description/index.html
  partner_deduplicate_acl/tests/__init__.py
  partner_deduplicate_acl/tests/test_partner_deduplicate_acl.py
  partner_deduplicate_acl/views/base_partner_merge_view.xml
  partner_deduplicate_acl/wizards/__init__.py
  partner_deduplicate_acl/wizards/partner_merge.py
  partner_deduplicate_acl/wizards/partner_merge_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1984 [17.0][MIG] partner_contact_address_default: Migration to 17.0
  partner_contact_address_default/README.rst
  partner_contact_address_default/__init__.py
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/i18n/es.po
  partner_contact_address_default/i18n/fr.po
  partner_contact_address_default/i18n/fr_FR.po
  partner_contact_address_default/i18n/it.po
  partner_contact_address_default/i18n/partner_contact_address_default.pot
  partner_contact_address_default/i18n/pt.po
  partner_contact_address_default/models/__init__.py
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/pyproject.toml
  partner_contact_address_default/readme/CONTRIBUTORS.md
  partner_contact_address_default/readme/DESCRIPTION.md
  partner_contact_address_default/readme/USAGE.md
  partner_contact_address_default/static/description/icon.png
  partner_contact_address_default/static/description/index.html
  partner_contact_address_default/tests/__init__.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
  partner_contact_address_default/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#2036 [FIX] partner_contact_department: proper version bump
  partner_contact_department/__manifest__.py
Labels: bot is merging ⏳

#1880 [18.0][MIG] partner_email_check: Migration to 18.0
  partner_email_check/README.rst
  partner_email_check/__init__.py
  partner_email_check/__manifest__.py
  partner_email_check/demo/res_company_demo.xml
  partner_email_check/i18n/es.po
  partner_email_check/i18n/fr.po
  partner_email_check/i18n/it.po
  partner_email_check/i18n/partner_email_check.pot
  partner_email_check/models/__init__.py
  partner_email_check/models/res_company.py
  partner_email_check/models/res_config_settings.py
  partner_email_check/models/res_partner.py
  partner_email_check/pyproject.toml
  partner_email_check/readme/CONFIGURE.md
  partner_email_check/readme/CONTRIBUTORS.md
  partner_email_check/readme/CREDITS.md
  partner_email_check/readme/DESCRIPTION.md
  partner_email_check/readme/USAGE.md
  partner_email_check/static/description/icon.png
  partner_email_check/static/description/index.html
  partner_email_check/tests/__init__.py
  partner_email_check/tests/test_partner_email_check.py
  partner_email_check/views/base_config_view.xml
  requirements.txt
Labels: approved, migration, ready to merge, bot is merging ⏳
