Repository OCA/partner-contact, pull requests merged in 2025-05, with the labels that each got.

#2045 [17.0] [MIG] partner_priority: standard migration to 17.0
  partner_priority/README.rst
  partner_priority/__init__.py
  partner_priority/__manifest__.py
  partner_priority/data/partner_priority_data.xml
  partner_priority/i18n/es.po
  partner_priority/i18n/it.po
  partner_priority/i18n/partner_priority.pot
  partner_priority/models/__init__.py
  partner_priority/models/partner_priority.py
  partner_priority/models/res_partner.py
  partner_priority/pyproject.toml
  partner_priority/readme/CONTRIBUTORS.md
  partner_priority/readme/DESCRIPTION.md
  partner_priority/readme/USAGE.md
  partner_priority/security/ir.model.access.csv
  partner_priority/static/description/icon.png
  partner_priority/static/description/index.html
  partner_priority/views/partner_priority.xml
  partner_priority/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#2058 [17.0][IMP] base_location: Add city code to be used for other purposes distinct of zip code.
  base_location/models/res_city.py
  base_location/views/res_city_view.xml
Labels: approved, bot is merging ⏳

#1886 [17.0][ADD] partner_utm_source
  partner_utm_source/README.rst
  partner_utm_source/__init__.py
  partner_utm_source/__manifest__.py
  partner_utm_source/models/__init__.py
  partner_utm_source/models/res_partner.py
  partner_utm_source/pyproject.toml
  partner_utm_source/readme/CONTRIBUTORS.md
  partner_utm_source/readme/DESCRIPTION.md
  partner_utm_source/static/description/index.html
  partner_utm_source/views/partner_views.xml
Labels: needs review, approved, bot is merging ⏳

#2056 [FIX] [18.0] partner_stage: Groupby Stages
  partner_stage/models/res_partner.py
  partner_stage/tests/test_partner_stage.py
Labels: bot is merging ⏳

#1920 [18.0][MIG] partner_duns: Migration to 18.0
  partner_duns/README.rst
  partner_duns/__init__.py
  partner_duns/__manifest__.py
  partner_duns/i18n/it.po
  partner_duns/i18n/partner_duns.pot
  partner_duns/models/__init__.py
  partner_duns/models/res_partner.py
  partner_duns/pyproject.toml
  partner_duns/readme/CONTRIBUTORS.md
  partner_duns/readme/DESCRIPTION.md
  partner_duns/static/description/icon.png
  partner_duns/static/description/index.html
  partner_duns/tests/__init__.py
  partner_duns/tests/test_partner_duns.py
  partner_duns/views/res_partner.xml
Labels: bot is merging ⏳, stale

#2062 [17.0][IMP] partner_property: add kanban view to display properties
  partner_property/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#2063 [18.0][FIX] partner_tz: fix partner form rendering
  partner_tz/views/res_partner.xml
Labels: bug, approved, bot is merging ⏳
